### ISSUE TITLE
Stellar Map: after loading a game several settings are turned on which where off

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4708] opened 2019-10-12 17:22 UTC
OS: Fedora 29
Version: 20191009

after loading a saved game, the settings for "DRAW VERTICAL LINES" "Label out-of-range system" "Label uninhabited system"  are shown off, but are internally on:

![Bildschirmfoto vom 2019-10-12 19-19-48](https://user-images.githubusercontent.com/8317797/66705342-77250b00-ed25-11e9-8f17-2b14906a38b1.jpg)

(and yes, i know i have 18 brs open now :) )

**Comment by craigo-** [comment] 2019-10-12 19:10
I've been meaning to log an issue for this for a while - confirmed.

**Comment by Web-eWorks** [comment] 2020-07-07 03:34
Closing as duplicate of #4815 - we'll track this issue there.

**Closed by Web-eWorks** 2020-07-07 03:34 UTC
Labels: Cosmetic or UI, Unexpected behaviour
