### ISSUE TITLE
Space Station docking fail/bug

### ISSUE THREAD

**Issue by ghost** [pioneerspacesim/pioneer#3974] opened 2017-04-16 19:48 UTC
Hello, i hope everybody understand my bad english.

I can't dock some space stations (near planet orbit) with the autopilot or manualy.
When i want to land the ship, it will fly through the station floor without crashing.

It seems this happend only on some station thats flying near the planet. Travis Citadel is one of them, but there are much more. No matter what ship.

I'm new in Pioneer. That bug is since March when I started to play the game.

I hope someone can fix this ;)
![img_20170416_212111](https://cloud.githubusercontent.com/assets/27641036/25073790/45177d0e-22ee-11e7-9e14-960b401af4bc.jpg)

Ubuntu Mate 16.04.02
AMD E2-2000
AMD HD 7340
8GB Ram

Pioneer latest stable build (April)

**Comment by nozmajner** [comment] 2017-04-16 20:02
Hi!

Could you please provide a save or give the system name, so we could test?

**Comment by impaktor** [comment] 2017-04-17 08:09
I just doubled checked, and the (linux) build is indeed from latest master, so the auto-pilot bug fix should be in there.  

So this is a new bug, I assume. And it happens manually as well. Something with funky collision detection.

**Comment by edragon35** [comment] 2017-04-17 09:44
It happend in System Ceeth (-4, -11, -10), Cook, Travis Citadel

**Comment by nozmajner** [comment] 2017-04-17 11:24
Hmm, I can land there without problems. Might be platform specific somehow? Collision mesh left out for some reason?
I also tried flying in at the exit gate after asking for clearance, but it auto-landed me without problem.

I checked the fresh linux version, and the collision mesh is in place if I view it from the win modelviewer.

@edragon35 I think you are doing it right, but just to make sure: do you ask for docking clearance?
 If you you should be auto-landed as soon as you enter the gate of the station. You can't dock fully manually (yet, hopefully).

**Comment by edragon35** [comment] 2017-04-17 13:31
I ask for docking clearance. I tried all options.

I reinstall pioneer and try it again later.

**Comment by nozmajner** [comment] 2017-04-17 14:04
Could you please try one other thing?
Turn on the model debug flags for displaying collision meshes, and see if there's some huge red rectangle wireframes at the gates and inside the stations?

First, select the station as target. Then enter these commands to the debug console. (Case sensitive, but I guess I don't have to point that out to a linux user :) )
```
model = import('Game').player:GetNavTarget().model
model:SetDebugFlags({"COLLMESH"})
```

Also, judging by the orbits Torvald's platform around Earth should also have this error. Although it's not the same station model...

**Comment by edragon35** [comment] 2017-04-17 17:39
Ok, i goint to try this later

**Comment by edragon35** [comment] 2017-04-17 18:13
Yes, there are many red wireframes in the station.

![img_20170417_200315](https://cloud.githubusercontent.com/assets/27641036/25098802/31718486-23aa-11e7-9005-f4aa45db23e2.jpg)

![img_20170417_200424](https://cloud.githubusercontent.com/assets/27641036/25098808/3821a25c-23aa-11e7-9ea1-ebcf892f9394.jpg)

![img_20170417_200344](https://cloud.githubusercontent.com/assets/27641036/25098829/47acbaae-23aa-11e7-9c9c-e022d49069d0.jpg)

**Comment by nozmajner** [comment] 2017-04-17 18:29
Yupp, collision mesh is in place.
Could you please provide a savegame when it happens?

**Comment by impaktor** [comment] 2017-04-17 18:35
(Maybe not worth mentioning, but it's possible / known that one can "tunnel" through terrain (and space stations?) if one just has the right angle, and low spead and persistance.)

**Comment by edragon35** [comment] 2017-04-17 18:40
Here's the savegame

[Savegame Travis Citadel.zip](https://github.com/pioneerspacesim/pioneer/files/926357/Savegame.Travis.Citadel.zip)

**Comment by edragon35** [comment] 2017-04-20 06:43
Reinstall does not solve the problem.

I'm noticed that AI ship also cannot dock and remain in the station entrance.

**Comment by spolen88** [comment] 2017-05-18 05:55
you said "That bug is since March when I started to play the game.", Is it possible that the problem could be a broken save from an earlier version? if you have the save from an earlier version try on a new game and see if it happens there.

**Comment by Bodasey** [comment] 2021-01-22 13:35
another old one? I have never seen that.

**Comment by Web-eWorks** [comment] 2021-01-23 19:04
Closing this as inactive; I haven't seen anyone reproduce it in the last two years.

**Closed by Web-eWorks** 2021-01-23 19:04 UTC
