### ISSUE TITLE
Speed limiter overlaps other UI elements

### ISSUE THREAD

**Issue by SomenameIchose** [pioneerspacesim/pioneer#5738] opened 2024-02-03 18:56 UTC
An interface bug. Game version is 20240203 e7f3122
[output.txt](https://github.com/pioneerspacesim/pioneer/files/14152565/output.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/14152566/opengl.txt)
![screenshot-20240203-225324](https://github.com/pioneerspacesim/pioneer/assets/154741968/5d240227-3739-46a0-a377-3d8800f07980)

Edit by @nozmajner: 
The speed limit preset buttons are misaligned and overlapping the speed limiter itself when it is open:
![image](https://github.com/pioneerspacesim/pioneer/assets/4182678/ac2bf577-3cdc-45db-ba3a-709187ae19e9)

**Comment by Web-eWorks** [comment] 2024-02-03 22:15
Generally speaking, "an interface bug" is not a valid issue description. Please keep in mind that you need to be specific about describing where, when, and *what* you think is wrong when creating an issue.

**Comment by Web-eWorks** [comment] 2024-03-16 18:36
Closing as duplicate of #5800.

**Closed by Web-eWorks** 2024-03-16 18:36 UTC
Labels: Cosmetic or UI
