### ISSUE TITLE
Pioneer Only Shows A Black Windowed Screen

### ISSUE THREAD

**Issue by kotenok2000** [pioneerspacesim/pioneer#5235] opened 2021-08-03 17:24 UTC
### Observed behaviour
opengl error(s) during frame: in function graphics::ogl::texturegl::texturegl on line 96 gl_invalid_operation`

### Steps to reproduce

__My pioneer version (and OS):__
Microsoft Windows [Version 10.0.19043.1110]
pioneer-20210723-win
nvidia driver 471.41
NVIDIA GeForce GTX 1650
cpu AMD Ryzen 3 3100 4-Core Processor

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/6925951/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6925953/output.txt)

**Comment by Web-eWorks** [comment] 2021-08-03 18:31
Please set `EnableGLDebug=1` in your `config.ini` file, re-run the program, and provide us the output.txt log file. My guess is this is caused by the same issue as #5162 (right down to the name of the issue), so try the fix listed there as well.

**Comment by kotenok2000** [comment] 2021-08-03 18:32
disabling antialiasing helped

**Comment by Web-eWorks** [comment] 2021-08-14 22:57
Closing as resolved.

**Closed by Web-eWorks** 2021-08-14 22:57 UTC
