### ISSUE TITLE
Cannot open game

### ISSUE THREAD

**Issue by derpderpderpdarp** [pioneerspacesim/pioneer#5135] opened 2021-02-04 06:58 UTC
help,
I installed the pioneer version of 2021-02-03, and every time I open the game it shows me an error message says a file is missing and cannot open the game.

**Comment by impaktor** [comment] 2021-02-04 07:29
There is absolutely nothing we can do unless you tell us what file it is that it claims is missing.

And what's your OS? Windows?

**Comment by etam** [comment] 2021-02-04 23:36
Probably duplicate of #5138 ?

**Comment by geeksmooth** [comment] 2021-02-05 21:22
confirm same problem...  file:
Fatal: Error while loading Space Station data (check stdout/output.txt).

and yes... probably duplicate of #5138

[output.txt](https://github.com/pioneerspacesim/pioneer/files/5935383/output.txt)

**Closed** 2021-02-08 10:02 UTC
