### ISSUE TITLE
Lua serializer '(null)' tried to serialize an invalid 'SpaceStation' object

### ISSUE THREAD

**Issue by impioneer** [pioneerspacesim/pioneer#3852] opened 2016-11-02 12:26 UTC
### Observed behaviour

The error described in title (or similar, for example it could be 'Ship' instead of 'SpaceStation') and crashing of the game occurs on Save (manual) or autosave (when docking to a station).

### Steps to reproduce

__My pioneer version (and OS):__

Linux 64 - 20161028, both pre-built and compiled from source.
I use Debian Jessie (stable) 64 bit.

**Comment by laarmen** [comment] 2016-11-02 12:27
Does this crash happen systematically?

**Comment by impioneer** [comment] 2016-11-02 12:28
It happened many time, but not on every save

**Comment by ecraven** [comment] 2016-11-02 12:29
could you paste the entire error message here, not just the last line?

**Comment by laarmen** [comment] 2016-11-02 12:30
Sadly, our serializer errors are succinct, to say the least.

**Comment by impioneer** [comment] 2016-11-02 12:30
That's the entire message. It's a small window with the title "Pioneer error" and then the line "Lua ..."  and "OK" button. That's all

**Comment by laarmen** [comment] 2016-11-02 12:34
Just in case, any mod installed?

**Comment by impioneer** [comment] 2016-11-02 12:35
no

**Comment by impioneer** [comment] 2016-11-02 12:39
IDK if this helps: I'm looking into the file ~/.xsession-errors
The last line before the serializer error is "TradeShips: Removed 5 ships before serialization"

**Comment by laarmen** [comment] 2016-11-02 12:44
Thanks. However, this doesn't really help (unless tradeships.lua triggers
autosaves, which I doubt, but cannot be sure of since it is a big can of
worms I won't open again.)

**Comment by impioneer** [comment] 2016-11-02 12:45
Autosave was disabled in this case, I used a manual Save.

Is this a known bug? Should I try any earlier version? Any known workaround? Really liked this game, but it's not worth much without being able to save :(

**Comment by laarmen** [comment] 2016-11-02 12:46
What we need is a better error output to pinpoint where exactly do things
go wrong. I'll work on that tonight.

Yes, I will, and not just try to ;-)

**Comment by laarmen** [comment] 2016-11-02 12:47
You could try an earlier version (like one from maybe 3 months ago) , and
maybe, if you're courageous, bisect from there of it works?

**Comment by impioneer** [comment] 2016-11-02 12:50
Thanks for your effort.

There were several releases in July, any specific one?

Also, I don't understand your phrase " bisect from there of it works"

**Comment by impaktor** [comment] 2016-11-02 12:52
> Is this a known bug?

No, not until now. Probably something recent. If you can figure out  how we can reproduce it, or give more info on error, then we can (hopefully) squash the bug.

**Comment by impaktor** [comment] 2016-11-02 12:52
> Also, I don't understand your phrase " bisect from there of it works"

= Try to find the first build with the bug.

**Comment by laarmen** [comment] 2016-11-02 12:53
Bisect from there if it works. Using git bisect, that is. If you dabbled
with git, you could check it out (git help bisect), it is a fantastic tool
to track down regressions.

I don't precisely know which revision would be the best to start with, but
@impaktor might know best.

**Comment by impaktor** [comment] 2016-11-02 12:55
Generally, if there are many builds close, that probably means the build from the day(s) before had some bad bug that was fixed the next day(s).

**Comment by impioneer** [comment] 2016-11-02 12:56
> If you can figure out how we can reproduce it, or give more info on error, then we can (hopefully) squash the bug.
To reproduce, I suppose use Debian 64, put autosave ON and play.

>  give more info on error
What additional info do you need? 

> git help bisect
Will try

**Comment by impioneer** [comment] 2016-11-02 13:13
Where can I find previous versions binary builds?

**Comment by impaktor** [comment] 2016-11-02 13:21
https://sourceforge.net/projects/pioneerspacesim/files/

**Comment by laarmen** [comment] 2016-11-02 19:08
If you are able to compile a new version, you could try my branch https://github.com/laarmen/pioneer/tree/serializer_crash (see also #3853 )

**Comment by impioneer** [comment] 2016-11-03 08:08
I tried versions 20160724, 20160814, 20160907, 20161022 - all worked fine, not a single error or crash.

Then I tried laarmen's branch (see above), it crashed on the second mission I did (docking with autopilot with autosave enabled), this is the error message:

`error: [string "[T] @modules/SearchRescue/SearchRescue.lua"]:707: Max must be bigger than min in random number range
stack traceback:
        [C]: in function 'Integer'
        [string "[T] @modules/SearchRescue/SearchRescue.lua"]:707: in function 'createTargetShip'
        [string "[T] @modules/SearchRescue/SearchRescue.lua"]:1983: in function 'cb'
        [string "[T] @libs/Event.lua"]:34: in function '?'
        [string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>
`

**Comment by laarmen** [comment] 2016-11-03 08:10
Uh. That's a weird one.

**Comment by impioneer** [comment] 2016-11-03 08:45
Here's another one (same setting as previously):
```
error: Lua serializer '.SpaceStation.equipmentPrice.<userdata>' tried to serialize an invalid 'SpaceStation' object
```

**Comment by laarmen** [comment] 2016-11-03 08:56
Ok, now we're talking. Somehow the object ends up nil.

**Comment by laarmen** [comment] 2016-11-03 09:50
Does the crash occur when you don't leave the system you started in?

**Comment by impioneer** [comment] 2016-11-03 11:25
I tried to play more. Got a few more crashes identical to the last one (with '.SpaceStation.equipmentPrice.<userdata>'), always at the moment of docking.

It seems though that the crash occurs only when I dock after a jump to another star system, that is, using hyperdrive. With traveling and docking to stations within the same star system, dockings are fine.

**Comment by laarmen** [comment] 2016-11-03 12:49
@impioneer thanks for your (really impressive) patience. Sadly, we weren't able to reproduce the bug on our end. Well, @ecraven wasn't at least.

**Comment by laarmen** [comment] 2016-11-03 16:16
Just to be clear, do all those crashes occur when starting a new game (and if so, from any starting point?), or when loading a savegame?

**Comment by karakai** [comment] 2016-11-04 08:32
Hello,
The same error is haunting my games...
I have tried with Earth and Bernard's star, as starting point, with a loaded savegame, and with one run without load until the error arises. So no mater how I start, the error is present. 

With manual saves, it occurs not only at docking (but it looks more frequent), but also if I save after exiting from hyperspace.

Another trial what I have made:
After entering to a new system : save was OK for many times
After docking to target station : save was OK for many times
After getting a new mission : the first save crashed 
After loading the last state, and getting the same mission: the save was OK for many times

The save of many times means 5-6 saves without doing anything else...

My setup if it matters: 
Inter core i7 8G RAM, Arch Linux x64

I hope this will be useful.
The game is really great!

**Comment by laarmen** [comment] 2016-11-04 09:17
Hi @karakai, thanks for the info.
Do you remember the mission in question?

**Comment by karakai** [comment] 2016-11-04 09:26
Sorry, I don't remember it...
The only thing I know, tat it was a taxi mission.
But I'm not sure if it depends on any mission. The error pops up randomly.

**Comment by laarmen** [comment] 2016-11-04 15:14
[16:00:04] <hauler> don't know if I tell already known things. It seems that #3852 is triggered by updateTotalHyperdriveFuel() inside Lobby.lua.
[16:00:04] <jameson> Issue #3852 [open]: Lua serializer '(null)' tried to serialize an invalid 'SpaceStation' object https://github.com/pioneerspacesim/pioneer/issues/3852 [ C++ code / Crash or hang ]
[16:01:02] <impaktor> laarmen: ^
[16:01:20] <laarmen> YEAAAAAAAAAAAAAAAAAAAAAAAH
[16:01:36] <laarmen> hauler++
[16:01:47] <impaktor> That also sounds like a function that might have changed at the same time the bug appeared.
[16:01:59] <laarmen> it does.
[16:02:48] <laarmen> Although I have no idea how it triggers the bug :/
[16:03:37] <hauler> Yes, that is strange
[16:03:57] <laarmen> oh, no, I have the explanation.
[16:04:20] <laarmen> in SpaceStation.GetEquipmentPrice at no point do we check if the station is a valid object.
[16:05:05] <impaktor> Why isn't the space station a valid object?
[16:05:11] <impaktor> Empty system?
[16:05:36] <JohnJ> Because Lobby.lua is running when the player isn't docked at a station?
[16:06:04] <laarmen> looks like it :/
[16:06:24] * john_cephalopoda (~john@unaffiliated/john-minetest/x-5335115) parts #pioneer ("Trees can see into your soul.")
[16:06:42] <laarmen> Well, not exactly.
[16:07:01] <laarmen> But lobby does register functions to be called on various triggers.
[16:07:02] * JohnJ doesn't actually know what "running" means in context :P
[16:07:20] <JohnJ> I guess it's supposed to unregister as soon as you undock?
[16:07:29] <laarmen> and those functions, well, closures, embed a station object.
[16:07:37] <laarmen> yeah, something like that. but it doesn't.
[16:08:33] <laarmen> See, that's why I don't do UI. always a PITA.
[16:09:34] <JohnJ> Is it actually proven that it's Lobby.lua at fault here btw?
[16:09:37] <laarmen> whenever the lobby is brought up, there's a new registration.
[16:10:09] <JohnJ> do they stack? :P
[16:10:12] <laarmen> JohnJ: not by me, but it would make a whole lot of sense. The station object gets stale, the player cargo changes, and BAM
[16:13:50] <impaktor> Something that needs fixing? Fixing in current UI, or in future imgui version?
[16:14:02] <laarmen> we need to fix it right now, yeah.
[16:14:05] <JohnJ> fixing now

**Comment by fluffyfreak** [comment] 2016-11-04 18:33
I think the lobby was mentioned in #3848 regarding not calling it when not docked / in actively in the lobby.

**Comment by laarmen** [comment] 2016-11-04 19:33
Allright, if you guys could try #3857 to see if it is still prone to crashes?

**Comment by impioneer** [comment] 2016-11-06 09:31
> Allright, if you guys could try #3857 to see if it is still prone to crashes?

Unfortunately, didn't work for me. Started a new game (from Earth), chose hyperspace delivery mission, crash on docking:

```
DEBUG: Jumps since warranty: 0, chance of failure (if > 0): 1/255
Warranty expires: 06:00:00 31 Dec 3200
updateTSTable:total:9,removed:9
GY-1587 enters frame Butcherworld
GY-1587 enters frame Butcherworld
GY-1587 docked with Whitfield Town ship:deneb
KJ-0436 enters frame Butcherworld
KJ-0436 enters frame Butcherworld
GY-1587 leaves frame Butcherworld
deneb jump status is not OK
GY-1587 enters frame Butcherworld
GY-1587 docked with Whitfield Town ship:deneb
LG-9045 enters frame Butcherworld
LG-9045 enters frame Butcherworld
LG-9045 docked with Whitfield Town ship:amphiesma
LG-9045 leaves frame Butcherworld
LG-9045 left GJ 2097 for NN 3789
cleanTSTable:total:11,active:8,removed:0
Hyperspace departure cloud leaves frame Butcherworld
GY-1587 leaves frame Butcherworld
deneb jump status is not OK
GY-1587 enters frame Butcherworld
GY-1587 docked with Whitfield Town ship:deneb
HB-3030 enters frame Butcherworld
HB-3030 enters frame Butcherworld
HB-3030 docked with Whitfield Town ship:storeria
NT-8509 enters frame Butcherworld
NT-8509 enters frame Butcherworld
NT-8509 docked with Whitfield Town ship:dsminer
GY-1587 leaves frame Butcherworld
deneb jump status is not OK
GY-1587 enters frame Butcherworld
GY-1587 docked with Whitfield Town ship:deneb
HZ-4393 enters frame Butcherworld
HZ-4393 enters frame Butcherworld
TradeShips: Removed 4 ships before serialization
error: Lua serializer '.SpaceStation.equipmentPrice.<userdata>' tried to serialize an invalid 'SpaceStation' object
```

**Comment by impioneer** [comment] 2016-11-06 09:34
Idk if it matters, since I saw that the PR was merged, I built from the master

**Comment by impaktor** [comment] 2016-11-06 10:15
@impioneer Which commit is you master on? (Just to make sure). If you're up to date, then yes, the fix is in upstream master.

@laarmen I don't know if you saw:
```
<JohnJ> laarmen: I'm probably missing something here, but doesn't that fix
        only work if all those update functions are called before the game is
        saved?                                                          [01:49]
<JohnJ> (after exiting a station)
```

I think I'll re-open this issue for now.

**Comment by impioneer** [comment] 2016-11-06 11:06
> @impioneer Which commit is you master on? (Just to make sure). If you're up to date, then yes, the fix is in upstream master.

 74d947f  with #3857 merged.
A also checked the file  data/ui/StationView/Lobby.lua to see that the version I use is included the changes.

**Comment by jaj22** [comment] 2016-11-07 01:27
Ok, having attempted to understand more of Pioneer's lua architecture with partial success, I think laarmen's fix is sound in principle. However, it seems to be missing a "return" after line 127 in Lobby.lua.

A related issue is that SpaceStation.lua has what looks like a straight misfeature. If functions such as GetEquipmentPrice() are called on a station that's not currently in the table, they will create an entry, which will then bomb on serialization.

**Comment by impioneer** [comment] 2016-11-07 11:13
#3859 seems to work! Played a few missions to other systems with autosave, no errors so far.

**Closed** 2016-11-07 12:57 UTC
Labels: C++ code, Crash or hang

**Comment by laarmen** [comment] 2016-11-07 12:59
Allright, that should be fixed. There remains to check for the station validity in SpaceStation:GetEquipmentPrice()
