### ISSUE TITLE
CLOSE? Crash in Combat missions when selecting System map after each kill

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5185] opened 2021-05-16 03:03 UTC
### Observed behaviour
In combat missions (with ships engaging),  if I select the System map after destroying the first ship, the game crashes without error message.
For example, I usually select the system map after the first ship is destroyed, in order to target the next "candidate" ship.

I can't tell yet if it happens in both cases of _single_ and _multiple_ enemies.
Will update if I am more sure about it.

Could this crash be related to:
- change of the mission status: first kill -> accomplished
- graphic - showing no more the destroyed ship in space
?

### Steps to reproduce
Accept a Combat mission.
Go to the planet orbit.
Destroy a ship.
Select the System map.
Crash.

__My pioneer version (and OS):__
20210205
Mint Cinnamon 20.1

**Comment by impaktor** [comment] 2021-05-16 05:59
It would probably help us a lot if you could get a [backtrace](https://pioneerwiki.com/wiki/FAQ#Debug_backtrace)

**Comment by Gliese852** [comment] 2021-05-16 06:56
@tropicalpioneer and also, please, specify the version of the program, you can see it, for example, here:
![image18](https://user-images.githubusercontent.com/18342621/118388006-6ee03080-b62a-11eb-8d48-bf66f0820d5f.png)
because it seems this is already fixed in the master

**Comment by tropicalpioneer** [comment] 2021-05-16 12:54
update:
Indeed the crash happens after _each_ kill 
Just tested it on a 3 enemy ships combat mission, crashed after each kill when I clicked the System Map.

That backtrace thing... It is a little bit technical, let's see if I get it.

**Comment by tropicalpioneer** [comment] 2021-05-29 15:38
Right, using the new version I have completed three combat missions with killings and the bug has not showed up yet.

**Comment by Gliese852** [comment] 2021-05-31 18:03
@tropicalpioneer I will close this issue, since I am almost 100% sure for what reason it happened in the old version and does not happen in the new one, we will assume that the problem is solved.

**Closed by Gliese852** 2021-05-31 18:03 UTC
