### ISSUE TITLE
Lua console doesn't handle back keyboard focus nicely

### ISSUE THREAD

**Issue by zonkmachine** [pioneerspacesim/pioneer#5598] opened 2023-07-20 17:00 UTC
Issue where the Lua Console won't give focus back to the keyboard after exiting.

As mentioned in https://github.com/pioneerspacesim/pioneer/issues/5287

### Observed behaviour and steps to reproduce

Open the Lua console and exit by pressing 'escape'. Open the Lua console again with a keyboard shortcut. You now need to press twice for the action to take place.

__My pioneer version (and OS):__
on current master (0f417f2810752fa547a92a24ce7c3f0b6b0f9931)
First noticed this on 65c3784f0636b283ec15ba761daa0062e4f628c7 and I suspect it goes back to df10b11def1bba8c157a4cb735f3438d473ff855
@Web-eWorks

**Comment by Web-eWorks** [comment] 2023-07-23 00:19
IIRC, this is caused by IMGUI eating the key-release event of the binding that opens the lua console. Thus the key doesn't appear de-asserted until it's pressed again after opening the console.

...the fix for this is stupidly easy, will push it to your PR.

**Comment by zonkmachine** [comment] 2023-07-23 00:41
> ...the fix for this is stupidly easy,

This was about as far as I got. Sweating for hours knowing there was a one-liner hidden somewhere.
Thanks! It now works like it should.

**Closed** 2023-07-23 00:51 UTC
