### ISSUE TITLE
Assassination missions fail

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#4154] opened 2017-09-16 18:10 UTC
### Observed behaviour

Every time I take on a termination mission, the mission status reverts to "failed" as soon as I have hyperjumped into the star system the assassination is to take place, this behaviour has happened every time without fail, different ships, different star systems, different builds. All other mission types work flawlessly.

![screenshot-20170916-181353](https://user-images.githubusercontent.com/32020353/30514612-98e327e0-9b10-11e7-83dd-c0a6429ad81f.png)

__My pioneer version (and OS):__

Several recent builds, most recent build downloaded and compiled 8th sept 2017

Linux Mint 64 bit

**Comment by impaktor** [comment] 2017-09-19 17:59
Not obvious to me what could cause it, but to me it looks like if the mission ship docks at any time, to any station, you get a "failed" mission, so I'm not so sure it has anything to do with entering a system, or could I be wrong?

But there are no such instructions in the mission texts right?

**Comment by antonspace** [comment] 2017-09-19 22:17
The mission screen displays the mission status as failed as soon as I have jumped into the system where the assassination is to take place. Have tried many times, with different ships, different missions.

If I ignore the "failed" status, hang around outside the base until the time the ship departs, then destroy the ship, a lua pop-up window appears with an error message, when the error message is closed, the game crashes.

If I dock at any spaceport after the failed status appears, I get a nasty message presumably from the guy issuing the contract, and the mission disappears from the mission screen.

If it will help, I can create a savegame with a mission, just before the hyperspace jump.

**Comment by impaktor** [comment] 2017-09-20 06:22
I don't have that much time to test things, but I've made this small modification that prints debug messages to both comms and terminal before setting `FAILED` state, so please see if you can find which string gets printed first (please replace file, and restart pioneer, load game that has not yet failed, or take on a new assassination mission).

https://raw.githubusercontent.com/impaktor/pioneer/assassination_bug/data/modules/Assassination/Assassination.lua

Also, I haven't tested the above script, as I'm at work, but I hope I didn't do any typos.

**Comment by antonspace** [comment] 2017-09-20 07:42
I followed your instructions and started a new assassination mission, immediately upon arrival in the system where the assassination was to be carried out, the message to comms and terminal was:-

DEBUG-ASS: Docked and failed

Hope this helps.

**Comment by impaktor** [comment] 2017-09-20 07:58
@antonspace thanks! It does help, it confirms my initial suspicion, that it's not `onEnterSystem()` but `onShipDocked()` that is the culprit. I'll have a look later at this, before the weekend.

**Comment by impaktor** [comment] 2017-09-21 06:50
_I thought I wrote this answer yesterday, but looks like I never posted it, so here goes:_

As far as I can see, the code dates back to #290, and @richardpl. I don't understand (yet) why the script checks (and fails the player) if the target ship is docking. Since it's more than 6 years since that code was introduced, I must assume that it has worked in the past (I'm fairly certain that it worked when I played it last time... some years ago), and that possibly something is wrongfully making the target ship dock. A bit difficult when I don't know the intended behaviour.

I hope to look into it in the weekend (issue tracker must not pass 300 again!).

**Comment by richardpl** [comment] 2017-09-21 13:16
Target ship should spawn docked. And than it should not be destroyed by other means except by player.
If target ship redocks somehow (or leave system and player do not follow it), even in same system, mission fails. So depends what have changed in AI behaviour.

**Comment by antonspace** [comment] 2017-09-21 16:11
Interesting, I have observed docked ships, including these due to be assassinated, bouncing up and down on landing platform.

**Comment by impaktor** [comment] 2017-09-22 17:40
@antonspace could you please do one more test, this has more debug print outs that I hope will print between entering the system and getting `FAILED`, [here](https://raw.githubusercontent.com/impaktor/pioneer/assassination_bug/data/modules/Assassination/Assassination.lua)

To me it looks like the mission ship undocks when time is right, then tries to find a planet to enter orbit around, but if no planet is found, it will dock again.

**Comment by antonspace** [comment] 2017-09-22 19:18
Many termination missions seem to generate with way too little time, 

![screenshot-20170921-184541](https://user-images.githubusercontent.com/32020353/30760553-9358ef32-9fd2-11e7-8118-b2483880407a.png)
 
Luckily the first mission I selected had plenty of time, arrived in the system with almost 2 months to spare, here are the two debug messages.

**DEBUG-ASS: Mission ship spawned, docked**
DEBUG: Jumps since warranty: 25
Warranty expires: 05:55:24 17 Jul 3212
NC-1021 enters frame Aygrean A
ZP-1459 enters frame Aygrean A
**DEBUG-ASS: Docked and failed**

**Comment by impaktor** [comment] 2017-09-23 04:46
Thanks! That's useful information. So my theory now is that there has been a change to pioneer that causes `OnShipDocked` event to be triggered also when spawning new ships (`Space.SpawnShipDocked(mission.shipid, station)`) that are already docked, and that this wasn't the case before. 

I'm not sure when "before" was. 1 month ago? 1 year? More? If any devs have any ideas if we've done such a change, please enlighten us.

I guess a fix for the symptom is easy, but I'd like to understand the cause, as this could have deeper implications.

**Comment by impaktor** [comment] 2017-09-23 05:48
I've pushed a fix to my branch, if you want to test it (and actually finish a assassination mission!) you can try it out, [same url](https://raw.githubusercontent.com/impaktor/pioneer/assassination_bug/data/modules/Assassination/Assassination.lua) as above.

However, I'm not liking fixing the symptom rather than the cause, but this is better than having a 100% broken mission module.

**Comment by antonspace** [comment] 2017-09-24 09:19
Tried out a mission with your latest assassination.lua [https://raw.githubusercontent.com/impaktor/pioneer/assassination_bug/data/modules/Assassination/Assassination.lua](url) Same result, mission fails upon entering system.

**DEBUG-ASS: Mission ship spawned, docked**
DEBUG: Jumps since warranty: 31
Warranty expires: 05:55:24 17 Jul 3212
updateTSTable:total:6,removed:6
NEWS created: #news = 1
**DEBUG-ASS: Docked and failed**
CO-2372 AICompleted: Error: GRAV_TOO_HIGH Status: inbound
KK-6700 AICompleted: Error: GRAV_TOO_HIGH Status: inbound
LT-0100 AICompleted: Error: GRAV_TOO_HIGH Status: inbound
Screenshot screenshots/screenshot-20170924-101229.png saved

![screenshot-20170924-101229](https://user-images.githubusercontent.com/32020353/30781136-cd286f7c-a111-11e7-8b49-24cb2a83c6b1.png)

**Comment by impaktor** [comment] 2017-09-25 15:28
Doh! Yeah, I fixed it now (same link), and tested jumping in to system, and I didn't get failed.

**Comment by antonspace** [comment] 2017-09-25 16:07
No problem, always happy to test, and can confirm that jumping into the mission system does not cause the mission to fail.

**Closed** 2017-09-30 15:11 UTC
