### ISSUE TITLE
UI overlap text problems

### ISSUE THREAD

**Issue by Fixer-007** [pioneerspacesim/pioneer#4115] opened 2017-08-27 17:15 UTC
I'm new player, and quite excited to hear there is open source "continuation" of Elite II (20170827 on Windows 7). This project needs more publicity.

I'm playing it in 1152*864 windowed mode (I have 5:4 1280x1024 monitor), and noticed few minor UI-text related issues in this resolution.

Few examples:
**FIXED**
![default](https://user-images.githubusercontent.com/16494741/29752288-eab95e02-8b63-11e7-9c6f-6ce6a02a33c5.png)
**FIXED IN SOME CASES, BUT NOT ENTIRELY**
![default](https://user-images.githubusercontent.com/16494741/29752296-0d1ba680-8b64-11e7-9b29-457b201a188e.png)
**FIXED**
![default](https://user-images.githubusercontent.com/16494741/29752307-3aa3e540-8b64-11e7-87f3-1e03ed478177.png)

On a side note (UI again), this "Continue Game" button is most puzzling to me, it is always greyed out (inactive) even if I have save games:
![default](https://user-images.githubusercontent.com/16494741/29752332-b9e6478a-8b64-11e7-9f4f-18e265625b6f.png)

**Comment by Fixer-007** [comment] 2017-08-27 17:27
Aw, missed release by few hours, I will check out newer version, I'm glad you know about this UI problem.

**Comment by nozmajner** [comment] 2017-08-27 17:33
The continue game option should work if you enable auto-save in the settings. Then it will save on every landing. (Which might hang the game for a couple of seconds)

**Comment by Fixer-007** [comment] 2017-08-27 18:10
Ok, I've checked new release, and overlap issues reported above are fixed for me, however, there is new minor UI problem:
![default](https://user-images.githubusercontent.com/16494741/29752731-1f28f53c-8b6c-11e7-945d-66ad92efc4be.png)

**Comment by impaktor** [comment] 2017-08-27 18:27
I'm not surprised, for reasons stated above.

**Comment by nozmajner** [comment] 2017-08-27 18:28
That's odd. There shouldn't be anything there hiding the UI

**Comment by Fixer-007** [comment] 2017-08-27 22:21
Update, this part still problematic too:
![default](https://user-images.githubusercontent.com/16494741/29754505-20a0e654-8b8f-11e7-8067-8f5255e5a02e.png)
Also, for some reasons there are no more orbits displayed.

**Comment by Fixer-007** [comment] 2017-08-30 21:18
Some more:
![default](https://user-images.githubusercontent.com/16494741/29895496-f76e78d2-8de1-11e7-833c-87263ed34434.png)

**Comment by laarmen** [comment] 2017-08-31 09:02
Hi, thanks for the reports!

However, could you be a bit more specific as to what the problem is when
posting screenshots? I'm guessing in the last one it's the third icon to
the right of the radar?

**Comment by nozmajner** [comment] 2017-08-31 09:38
So some of the the icon boxes are cropped partially on 4:3 aspect ratios.

**Comment by Fixer-007** [comment] 2017-08-31 11:36
>However, could you be a bit more specific as to what the problem is when posting screenshots?

Problematic areas are marked by red lines (usual problem is cropped icon or text that does not fit properly)

**Comment by nozmajner** [comment] 2017-09-01 08:30
Closing, noted on #4078

**Closed by nozmajner** 2017-09-01 08:30 UTC
Labels:  CONFIRMED, Cosmetic or UI, UI rewrite
