### ISSUE TITLE
Burning into a crisp near the sun could be improved.

### ISSUE THREAD

**Issue by alugarius** [pioneerspacesim/pioneer#3963] opened 2017-04-05 07:45 UTC
using the Hull temperature instead of crashing into a sun?

**Comment by alugarius** [comment] 2017-07-27 09:24
Bump?

**Comment by impaktor** [comment] 2017-07-27 09:43
As you can see, we have 296 open issues to address, and very very very very little free time. If this is something you feel passionate about, then feel free to submitt code to this effect.

**Comment by impaktor** [comment] 2017-12-30 13:52
duplicate of #1336, closing

**Closed by impaktor** 2017-12-30 13:52 UTC
Labels: Feature request
