### ISSUE TITLE
Crash while loading a save with an accepted mission

### ISSUE THREAD

**Issue by kinderhead** [pioneerspacesim/pioneer#5402] opened 2022-09-07 21:46 UTC
### Observed behaviour
Loading a save after accepting a contract and opening the sector map crashes the game.

### Expected behaviour
The game does not crash when opening the sector map.

### Steps to reproduce
Accept a mission (eg one of the corporate transportation ones)

Save and exit

Reload the save

Open the sector map

__My pioneer version (and OS):__ 20220203 Windows 11

**Comment by Web-eWorks** [comment] 2022-09-09 21:17
Without providing the save file in question we will be completely unable to act on this crash report. If you are able to provide the save that causes you to consistently crash, we can hopefully reproduce the issue and try to fix it. :smile:

**Comment by kinderhead** [comment] 2022-09-10 03:43
[_exit.zip](https://github.com/pioneerspacesim/pioneer/files/9539511/_exit.zip)
Had to upload it as a zip because github wouldn't accept it otherwise

**Comment by k0m18ar** [comment] 2022-09-13 17:32
У меня точно такая же проблема. Игра вылетает при попытке открыть карту сектора.

**Comment by impaktor** [comment] 2022-09-15 06:34
I think we need a back trace to get further on this, (I'm on the wrong machine now), so anyone with february release should be able to get that, using the save above, I hope, e.g. using gdb (if on GNU/Linux). See our wiki FAQ for how to do it, if not familiar.

**Comment by Compiemunky** [comment] 2022-09-16 16:53
Hi, looking like a very similar problem to what I have, however I do not have a mission accepted, I load the save, can open pretty much any menu, but if I open Sector map, game crash to desktop.

Although it happened once before, I reloaded a previous save, and it let me open the Map, so I just continued, this time, no matter what save I load, it crashes

Tried on 2 PCs, same result, I have attached documents pioneer folder for all output/opengl/saves
[Pioneer.zip](https://github.com/pioneerspacesim/pioneer/files/9585849/Pioneer.zip)


Hope I got the traceback instructions right, included the popup the gets thrown after the crash:

'Exception thrown at 0x00007FF62CDD03F3 in pioneer.exe: 0xC0000005: Access violation reading location 0x0000000000000014.'

`pioneer.exe!00007ff62cdd03f3()
pioneer.exe!00007ff62cdcbade()
pioneer.exe!00007ff62cdcafc8()
pioneer.exe!00007ff62cc9a420()
pioneer.exe!00007ff62cf51915()
pioneer.exe!00007ff62cc806e6()
pioneer.exe!00007ff62cf73b2c()
pioneer.exe!00007ff62cf6f596()
kernel32.dll!00007ffa0fb97034()
ntdll.dll!00007ffa11782651()
`

**Comment by Gliese852** [comment] 2022-09-17 18:37
Perhaps it was already in #5349 ? In the last message there is a link to the corrected artifact, as well as workaround.

**Comment by Compiemunky** [comment] 2022-09-17 19:39
Hm ok, that one didn't come up with that issue when I was searching, may have forgotten to take off issue:open though.

Well anyway, the workaround in #5349 works for me, just have to run it every time I open the game, which I guess is expected with a console code, I'm not versed enough to know/see if there is a way to run on start automatically (Hobbyist coder that only learns what I need to get by :P)

Hope it works for OP too.

**Comment by Gliese852** [comment] 2022-09-17 19:46
@Compiemunky You probably noticed that there, in fact, the sector map has 2 display modes - "far" and "near". It seems that the crash should not occur if the sector map is in "near" mode when saving.

**Comment by Compiemunky** [comment] 2022-09-17 19:52
As I'm playing right now, I just tested, yep, far mode crashes, near mode doesn't. Just have to remember to save in the right mode... but at least there's the script to fix if I fail XD

**Comment by kinderhead** [comment] 2022-09-21 19:42
The fix in #5349 works for me, but now I can't click on any stars in the near mode.

**Comment by Web-eWorks** [comment] 2023-01-14 08:30
Closing as completed due to the fix for the linked issue being merged quite some time ago.

**Closed by Web-eWorks** 2023-01-14 08:30 UTC
