### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by gkpioneer** [pioneerspacesim/pioneer#3307] opened 2015-01-07 14:14 UTC
Over the past few months some builds have failed with the error pictured below. December and January have done so as well. The build pioneer-20141128-win32 runs OK but is jerky.
Build pioneer-20140715-win32 runs smoothly and OK.
Attached is the error message I have been getting. Sometimes part way into a game, sometimes on startup.
Running on Windows Vista 32 bit 4MB RAM, AMD Athlon 64 5000+ at 2.6GH, ATI Radeon HD 4600.
![pioneer3112](https://cloud.githubusercontent.com/assets/10435693/5646687/d9fd0c7e-9676-11e4-97d3-a536bebe068e.png)

**Comment by fluffyfreak** [comment] 2015-01-09 08:27
There's been several new builds since then with numerous fixes and optimisations, would you mind trying one of the newer versions please @gkpioneer

**Comment by fluffyfreak** [comment] 2015-01-24 11:50
Closing this as I believe the issue is already fixed in newer version and there has been no further response.

**Closed by fluffyfreak** 2015-01-24 11:50 UTC
Labels: Crash or hang
