### ISSUE TITLE
comms menu bug

### ISSUE THREAD

**Issue by bhatna** [pioneerspacesim/pioneer#5165] opened 2021-04-20 12:03 UTC
### Observed behaviour
the 'commodity market', 'ship market', bulletin board' and 'equipment market' in  'show comms' went blank
![image](https://user-images.githubusercontent.com/82880517/115391654-53396400-a1fd-11eb-8e56-94d4c8d279fb.png)
![image](https://user-images.githubusercontent.com/82880517/115391850-8c71d400-a1fd-11eb-8a59-37068c21cb44.png)
![image](https://user-images.githubusercontent.com/82880517/115390974-88918200-a1fc-11eb-9ae1-0abd3afc3a55.png)
![image](https://user-images.githubusercontent.com/82880517/115392179-e377a900-a1fd-11eb-9716-1e44dc306f85.png)

### Expected behaviour
it was expected to show what usually shows there

### Steps to reproduce
i think i did something in 'debug info' in 'video' in the menu

__My pioneer version (and OS):__
20210203 (142693b)

**Comment by Web-eWorks** [comment] 2021-05-08 21:14
Closing as duplicate of #5149.

**Closed by Web-eWorks** 2021-05-08 21:14 UTC
