### ISSUE TITLE
bug in commodity tab and market tab and also empty ship tab

### ISSUE THREAD

**Issue by iurirolho** [pioneerspacesim/pioneer#5241] opened 2021-08-15 22:58 UTC
### Observed behaviour
Commodity tab and ship tab and equipment market all not working two give error(market and commodity tab) while ship tab is empty

### Expected behaviour
at least the two with error should be working

### Steps to reproduce
not exactly sure if these are the right steps but get a mission fail it due to no arriving in time to deliver goods, access station tabs get error

__My pioneer version (and OS):__
os windows 10 64bit 8gb ram and i5 4460 and also a gtx 1050, version 20210723(0b82c65)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6989008/output.txt)
[savefiles.zip](https://github.com/pioneerspacesim/pioneer/files/6989009/savefiles.zip)

hopefully this can help you find out why this happened, am not sure if the steps above are right as i have no idea if what i did was what made it but if needed i can try and describe it better, tough my memory is short so might not recall all details

**Comment by iurirolho** [comment] 2021-08-15 22:59
atm i cant buy any new ships until i figure if this bug is recoverable or if i have to restart, if that is the case i will cheat my way to where i was in terms of progress

**Comment by iurirolho** [comment] 2021-08-15 23:02
https://github.com/pioneerspacesim/pioneer/issues/5233 this might be a duplicate of this but am not sure, i think the same the other had its my case as well

**Comment by impaktor** [comment] 2021-08-16 08:44
As it wasn't clear what the bug report is reporting, beyond "something is wrong", I assume you got a crash of the program. Relevant lines from output:
```
[22:50:28] Warning: [string "[T] @libs/SpaceStation.lua"]:144: attempt to index field '?' (a nil value)
stack traceback:
	[string "[T] @libs/SpaceStation.lua"]:144: in function <[string "[T] @libs/SpaceStation.lua"]:142>
	(...tail calls...)
	[string "[T] @pigui/libs/commodity-market.lua"]:78: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:609: in function 'withStyleVars'
	[string "[T] @pigui/libs/commodity-market.lua"]:70: in function 'renderItem'
	[string "[T] @pigui/libs/table.lua"]:125: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:283: in function 'child'
	[string "[T] @pigui/libs/table.lua"]:84: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:609: in function 'withStyleVars'
	[string "[T] @pigui/libs/table.lua"]:83: in function 'render'
	...
	[string "[T] @pigui/libs/wrappers.lua"]:138: in function 'window'
	[string "[T] @pigui/views/tab-view.lua"]:111: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:641: in function 'withStyleColorsAndVars'
	[string "[T] @pigui/views/tab-view.lua"]:107: in function 'renderTabView'
	[string "[T] @pigui/views/station-view.lua"]:67: in function 'draw'
	[string "[T] @pigui/views/game.lua"]:57: in function 'callModules'
	[string "[T] @pigui/views/game.lua"]:240: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:138: in function 'window'
	[string "[T] @pigui/views/game.lua"]:230: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:576: in function 'withStyleColors'
	[string "[T] @pigui/views/game.lua"]:229: in function <[string "[T] @pigui/views/game.lua"]:216>
Cleaned up 2 windows, 5 styles, and 1 fonts.
[22:50:37] Warning: [string "[T] @libs/SpaceStation.lua"]:144: attempt to index field '?' (a nil value)
stack traceback:
	[string "[T] @libs/SpaceStation.lua"]:144: in function <[string "[T] @libs/SpaceStation.lua"]:142>
	(...tail calls...)
	[string "[T] @pigui/modules/station-view/05-equipmentM..."]:64: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:312: in function 'withTooltip'
	[string "[T] @pigui/modules/station-view/05-equipmentM..."]:55: in function 'renderItem'
	[string "[T] @pigui/libs/table.lua"]:125: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:283: in function 'child'
	[string "[T] @pigui/libs/table.lua"]:84: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:609: in function 'withStyleVars'
	[string "[T] @pigui/libs/table.lua"]:83: in function 'render'
	...
	[string "[T] @pigui/libs/wrappers.lua"]:138: in function 'window'
	[string "[T] @pigui/views/tab-view.lua"]:111: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:641: in function 'withStyleColorsAndVars'
	[string "[T] @pigui/views/tab-view.lua"]:107: in function 'renderTabView'
	[string "[T] @pigui/views/station-view.lua"]:67: in function 'draw'
	[string "[T] @pigui/views/game.lua"]:57: in function 'callModules'
	[string "[T] @pigui/views/game.lua"]:240: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:138: in function 'window'
	[string "[T] @pigui/views/game.lua"]:230: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:576: in function 'withStyleColors'
	[string "[T] @pigui/views/game.lua"]:229: in function <[string "[T] @pigui/views/game.lua"]:216>
Cleaned up 2 windows, 2 styles, and 1 fonts.
```

**Comment by iurirolho** [comment] 2021-08-16 16:11
sorry if the original post was not clear i should have given more details, anyhow i still have yet to found a work around as am new to the game, but so far nothing i tried worked to fix the bug and if possible i want to keep playing on that save but idk if if it is possible

**Comment by iurirolho** [comment] 2021-08-16 20:15
i managed to get the ship tab working and also changed ships but atm i cant seem to figure if i can work around it without new save, but am willing to help you try things on the saves i got

**Comment by iurirolho** [comment] 2021-08-16 22:02
found a work around for my save but idk if applies to other cases as this bug is rare, this worked for me load fresh easy save reload old save and it worked

**Comment by Web-eWorks** [comment] 2021-08-17 03:55
Yep, that seems to be the workaround for this bug. Definitely a duplicate of #5233, going to close this but keep it linked to the original for debugging purposes. It will be fixed eventually, it's just a matter of one of the developers changing tracks from where they're developing new features to look into this bug.

**Closed by Web-eWorks** 2021-08-17 03:55 UTC
Labels: Unexpected behaviour, Lua code
