### ISSUE TITLE
More Text = Less Frames

### ISSUE THREAD

**Issue by SpencerBelleau** [pioneerspacesim/pioneer#3417] opened 2015-07-07 08:28 UTC
So for the record I'm running Win7 64 bit, 8GB of RAM, an ATI HD7870 and an AMD Phenom II X4 Black Edition @ 3.4Ghz.

Whenever text is rendered on screen I lose frames like crazy, to the point where opening autopilot can dip my framerate from a perfect 60 to sub-15. I'm not sure what's causing this but I have the latest proprietary drivers from ATI installed as well. Other than this the game runs flawlessly.

On latest version: 20150701

**Comment by fluffyfreak** [comment] 2015-07-08 13:09
It's the text rendering. The autopilot-comms screen and some others use the old style text rendering which is very inefficient whereas the newer screens like stations-comms use the newer UI.

**Comment by impaktor** [comment] 2015-07-08 13:35
I encouraged SpencerBelleau to open this issue since I had no such problem when I played on my very old low-tech openGL 2.0 computer, but now I realize text rendering has changed since the OpenGL bump to 3.1, right? Thus its not so strange that @SpencerBelleau's speed machine is under strain with 20150701, where my steam engine of a computer danced gracefully on 20141118 version.

**Comment by fluffyfreak** [comment] 2015-07-08 13:46
Yes exactly, it's probably come in with the 3.1 change.

I did some optimisations to fix it up at the time if you recall but each vendors drivers handle these things differently. All my machines are nVidia except the Linux box and that uses open source drivers. AMD/Ati drivers are... very variable in their quality so it's hard to know what's causing slowdown when I don't see it myself :/

**Comment by fluffyfreak** [comment] 2015-07-08 17:29
Having looked into it a little I think that it's because it's thrashing the buffers per frame and creating/destroying a great many of them per-frame.

**Comment by fluffyfreak** [comment] 2015-07-15 20:10
Reopening, seems I optimised a bunch of stuff but it didn't fix the cause of the issue. The joy of not being able to reproduce problems on your own hardware eh.

**Comment by fluffyfreak** [comment] 2015-07-15 20:23
Starting to wonder if I can "borrow" an AMD GPU from work to test this.

**Comment by SpencerBelleau** [comment] 2015-07-15 23:03
Yeah it's probably some dumb driver nonsense. AMD's pretty bad for that. If I had my old one I'd mail it to you or something.

**Comment by fluffyfreak** [comment] 2015-07-21 11:05
I have merged in a bunch more optimisations but I'm not closing this issue until we know that I've fixed it.

All of this is because of the old GUI system :( I'd love to just fixup all of the screens and menu and ditch it entirely. Any volunteers?

**Comment by snwyvern** [comment] 2015-08-16 20:57
For what it's worth: I was having this issue as well, FX-8150 pushing a AMD R270. I run crysis3 in 3x 1080p; I added "DisableShaders=1" to my config file, which fixed the 1FPS on the mission menu while docked.

**Comment by snwyvern** [comment] 2015-08-18 09:10
Correction: the low fps in the mission menus while docked came back after four or so runs.

**Comment by impaktor** [comment] 2016-01-26 10:20
A new build just went up on the homepage. It has optimizations for text, (and bug fixes that those optimzations introduced), so all should be fine now. Would be great if those who experienced the slow frame rate could test it and report if it has improved or not.

**Comment by fluffyfreak** [comment] 2016-01-26 10:25
I didn't actually mean to close this one with that fix since it was still unknown if it fixes the issue.

I'll reopen it for tracking until we get confirmation.

**Comment by roman-yagodin** [comment] 2016-06-18 20:12
I'm experiencing the described issue on Linux (Linux mylaptop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux) with AMD Radeon HD 7660G (A10-4600M APU) and proprietary drivers (fglrx-driver 1:15.9-4).

The issue shows up after some play time, slowdown is more noticeable then on Bulletin Board screen.

**Closed** 2016-12-09 15:33 UTC
