### ISSUE TITLE
Consistent ESC key behavior

### ISSUE THREAD

**Issue by monolifed** [pioneerspacesim/pioneer#2727] opened 2014-02-08 13:16 UTC
When I press ESC key It should close any menus and go back to ship view
But instead of that it opens options menu. It is a little inconvenient in my opinion

**Comment by impaktor** [comment] 2015-12-27 13:49
@salborrelli is currently looking into this, discussion thread: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=385

**Comment by salborrelli** [comment] 2016-01-07 11:26
@impaktor @robn @nozmajner @monolifed @lwho I've just published a document with a proposal for updating the effects of pressing the ESC key on a per-view basis. You can find the details in the Dev Forum: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=385#p4531

**Comment by Web-eWorks** [comment] 2020-10-19 21:01
Closing as duplicate of #4851 as that issue better tracks the current situation.

**Closed by Web-eWorks** 2020-10-19 21:01 UTC
Labels: Input, UI rewrite
