### ISSUE TITLE
Undocking while paused should unpause the game.

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4989] opened 2020-10-29 02:31 UTC
### Observed behaviour
After requesting launch from orbital station, nothing happens. The game menus and flight UI are still responsive. ~~If I press F1 at this time the game crashes with a segmentation fault.~~ (Sturnclaw edit: tracked in #4968)

Additional observation (not sure if related): all options in the bulletin board are greyed out.

Edit: It appears that any previous save from this particular pilot/ship suffers from the same problem. Does not matter if the station is ground based or orbit. If I start a new game I can launch from stations just fine. I don't have another save from a different pilot/ship to test how universal that is.

I had saved and loaded before just fine. What I changed from my last session to now is to unplug my external monitor and try to resume playing on my laptop with a different resolution than before. It does not matter if I play fullscreen or windowed, the problem persists. Resolution of the laptop is 3200x1800 (much higher than the external monitor).

### Expected behaviour
Requesting a launch should result in the initiation of the launch sequence. 

### Steps to reproduce
See attached save file. 
1. Request launch. Nothing will happen.
2. Press F1. Game will crash.

__My pioneer version (and OS):__
pioneer version: 2020-10-23 (52360f815)
OS: openSUSE Leap 15.2

[07.zip](https://github.com/pioneerspacesim/pioneer/files/5455777/07.zip)

**Comment by The-EG** [comment] 2020-10-29 10:59
Undocking with your saved game works on master, but you do need to unpause the game after loading it. You can still click undock while it's paused, and the button goes away but nothing will happen until the game isn't paused:
https://i.imgur.com/DTtIi8c.mp4

I can confirm the crash with changing camera views (F1) in your saved game, and it happens regardless of trying to undock or not. In fact, I can reproduce this crash with any saved game, including a newly created one:
 - Start a new game
 - Save it
 - End Game
 - Load saved game
 - While still paused, press F1 (change camera view)

Something is happening when a loaded game is unpaused the first time. On the debug build, which runs fairly slowly, it actually hangs up for a second or so when I press 1x time acceleration. After that initial pause, switching between time accelerations and pause again doesn't produce another hang/pause. Also, loading a game, unpausing it, then pausing it again will not produce the crash.

The error causing the crash: `this->m_statusObjectTree was nullptr`  in [src/collider/CollisionSpace.cpp @ 315](https://github.com/pioneerspacesim/pioneer/blob/master/src/collider/CollisionSpace.cpp#L315)

**Comment by Gliese852** [comment] 2020-10-29 11:06
#4968 ?

**Comment by The-EG** [comment] 2020-10-29 11:09
@Gliese852 indeed, thanks! 

This is a duplicate of #4968

**Comment by Web-eWorks** [comment] 2020-10-30 03:15
Re-opening this as we need an issue tracking the undock-while-paused problem.

**Closed** 2020-11-07 16:45 UTC
Labels:  CONFIRMED, Unexpected behaviour
