### ISSUE TITLE
Pioneer graphics wont't launch on Ubuntu 20.04 / OPenGL 4.6.0

### ISSUE THREAD

**Issue by Mutos** [pioneerspacesim/pioneer#5416] opened 2022-11-06 15:00 UTC
### Observed behaviour
First time I tried to run Pioneer :
- I installed on my Ubuntu 20.04 / OGL 4.6.0 ;
- I first compiled with current GitHub master, then tried pioneer-20220203-linux.tar.gz download from the Pioneer site ;
- In both installs, when I fire ./pioneer, I got multiple errors, presumably on each frame render :
```
Info: OpenGL error(s) during frame:
In function ExecuteRenderPassCmd
On line 295
GL_INVALID_OPERATION
```
- The Pioneer window shows up with music playing ;
- When I close the window, it terminates Pioneer without crashing it.

### Expected behaviour

Pioneer should launch...

### Steps to reproduce

- I first compiled with current GitHub master, then tried pioneer-20220203-linux.tar.gz download from the Pioneer site ;

__My pioneer version (and OS):__

Ubuntu 20.04 / OGL 4.6.0
Pioneer version : happens on both **commit cec94a2ffe5720d441671538731726633b4fe74b** and **pioneer-20220203-linux**

**Comment by Mutos** [comment] 2022-11-06 21:12
For information : setting **AntiAliasingMode=0** in **~/.pioneer/config.ini** works. Original value was **2** and a value of **1** doesn't work.

**Comment by impaktor** [comment] 2022-11-06 21:22
>  then tried pioneer-20220203-linux.tar.gz

I recommend staying with current master branch, as that's really the only version of pioneer we care about.

> setting AntiAliasingMode=0 in ~/.pioneer/config.ini works. 

So game works now, with that option?

**Comment by Web-eWorks** [comment] 2022-11-07 00:17
This one is *also* a duplicate of #5297, thanks for reporting @Mutos and I'm glad that workaround fixed it!

**Closed by Web-eWorks** 2022-11-07 00:17 UTC

**Comment by Mutos** [comment] 2022-11-07 12:13
@impaktor : yes it works, but it's not possible to use anti-aliasing. Personally, I don't care, but it breaks a feature.
@Web-eWorks : sorry, didn't know about duplicates, I searched but found nothing.

**Comment by impaktor** [comment] 2022-11-07 13:33
@Mutos thanks for reporting, anyway.

**Comment by Web-eWorks** [comment] 2022-11-07 19:55
No problem @Mutos, was mostly mentioning it for our internal bookkeeping so we can reference this issue from that one - the underlying issue is a persistent one that seems to be driver related. We'll keep looking into a solution for it!
