### ISSUE TITLE
Can't replace Target Scanner with second hand Advanced target scanner in level 6 station

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5191] opened 2021-05-17 04:23 UTC
### Observed behaviour
I am equipped with a Target scanner.
I found second hand Advanced target scanner in a station, but it turns out that I can't replace the equipment because the station technology level is too low (level 6 tech certificate) to stock my second hand Target Scanner.

### Expected behaviour
Option A: It would not be too unrealistic to force second hand sales to be limited to the station tech level, if the installation of equipment depends on the tech level of the station.
Option B: Guys are free to sell second hand anywhere, but I must find a way to get rid of my replaced piece of equipment (trash it? Keep in cargo and sell in the next station?)
Option x: ...

### Steps to reproduce

![advanced target scanner second hand in low level station](https://user-images.githubusercontent.com/84130826/118432099-5f381900-b70a-11eb-93cd-50da311da60a.png)
![Screenshot from 2021-05-17 12-23-50](https://user-images.githubusercontent.com/84130826/118432292-c950be00-b70a-11eb-8986-c698f36cac8a.png)
![issue target scanner too high to sell](https://user-images.githubusercontent.com/84130826/118432103-60694600-b70a-11eb-947d-fc77ef2dad12.png)

__My pioneer version (and OS):__

**Comment by impaktor** [comment] 2021-05-17 11:23
duplicate of #4276

**Closed by impaktor** 2021-05-17 11:23 UTC
Labels: Unexpected behaviour
