### ISSUE TITLE
game crash and spaceship go into graphics

### ISSUE THREAD

**Issue by dparseni** [pioneerspacesim/pioneer#5546] opened 2023-02-15 15:33 UTC
![Screenshot_2022-12-15_015612](https://user-images.githubusercontent.com/72562338/219073658-b4f94130-7147-43cc-a315-60c8b5f8dbdd.png)

spaceship fell into graphics ,also theres a lot problems with spaceship movement .

__My pioneer version (and OS):__

**Comment by nozmajner** [comment] 2023-02-15 19:10
Could you provide some more details?
How did you end up under ground for example?
What do you mean by lots of problems with ship movement?

**Comment by dparseni** [comment] 2023-02-15 20:58
just moving straight and come slow in contact with something like small hill or the ground it  goes through the graphics and keep moving in graphics

**Comment by impaktor** [comment] 2023-02-16 08:04
Yep, glitching through hills is old problem (that I don't think ever got solved? But I cant find the issue I'm thinking of).

**Comment by dparseni** [comment] 2023-02-16 17:09
how is this possible?? and glitching whe you go to a hill is graphic machines problem??

**Comment by impaktor** [comment] 2023-02-16 21:38
I believe it's due to how physics engine and collision detection is done.

**Comment by Web-eWorks** [comment] 2023-02-17 04:18
Duplicate of #2337 and others, no viable fix available other than a rewrite of how terrain collision (and the collision system in general) is handled. Closing as not planned at this time, we are well aware of the issue and will fix it eventually:tm:.

**Closed by Web-eWorks** 2023-02-17 04:18 UTC
