### ISSUE TITLE
Bullettin Board: Goods requests in bulletin board appear with encoded variables

### ISSUE THREAD

**Issue by Another-MrZ** [pioneerspacesim/pioneer#5100] opened 2020-12-28 17:48 UTC
### Observed behaviour
In the Bulletin Board requests for goods appear with encoded variables for good name and price
Not sure this happens for all requests of goods.
This instance happened after a fresh start and one mission to High Security Prison Tranquillity completed.
Tapping on the request showed that the required good was Mining machinery and the price was $742.56

### Expected behaviour
The ad should show actual goods name and price, and not the encoded variables.

__My pioneer version (and OS):__  20201222  (Windows 7)

![Encoding](https://user-images.githubusercontent.com/34732798/103233269-90b77000-4934-11eb-8bbb-0dd6423da180.png)
![Encoding2](https://user-images.githubusercontent.com/34732798/103233270-944af700-4934-11eb-90a1-be5bbfc2ffb9.png)

**Comment by impaktor** [comment] 2020-12-28 17:52
This was fixed in #5092, but thanks for reporting!

(Might be a good idea to keep this open until next pre-release?)

**Comment by The-EG** [comment] 2020-12-28 18:06
duplicate of #5090

**Comment by Another-MrZ** [comment] 2020-12-28 19:31
Sorry, I did not check the Closed bugs.

**Closed** 2020-12-29 21:02 UTC
