### ISSUE TITLE
Game throws up " lua serializer '(null)' tried to serialize an invalid 'ship' " and crashes when attempting to save

### ISSUE THREAD

**Issue by wafehling** [pioneerspacesim/pioneer#3648] opened 2016-03-11 08:12 UTC
This error is reproducible. Here are the following steps:
1. Download this save file and add it to the usual save file location for pioneer (My documents/pioneer/savefiles)
[_autosave2.zip](https://github.com/pioneerspacesim/pioneer/files/168662/_autosave2.zip)
2. Load this up in pioneer. Version where error occurs is 20160307 (33328ed)
3. jump to Barnard's star, which is already selected. All you have to do in-game is unpause and hit F7.
4. Attempt to manually save. Game will crash, giving that exact error. Error will also occur upon docking with "System Administration Resting" orbital starport with autosave enabled. Have not tested with other locations, but assumed it will happen anywhere in system.

**Comment by wafehling** [comment] 2016-03-11 08:30
Targeting a different ship from the one currently set as combat target in original save file does not prevent the error.

**Comment by wafehling** [comment] 2016-03-11 08:32
This star system is the first system where I performed a search and rescue mission. Jumping to Sirius and attempting to save produces the same crash.

I highly suspect the crash is caused by the game attempting to save the ship spawned for the search and rescue mission, and failing somehow.

**Comment by wafehling** [comment] 2016-03-11 08:57
I flew out and destroyed the ship, saving immediately before. The save right before his death was fine, the save right after his death failed. The ship appeared to not have left the system properly from the discardShip function found in searchrescue.lua. 

It seems the error narrows down to a ship not being marked as destroyed/gone when attempting to save. I'll see if I can figure out how to get a debugger working and run it through there, to narrow things down further.

**Comment by impaktor** [comment] 2016-03-11 09:53
Ping @clausimu

**Comment by laarmen** [comment] 2016-03-11 10:04
My guess is that it has something to do with the recent changes to the
setCombatTarget Lua method.

**Comment by wafehling** [comment] 2016-03-11 10:40
I've fully reproduced the bug. Simply accept a fuel resupply emergency mission, successfully complete it, and hyperdrive away to another system shortly after completing it. When you attempt to save in the new system, it. will. crash.

**Comment by walterar** [comment] 2016-03-11 10:53
@laarmen That's a joke?

The problem is that are trying to serialize a "dead" ship.

**Comment by clausimu** [comment] 2016-03-11 11:36
@wafehling - thank you. I will look into it. 

There must be a sensor somewhere in the SAR script that sets it up to fail exactly when my work-life is at peak capacity... :)

**Comment by fluffyfreak** [comment] 2016-03-11 13:24
@clausimu looking at `SearchRescue.lua` you keep a list of `discarded_ships`, you probably want to throw them away in the `onLeaveSystem` and `onEnterSystem` functions since they'll be for ships in a different system (I think).

Also why use `"NIL"` everywhere when you can use `nil` which is Lua's `nullptr` value? When you assign `"NIL"` to something you're assigning the string "NIL" too it rather than marking it as a dead value.

**Comment by clausimu** [comment] 2016-03-11 14:12
@fluffyfreak - you are right. I just went over it this morning before my kids were up and I had to leave for work. There are actually two issues that I can see right now: (a) discarded_ships need to be cleared onLeaveSystem, (b) the ship discarded needs to be removed from discarded_ships once it leaves the system (don't know how I missed that).

I'll double check on the "NIL" - but I remember I put that there for a reason... can't remember which reason though... - which doesn't mean it is/was smart to begin with...

**Comment by fluffyfreak** [comment] 2016-03-11 14:13
I just threw together a PR which might have some bits of what needs doing :) good timing!

**Comment by impaktor** [comment] 2016-03-11 15:33
@wafehling can test it by simply replacing the script with the one given in #3649, if you want to.

**Comment by wafehling** [comment] 2016-03-11 23:40
Sure, let me give it a shot and see what it does.

**Comment by wafehling** [comment] 2016-03-11 23:50
Welp. That didn't quite work...
![ss 2016-03-11 at 05 50 08](https://cloud.githubusercontent.com/assets/1471082/13718680/caa89cec-e7b1-11e5-945b-62dadf2cb545.jpg)

**Comment by wafehling** [comment] 2016-03-12 00:53
I fixed the error, with the help of #lua. Published the fix in 3649

**Comment by fluffyfreak** [comment] 2016-03-31 08:56
Hi @wafehling what do you mean you published the fix in #3649? I can't see anything you've done in that converstaion thread and not had a PR on the code?

**Comment by fluffyfreak** [comment] 2016-03-31 08:58
Also I can't see anything on your pioneer fork, I think you need to do  `got push origin -all` so that your changes actually get pushed from your computer upto GitHub so we can see them :)

I'd really like to get these bugs fixed so if you have them that would be great, thanks.

**Comment by fluffyfreak** [comment] 2016-04-03 14:11
@clausimu sorry to bug you but thought you might be interested in this and @3650 if you weren't already aware of them :)

**Comment by clausimu** [comment] 2016-04-05 12:27
@fluffyfreak - I'm following along quietly :). I don't have any time right now. But I will be going to a conference in two weeks. I should have some time on the flight.

I feel really bad about the bugs in the SAR mission script - and not being able to squash them right now. I hope this does not kill the experience for everyone and turns people away from pioneer.

**Comment by impaktor** [comment] 2016-04-05 12:55
@clausimu don't worry about it too much. All new code, of significant length, has bugs.

**Comment by laarmen** [comment] 2016-04-05 14:27
Plus, if it gets too bad we can always yank it from master until we fix it.
We did that once (although we never fixed the module because it was way too
complex, nobody from the usual folks at the time could make heads of tails
of it)

**Comment by fluffyfreak** [comment] 2016-04-05 14:41
It's not that bad, only some minor bit's with issues

**Comment by Gliese852** [comment] 2016-04-08 05:27
Please, don't yank it, its my favorite mission in game

**Comment by laarmen** [comment] 2016-04-08 15:10
As I said, worst case scenario.

**Comment by Gliese852** [comment] 2016-04-12 19:24
I downloaded new file SearchRescue.lua from here, and this problem is gone, but i get another error. When i get mission to rescue crew from crashed ship, and ask "Where do i find the rarget?", program crashes and window appears:
"MinGW Runtime Assertion
Assertion failed!
Program: ...pioneer.exe
File: TextureFont.cpp, Line 86
Expression: n"
If i replace SearchRescue.lua with old version, this error doesn't come.
Can't attach savefile, (even zip), this is link to my cloud
https://cloud.mail.ru/public/83b7/A39i4Ke8s
go to bulletin board, then to "SHIP CRASH LANDED..."
my version for windows, build 20160404(646f6c0)

**Comment by laarmen** [comment] 2016-05-23 21:33
This should just have been fixed on master

**Closed by laarmen** 2016-05-23 21:33 UTC
