### ISSUE TITLE
Pioneer does not work on newer versions of Ubuntu (Ubuntu 17.04)

### ISSUE THREAD

**Issue by TSGU** [pioneerspacesim/pioneer#4075] opened 2017-08-12 09:00 UTC
When I try to run the game in the terminal I get a error message saying"./pioneer: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory"

**Comment by nozmajner** [comment] 2017-08-12 09:03
Could you please provide more details?
- How it is not working? It crashes? Doesn't even start?
- Please attach the output.txt and openGL.txt. You can find them in ~Pioneer
- What kind of hardware do you have?
Could you try building Pioneer from master? There were lots of changes since April, the issue might be already fixed.

**Comment by impaktor** [comment] 2017-08-12 09:04
There is zero chance we can do anything with this report.

**Comment by TSGU** [comment] 2017-08-12 21:00
I fixed the problem you just need install the library at https://packages.debian.org/jessie/libpng12-0 and run the game as root.

**Comment by TSGU** [comment] 2017-08-12 21:03
For whatever reason it was not listing the rest of my report sorry.

**Comment by nozmajner** [comment] 2017-08-12 21:45
Thanks! It's a duplicate of #3959, so closing.

**Closed by nozmajner** 2017-08-12 21:45 UTC
