### ISSUE TITLE
Fullscreen Issue :)

### ISSUE THREAD

**Issue by realusername12** [pioneerspacesim/pioneer#5757] opened 2024-02-10 14:42 UTC
Hello

I put the latest Pioneer version downloaded from the homepage in fullscreen mode in game settings (Win 11 23H2, AMD Ryzen 5 5625U with Radeon Graphics 2.30 GHz) and when I ran the game it looked like this *attached pictures of laptop screen*

![Pioneer Fullscreen Issue Pic 5](https://github.com/pioneerspacesim/pioneer/assets/159630751/2faa2cc3-23ab-4ccd-b81d-e8992884eb42)
![Pioneer Fullscreen Issue Pic 4](https://github.com/pioneerspacesim/pioneer/assets/159630751/455d109f-8256-4b5e-b175-df846152e945)
![Pioneer Fullscreen Issue Pic 3](https://github.com/pioneerspacesim/pioneer/assets/159630751/e98cea5f-ca0d-4710-a16c-4ae936f4c16b)
![Pioneer Fullscreen Issue Pic 2](https://github.com/pioneerspacesim/pioneer/assets/159630751/54f71b26-939b-465f-82b2-040a452df0ac)
![Pioneer Fullscreen Issue Pic 1](https://github.com/pioneerspacesim/pioneer/assets/159630751/f3907278-c63d-4d96-9bea-8765ea64762e)

**Comment by Web-eWorks** [comment] 2024-02-10 21:29
That's a fun one - your OS is setting a different resolution for the game window than it requested, so the UI gets messed up. Set the game's resolution in the settings or in `Documents/Pioneer/config.ini` (`ScrWidth` / `ScrHeight` keys) to your monitor resolution.

Duplicate of #4575.

**Closed by Web-eWorks** 2024-02-10 21:29 UTC

**Comment by realusername12** [comment] 2024-02-11 16:48
Thank You!
