### ISSUE TITLE
Game crashes when looking at certain stars, e.g. Type 'M' red stars

### ISSUE THREAD

**Issue by wingnut-2019** [pioneerspacesim/pioneer#4670] opened 2019-09-11 09:10 UTC
### Observed behaviour
Game crashes when certain types of stars become visible. As of now I observed it for Type 'M' red stars and sometimes Brown dwarfs

### Expected behaviour
Game should not crash

### Steps to reproduce
1. Select the "Start on Mars" option in the main menu
2. Go to the Sector map and select the hyperjump target to Kruger 60 A (-1, -1, 1)
3. Request launch on Mars and initiate the hyperjump to Kruger 60 A
4. Select Kruger 60 A as navigation target and orient the ship so that Kruger 60 A is visible -> once the star becomes visible the game crashes immediately

I have included a savegame just after arriving in the Kruger 60 system. The issue might not be reproducible (easily) on other machines as I could not find a similar issue loged already.

__My pioneer version (and OS): pioneer-20190203 on Windows 10__

### Attachments
[Kruger 60 A.zip](https://github.com/pioneerspacesim/pioneer/files/3599923/Kruger.60.A.zip) (Savegame)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/3599919/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/3599920/output.txt) (output.txt after provoking the game crash with above savegame)

**Comment by craigo-** [comment] 2019-09-12 03:16
I cannot reproduce the crash, either with your steps or your savegame. (I can, however, quite happily crash my ship into that sun :smile:)

My environment:

- Windows 10 Enterprise 1809 x64
- Intel UHD Graphics 620 (driver: 25.20.100.6472)
- Pioneer Release 20190203
- Pioneer Master x64 (4bc31eef4700b343256cb1dae604622680c534d8)

**Comment by Web-eWorks** [comment] 2019-09-13 23:07
I've tracked down the hypercloud bug; the `InitGraphics` method is not being called when it's loaded from a savefile, triggering a segfault here: https://github.com/pioneerspacesim/pioneer/blob/f508f0047a2ead557898aad6220afb31b490099c/src/HyperspaceCloud.cpp#L173

This doesn't appear to be the root cause of the problem, but adding `InitGraphics()` to the end of the JSON constructor should fix this specific crash.

**Comment by impaktor** [comment] 2019-09-14 15:59
@Web-eWorks will you PR that?

**Comment by Web-eWorks** [comment] 2019-09-14 16:01
@impaktor Sure, can do. I'll get that tested and PR'd in a few minutes.

**Comment by Web-eWorks** [comment] 2019-09-14 17:04
@wingnut-2019 I've created a PR to resolve the hyperspace cloud crash bug; if you could pull that and test to see if the game still crashes for you? I cannot reproduce the bug you're describing, which makes me think it's related to your specific graphics configuration.

For reference, this is what Kruger 60 A looks like for me:
![Screenshot from 2019-09-14 12-37-24](https://user-images.githubusercontent.com/4218491/64911467-21dae700-d6f0-11e9-80e5-e862fb7642bc.png)

**Comment by impaktor** [comment] 2019-09-14 17:35
Hypercloud fix now merged, thanks @Web-eWorks!

Could those who replicated the bug try to do so again, with a fresh backtrace? 
ping: @pcercuei  or @wingnut-2019

**Closed** 2020-06-25 07:12 UTC
Labels: Crash or hang, More information required
