### ISSUE TITLE
Autopilot cannot dock on starport -weird planet bug.

### ISSUE THREAD

**Issue by Cosm1cGam3r** [pioneerspacesim/pioneer#3077] opened 2014-07-22 21:17 UTC
Autopilot cannot dock on starport at planet richardson's rock (Andho -5,5,-47)

First thing I noticed while autopilot was descending into starport was jolts of whole city. When autopilot reaches landing pad it just hangs above landing pad and cannot dock. I was able to dock on other port using autopilot. And on those docks that it could not dock I tried to do it manually but I had to compensate planet's rotation and I tried to hit that docking spot but it seemed not present. Also It seems that I am able to see that space dust speed indicator things like I would be still in space above planet.

But in case when I take over controls from autopilot while he is hovering above docking pad I am able to just go underneath this landing platform (ghosting)
When I go even lower to see if I can land on surface it appears that I am going under planets surface. ALT shows 0 while I am still descending. Now fun part begins.
I am some way under surface and first time my ship crashed on invisible surface. Second attempt and I tried to move slower and this time I landed but i was teleported into visible surface under that landing pad. But everything was moving! My ship just slided on ground and was passing through every building. I skipped time and my ship after some time seemed to be way above visible ground. Then was back again on visible surface. That repeats continuously.

Very weird bug :)

**Comment by ribbi73** [comment] 2016-12-16 00:41
I'm currently using precompiled pioneer-20161129-win32 on Windows 10 64-bit, and I think I'm experiencing  the same issue as described in the first post. Autopilot cannot land in Hudson Village, on planet Crawford's Rock, in system Gliese 810 (-4, -4, -2). Instead of landing the ship, autopilot hovers two meters above landing pad, and disabling autopilot results in ship falling through the landing pad. I'm attaching a savegame file, with the ship approaching Hudson Village. Hope this helps solving the issue.
[deneb_gliese810.zip](https://github.com/pioneerspacesim/pioneer/files/656149/deneb_gliese810.zip)

**Comment by jaj22** [comment] 2016-12-16 02:03
@ribbi73 The ship never enters the rotating frame of Crawford's Rock, which I assume is because the rotating frame is smaller than the actual terrain. It's probably the issue addressed by #3491. I'll check that again and try to get a fix merged.

**Comment by walterar** [comment] 2016-12-16 19:31
@jaj22 Surely this is another planet where the problem is evident. I call it "the killer planet of novice pilots". :)

For those who want to try their luck, here is the game saved with the ship in orbit: [](https://dl.dropboxusercontent.com/u/15391580/Pioneer/Enaress-Be)

**Comment by jaj22** [comment] 2016-12-16 22:28
Well, that was easier than I expected:

![enaress b e landing](https://cloud.githubusercontent.com/assets/562040/21280248/a957c0c4-c3dc-11e6-8176-664b2b3d89a4.png)

There's no strict terrain height vs frame size problem on Enaress B-e. You could argue there's an instrumentation issue, because the player would expect their velocity to be calculated relative to the planet surface. For planets with decent atmospheres, you get a much earlier transition and so navigation feels inconsistent.

Looking into cases where terrain height > 1.0 opened a can of worms. TerrainHeightMountainsNormal is the culprit for Crawford's Rock, but it's probably not the only one. The heightmaps are all loaded with trash maxHeight but avoid the problem due to their atmospheres.

It's extremely difficult to calculate the theoretical maximum height for many of the fractals due to their complexity. I'm considering simply doubling the max height to give a safe margin, which would also cover the heightmap fractals. For planets I've seen, doubling the max height will typically give a frame size far below that for atmosphere planets, so it's unlikely to cause issues with low orbits.

**Comment by impaktor** [comment] 2022-01-20 08:05
I'm going to deem this issue as outdated.

**Closed by impaktor** 2022-01-20 08:05 UTC
