### ISSUE TITLE
Sector map not displaying factions correctly.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#4160] opened 2017-09-19 08:34 UTC
### Observed behaviour

After a long journey towards Canho, the capital of the Free Republic faction, it was observed in the sector map that the Canho star system was coloured grey instead of the usual colour used to denote populated systems in the Free Republic. Quit Pioneer, and restarted, Canho was correctly coloured. Memory issue? 

Perhaps even stranger, and un-noticed until comparing the screenshots, Beve appears to change factions.

![screenshot-20170918-140912](https://user-images.githubusercontent.com/32020353/30583006-96c9e0ac-9d1d-11e7-9bc6-b527d4f66fdd.gif)

__My pioneer version (and OS):__

a614c6f 
Linux Mint 18 64 bit
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/1313534/opengl.txt)

**Comment by nozmajner** [comment] 2017-09-19 13:29
Try pressing tab in the sector map until it shows the faction list. You can toggle the factions, to see if they are the correct ones.

**Comment by antonspace** [comment] 2017-09-19 14:10
That is a cool feature, saves zooming out. This is what happened.

1) Entered 40 26 26 in search box, same location as above.
2) Pressed tab to bring up the faction buttons.
3) Deselected all 3 factions.

Ackmi remains on map, even though it is populated system aligned with the "Free Republic" faction.

![screenshot-20170919-145719](https://user-images.githubusercontent.com/32020353/30596620-917f306e-9d4c-11e7-8284-7b1fbed05edd.png)

**Comment by joonicks** [comment] 2017-12-30 23:45
I ran into this as well just now. Faction homeworlds dont color according to its faction. systemview shows the allegiance correctly but not the sectorview.

**Comment by fluffyfreak** [comment] 2017-12-31 15:34
I am unable to reproduce this issue, either at the location in the screenshot or by spawning at a faction homeworld.

**Comment by impaktor** [comment] 2018-01-04 19:10
Running in valgrind might turn something up, provided one can reproduce the bug.

**Comment by Web-eWorks** [comment] 2020-07-07 03:22
As the sector map view has undergone a number of iterations since (including a move to a completely different UI framework!) and we're unable to reproduce the bug, I'm closing this issue. If you can reproduce the issue with the most recent master build, please open a new issue with a save-file attached, thank you!

**Closed by Web-eWorks** 2020-07-07 03:22 UTC
Labels: Cosmetic or UI, UI rewrite
