### ISSUE TITLE
Stars Popping into view

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4077] opened 2017-08-12 16:57 UTC
### Observed behaviour
Stars Pop into view long after their halo has already appeared.
This might also be happening to Planets and Gas Giants as they use some of the same code and distances can be similar.

### Expected behaviour
Stars should not pop but should replace their billboards at a far distance, then smoothly grow larger as the player approached.

### Steps to reproduce
Head to Sirius from New Hope start point, fly towards Sirius-A and watch.

This appears to be caused by the near/far clipping planes, must investigate.

__My pioneer version (and OS):__
On current master.

**Comment by nozmajner** [comment] 2017-08-12 17:01
I can confirm this. Happens with gas giants too.

**Comment by fluffyfreak** [comment] 2017-08-13 13:31
If people can test the fix in #4083 that would be great.
I've tested it locally and can't see any issues but then I have quite modern/powerful hardware so sometimes I miss things.

**Comment by nozmajner** [comment] 2017-08-13 14:35
It works for me, Neptune came into view quite sooner than I expected. No difference in performance on my end, but my machine is relatively strong.

**Comment by nozmajner** [comment] 2020-10-11 09:15
This one popped up again on master (two weeks or so old build).
I can decide if Jupiter is smaller or larger :D :
[https://www.youtube.com/watch?v=vtwtWIizJAs&feature=youtu.be](https://www.youtube.com/watch?v=vtwtWIizJAs&feature=youtu.be)
All planet settings are on High.

**Comment by Web-eWorks** [comment] 2020-10-11 20:24
@nozmajner I really need a savefile for this one :D Hardware specs would be greatly appreciated as well; if I can get it to reproduce it should be possible to fix.

**Comment by fluffyfreak** [comment] 2020-10-16 12:42
What appears to be happening there is it being z-clipped as far as I can tell.

**Comment by fluffyfreak** [comment] 2020-10-19 09:46
It will be a good test of #4975 to see if this still happens with reverse-Z and an infinite far clip plane

**Comment by impaktor** [comment] 2020-11-15 13:57
That PR is now merged, so perhaps it fixed the issue?

**Comment by Web-eWorks** [comment] 2020-11-15 17:52
At least part of the issue is fixed - I'll implement an infinite clip plane in another PR; but we haven't been able to reproduce the issue so far.

**Comment by Web-eWorks** [comment] 2021-04-02 20:01
Closed with #5157.

**Closed by Web-eWorks** 2021-04-02 20:01 UTC
Labels:  CONFIRMED
