### ISSUE TITLE
Game terminates when leaving hyperspace in specific system

### ISSUE THREAD

**Issue by cwyss** [pioneerspacesim/pioneer#4410] opened 2018-08-26 11:06 UTC
### Observed behaviour

After doing several missions starting of from Barnard's star, I arrived in the Arphifa system (-14,5,-4) 
at Wood base (space station). Then I set up my next hyperspace route with first stop at
Andack (-14,5,-5). Upon leaving hyperspace at Andack, pioneer exited with an error message
like
In function getNearestStarport, l. 221, TradeShips.lua: "Object is no longer valid"
(see attached output.txt for details)

### Expected behaviour
no termination

### Steps to reproduce

- Load saved game file: [_quicksave](http://www2.math.uni-wuppertal.de/~fa/wyss/_quicksave)
- set Andack as hyperspace target
- engage hyperdrive

Or reproduce from scratch:

- Start at Earth, fly to Jobs pad, sell pulse cannon and radar
- hyperspace to Arphifa taking the following route:
Regula Benedicti -4,1,-3
Epsilon Scorpii -7,2,-5, refuel at Howell base
Anliawa -10,3,-5
Wain -13,5,-4
Arphifa -14,5,-4, dock with Wood base, refuel
- hyperspace to Andack

The error is quite specific. It does _not_ occur if from Arphifa you:
- hyperspace to a system different than Andack (I used Daarbe -15,5,-4), or
- first go to a different system, and then hyperspace to Andack

__My pioneer version (and OS):__
Latest release version 20180203, built from the github source.

Error also happens with the current github version (master branch) e323dd830
_and_ using the _quicksave file from above.

However, if you do the "reproduce from scratch" steps, then the error occurs only with the 
release version 20180203, not with the current github version.

So perhaps the new code already contains a fix..?

[output.txt](https://github.com/pioneerspacesim/pioneer/files/2321579/output.txt)

**Comment by impaktor** [comment] 2018-08-27 11:05
Do you know if the save you're playing with was from an even older version of pioneer? Sounds like something's gone wonky in the save file. Especially since reproducing from scratch doesn't trigger the bug.

**Comment by cwyss** [comment] 2018-08-27 12:03
I am pretty much sure that in my save no versions other than the 20180203 release are involved. (I will try to double check later)

And perhaps I was a little bit unclear:

Reproducing from scratch _does_ trigger the bug in the release version 20180203 (at least for me),
but it does _not_ for the current e323dd8 version.

I would also suppose that the problem is in the save file. And that it is only with the release version that at some point the save file gets messed up, but not in the current e323dd8 version.

**Comment by cwyss** [comment] 2018-08-27 16:08
Now I am not so sure anymore that my save does not involve other versions, sorry :(

But if it would be helpfull, I can do a new save file using only the 20180203 release version via the "reproduce from scratch" steps. I could also add more details to the description.

**Comment by fluffyfreak** [comment] 2018-11-14 22:03
@impaktor I've not been able to reproduce this crash. It might be that I fixed it with #4449 but really no way to tell without more effort than I can afford to spend right now.

Since it seems to have been fixed though I'm going to close it.

**Closed by fluffyfreak** 2018-11-14 22:03 UTC
Labels: Unexpected behaviour
