### ISSUE TITLE
Wrong UV in internal cockpit.

### ISSUE THREAD

**Issue by RepairUnit3k6** [pioneerspacesim/pioneer#4352] opened 2018-06-19 15:21 UTC
### Observed behaviour
I know it is not called experimental for fun but there is panel with wrong UV by right side inside cockpit.
![screenshot-20180619-170624](https://user-images.githubusercontent.com/24418090/41606479-0fad1186-73e4-11e8-9acd-58007f9a3322.png)
Was content of this panel important ? Does it looks like this because I'm missing equipment for it ?

### Expected behaviour
I really don't know what to expect because I have no idea what this panel should show.

### Steps to reproduce
1) Start new game at Earth
2) Enable internal cockpit
3) Rotate head right a little(move mouse while holding down mouse 3 button(scroll wheel)).

__My pioneer version (and OS):__
**Pioneer build 20180203(038a2a4)**
**Laptiop** _Lenovo B50-80_
**Running** _Microsoft Windows 7 Ultimate (x64) Build 7601_
**Eqiped with :**
**CPU** : _Intel(R) Pentium(R) CPU 3825U @ 1.90GHz_
**GPU** : _Intel Broadwell-U GT1 - Integrated Graphics_
**RAM** : _KHX1600C9S3L/4G_

**Comment by nozmajner** [comment] 2018-06-20 05:43
Yes, it's known. It was made before the mouselook feature, and I didn't had the time to finish the replacement cockpit.

**Comment by Garrom** [comment] 2018-06-20 07:11
@nozmajner Oh, i understand. I'm hobbyist graphic, specialized mostly in pixel art and voxel art but I can get together 360 degree model of cockpit.I may help, just tell me what is required to make it work(like position of origin, how to define place of camera, how textures for info panels should look like to show actual informations).Besides that, I have experience with GML, C# and GDscript(kinda like python).I wanted to offer my help before but I have problems with registration to forum(I cannot receive authorization code email).

**Comment by impaktor** [comment] 2018-06-20 07:42
@Garrom could you please stop by our [IRC](http://webchat.freenode.net/?channels=pioneer) and we can have a chat, give you access to forum, etc.? We'd love some help!

**Comment by nozmajner** [comment] 2018-06-20 07:45
Yeah, it would be great to have other artists on board.
I already have a mostly done replacement model for the cockpit, but it needs detailing and texturing.

**Comment by Web-eWorks** [comment] 2020-12-01 21:37
Closing as duplicate of #4068.

**Closed by Web-eWorks** 2020-12-01 21:37 UTC
Labels: Art, Cosmetic or UI
