### ISSUE TITLE
External view clips into station geometry when docked

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4700] opened 2019-10-10 14:20 UTC
OS: Fedora 29
Version: 2019-10-09

when docked in a station, the external cam position is "unlucky" choosen:

![Pioneer-Externalcamproblem](https://user-images.githubusercontent.com/8317797/66577446-b0207c80-eb79-11e9-8a20-94dfd7ae1ef9.jpg)

Please mve it back to something more usefull ;)

**Comment by Cyborgscode** [comment] 2019-10-10 14:21
You don't wanne see the REAR View... it's mostly BLACK, because cam position is inside the walls.

**Comment by impaktor** [comment] 2019-10-21 08:20
So basically, this could be seen as a feature request where the distance between external view camera and player is variable and bound to some key pair, possibly on numpad, as that's where camera control resides, if I remember correctly.

(I assume that would be the easiest fix, rather than have some code that checks collision detection with external camera, and try to move it to something else)

**Comment by nozmajner** [comment] 2019-10-21 08:56
You can already move the camera closer or further. Numpad +-.

**Comment by impaktor** [comment] 2019-10-21 09:08
Excellent! Then I'm taking an "executive decision" and closing this.

**Comment by fluffyfreak** [comment] 2019-10-21 09:25
I'm afraid the problem has been misunderstood, he means that when using the external camera when docked that it can clip through the station geometry.

The typical solution to this is to constrain the camera movement so that it cannot pass through solid objects using the physics/collision system/raycasting.

It's not that you can move the camera nearer or further, but that the clipping is possible at all which is the "bug".

Most games do prevent camera clipping nowadays, we've just never bothered yet.

**Comment by impaktor** [comment] 2019-11-13 09:04
@fluffyfreak so one should not be able to get an external view of a station if zooming out with the external camera when docked inside it?

For me it's a "bug vs. feature" question, but if someone wants to fix this, that's fine by me.

I guess the question is: is the external camera there for taking glory-shots of your craft/surrounding, and not part of the game-lore, or is it some "high tech drone" that is following the ship and giving the player an edge during e.g. combat?

**Comment by nozmajner** [comment] 2019-11-13 10:20
I think the drone approach would detract from the game  in the end. 
It never bothered me that it can clip trough stuff, since for me it was never an immersive feature.
A possible fix could be that the default position would be at a given max distance in case you are docked in a certain sized dock, and above your ship a bit. That would avoid most of this problem I think.

**Comment by Cyborgscode** [comment] 2019-11-13 11:52
Just remember, that the camera view was "outside" and force it to be "front" when docked to a station. After launch, it resets back to normal. Problem solved.

**Comment by impaktor** [comment] 2019-11-13 12:08
> After launch, it resets back to normal. Problem solved.

If that a problem even be...

**Comment by fluffyfreak** [comment] 2019-11-14 12:40
These external cameras are just visual "nice-to-have" features, they aren't any kind of in game tech. They mostly exist for screenshots. Some games try to avoid the clipping problem and I could come up with something to do so I guess but I don't see much value in doing so.

**Comment by impaktor** [comment] 2019-11-14 13:51
> I could come up with something to do so I guess but I don't see much value in doing so.

I concur

**Comment by Web-eWorks** [comment] 2019-11-15 21:26
Elite Dangerous' external camera suite doesn't care about clipping. You can take shots from the inside of your vessel if you so chose, although not many do. The solution to the problem is probably to implement an (at least rudimentary) free camera within a certain bound from the ship. Allow players to move it about how they like, and if they get clipping shots that's on them.

It would also allow them to frame the shot better than an orbit camera...

**Comment by Cyborgscode** [comment] 2019-11-15 21:57
If you want to open Pandoras Box, you need a free camera makro editor ;) So you can make passbys of the ship in all states and most preferable initated by keystrokes :D

**Comment by fluffyfreak** [comment] 2019-11-16 14:40
We don't really want to open any kind of pandoras box ;)

The externals cameras are not ingame canon they're just gameplay things that are nice to have. Players can catch screenshots and appreciate how their ships look - which is important - but getting odd clipping shots is their choice.

I'm going to make the decision to close this.

**Closed by fluffyfreak** 2019-11-16 14:40 UTC
Labels: Feature request
