### ISSUE TITLE
Refueling causes game to crash

### ISSUE THREAD

**Issue by pebblegarden** [pioneerspacesim/pioneer#5290] opened 2021-10-02 23:41 UTC
### Observed behaviour
![refuelcrash](https://user-images.githubusercontent.com/1176722/135734300-2237cc6c-b664-4999-a84c-e2a2e88028fa.JPG)

Game crashes with an error when attempting to refuel at a station. This has happened to multiple saved games, and once it happens, I can no longer progress with that save.
I didn't see this behavior in previous versions.

I'd attach my saved game, but I can't find it.

### Expected behaviour
The refueling operation at a station/base should not crash the game. 

### Steps to reproduce
Fly a bunch of missions, refuel at a station/base, eventually this bug will happen.

__My pioneer version (and OS):__
20210723 (0b82c65) 
Windows 10 r
[DxDiag.txt](https://github.com/pioneerspacesim/pioneer/files/7272396/DxDiag.txt)
un

**Comment by Web-eWorks** [comment] 2021-10-03 03:11
Duplicate of #5149 / #5233, but thanks for reporting it! Will close this one as it's all the same underlying cause and will hopefully have it fixed soon!

**Closed by Web-eWorks** 2021-10-03 03:11 UTC
