### ISSUE TITLE
Crashing sound played when docking at ground station

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4017] opened 2017-05-25 16:59 UTC
### Observed behaviour
When docking at a ground station (player or non-player ship) the same sound is played as if you were crashing into the sound, even when you don't take damage. This must be something new, never noticed that before. But it surprises me every time.

### Expected behaviour
Don't play the same sound as if you were crashing when you dock (or is the ship actually "slightly" crashing by mistake?).

### Steps to reproduce
Dock at Itzalean or wait for a non-player ship to dock next to you.

__My pioneer version (and OS):__
pioneer version: 7c64d721c
OS: openSUSE 64bit 42.1

**Comment by fluffyfreak** [comment] 2017-05-25 20:41
hmm, could be due to #3953

**Comment by richardpl** [comment] 2018-07-04 12:12
I can not reproduce this one. Anybody can?

**Comment by impaktor** [comment] 2018-07-04 12:31
If AI ships don't make "crashing sound" when docking, I assume it's been fixed bu the issue fluffy linked above.

**Comment by fluffyfreak** [comment] 2018-07-04 12:31
I think it was probably fixed by #3953 it's just that we don't do regular releases so there was probably still an old one being used.

**Closed by fluffyfreak** 2018-07-04 12:31 UTC
