### ISSUE TITLE
Linux: unfocus on fullscreenmode iconifies running game

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4686] opened 2019-10-07 14:22 UTC
This happens anytime, the mouse pointer leaves the fullscreen window. A know issue to most apps running in a fullscreen mode (windows or linux) instead of a borderless windowmode.

With a dual monitor it is next to impossible to fight without "pulling" so much, that the mouse pointer touches the other display. It will be no problem on a mono monitor setup.

**Comment by Web-eWorks** [comment] 2019-10-07 20:52
@Cyborgscode do you have your window manager set to 'focus window on mouseover'? I'm going to hazard a shot in the dark that that's the issue at hand. It sounds to me like Pioneer is failing to properly capture the mouse, and the WM is changing application focus and minimizing the Pioneer window once it loses fullscreen focus.

**Comment by Cyborgscode** [comment] 2019-10-07 21:00
"Not that i know of."(tm)
Cinnamon systemsettings "Windows" says: "Focuscontroll for windows "click""

**Comment by Web-eWorks** [comment] 2019-10-07 21:10
Hmm. I can't reproduce this under Budgie WM, so I'm going to tentatively consider this a platform-specific issue. I don't have a MATE desktop to debug under, but if you want to dig further into the problem, you can try building Pioneer locally and changing https://github.com/pioneerspacesim/pioneer/blob/e85a0cf4ca8e710d926f6c1581c3d9db242f361f/src/graphics/opengl/RendererGL.cpp#L70 to `SDL_WINDOW_FULLSCREEN_DESKTOP` (aka Borderless Fullscreen) to see if that fixes your issue.

Also, for future reference, please remember to include your full OS details and Pioneer version with every platform-related issue you open (like this one). It makes debugging things significantly easier.

**Comment by Cyborgscode** [comment] 2019-10-07 21:27
WM: Cinnamon 4.0.10 + Xorg

I agree on the "windowmanager will cause it" theory. EVE Online and Runes of Magic had the same issues and fixes (borderless window), and they are not SDL Games. 

But i would suggest to implement it as an SelectBox ( Fullscreen | Fullscreen Window | Window ) right away. It won't hurt and fix it most of the time.

BTW: on a 3k Wayland display running gnome 3.32+ , there where no other resolutions to choose than the 3k itself. As i have seen this by other apps and gnome itself, i wondered and one particular game had a nice solution for it: They open the screen in 3k, but you can choose a scale resolution, to speed things up. The weaker your hardware is, the smaller you choose it. Worked great and it fixed the 3k resolution on a small 11" display problem: you have problems to read things, if the ui does not get scaled. Either you inheritate the scale option from gnome or you make a nice select box right away. The later sounds better, because gnome and others are switching to free adjustable scalefactors like "1.35" or "2.87" instead of 100% 200% etc.

**Comment by impaktor** [comment] 2019-10-08 06:07
So basically, this can be considered a request to expose that SDL setting in a PR. Preferably with explaining tooltip as well.

**Comment by Web-eWorks** [comment] 2019-10-08 20:39
@Cyborgscode please try running Pioneer with the `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0` environment variable set. This *may* fix your issue, but I'm going to guess that it's something specific to the Cinnamon WM.

**Comment by Cyborgscode** [comment] 2019-10-08 22:20
works.

**Comment by Web-eWorks** [comment] 2019-10-09 01:51
So, the issue is that something in your WM stack is causing the game to lose input focus when you mouse off the screen. Aside from capturing the mouse, we can't do anything about that. However, we will try to implement borderless fullscreen... soon(tm). Bit of a infrastructure rewrite to make everything work properly there.

**Comment by impaktor** [comment] 2019-10-09 07:00
> However, we will try to implement borderless fullscreen... soon(tm). Bit of a infrastructure rewrite to make everything work properly there.

So it's not as easy to just expose `SDL_WINDOW_FULLSCREEN_DESKTOP` in the settings menu?

**Comment by fluffyfreak** [comment] 2019-10-09 09:29
> So it's not as easy to just expose `SDL_WINDOW_FULLSCREEN_DESKTOP` in the settings menu?

When is anything that easy? 😁

**Comment by Cyborgscode** [comment] 2019-10-09 09:42
Workaround-Patch for Fedora installations to make it perma:

Edit /usr/share/applications/pioneer.desktop and change it to this:

[Desktop Entry]
Version=1.0
Name=Pioneer
GenericName=Pioneer Space Simulator
Comment=A game of lonely space adventure
Exec=env force_s3tc_enable=true SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 pioneer
Icon=/usr/share/icons/hicolor/64x64/apps/pioneer-64x64.png
Terminal=false
Type=Application
Categories=Game;AdventureGame;ActionGame;Simulation;
X-Desktop-File-Install-Version=0.23
StartupNotify=false

**Comment by Cyborgscode** [comment] 2019-10-09 09:52
https://bugzilla.redhat.com/show_bug.cgi?id=1759866

**Comment by impaktor** [comment] 2019-10-09 12:18
So I guess we can close this now, as it's not on our table?

Or does @Web-eWorks want it open for "soon(tm)" PR to come?

**Comment by Web-eWorks** [comment] 2019-10-09 16:17
Closing this as an upstream issue. We'll track borderless fullscreen elsewhere.

**Closed by Web-eWorks** 2019-10-09 16:17 UTC
Labels: Feature request, Platform Specific
