### ISSUE TITLE
Unable to load or save games

### ISSUE THREAD

**Issue by weedfreak** [pioneerspacesim/pioneer#3576] opened 2015-12-27 14:15 UTC
Using pioneer-20151130-linux64 on Arch I cannot load any saves, there is no visible section of any game and I get a 'file is corrupt' error or a permissions error. This applies to any save with this version. and to using the resume button.

I tried deleting the .pioneer folder to clear any setting problems, start a new game and save it, resume works unless I exit the try to resume, if I restart and only have one save game then I can load it and play, if there are more saves then it does not load any.

**Comment by johnbartholomew** [comment] 2015-12-27 23:07
The save game version number was last changed on November 2nd:
- October 17th: @24a58a648471e7820c5692cad3b8965226d57d88 -- "Bump the save version to 82"
- October 17th: @3d80b4b4277b1684de4ecc1203d0d9f315d514fa -- "Bump save game version to 83, 1 higher than another PR I expect to merge first."
- November 2nd: @43e5577b2e57f520d211dea16b4ac7fc75ec806f -- "Merge branch 'pcg', #3485" (save version reverted to 82)

The "This saved game file could not be opened due to permissions or something..." message means the game can't access the save file, which is most likely to happen if the file doesn't exist. When I tried just now, the autosave-on-game-exit didn't work, which meant the "_exit" save file was never created for me, so I got that message. I don't know when autosave got broken.

I haven't noticed any problems with having multiple save files available.

**Comment by johnbartholomew** [comment] 2015-12-27 23:13
Oh, apparently autosave was deliberately turned off and is now controlled with a config option. See #3518.

**Comment by impaktor** [comment] 2016-07-06 13:38
6 months old, and save/load seems to work for everyone else, this is at leat outdated -> closing.

@weedfreak if you can confirm that new saves in latest pioneer are still broken then please post how to reproduce the bug/error, and re-open this.

**Closed by impaktor** 2016-07-06 13:38 UTC
Labels: Unexpected behaviour
