### ISSUE TITLE
Crash upon clicking "Switch to system overview" button after engaging enemy ship.

### ISSUE THREAD

**Issue by Another-MrZ** [pioneerspacesim/pioneer#4297] opened 2018-01-26 13:52 UTC
### Observed behaviour
After engaging a battle against an enemy ship, the game crashed as soon as I clicked on the "Switch To System Overview" button. This happened in more than one occasion.

I have noticed that if I change manually the autopilot to a celestial body by clicking on it, the game does not crash any more. Changing to a hyperspace cloud however, does not solve the issue, and the game still crashes when clicking on the "Switch to system overview". 

This crash could be having something to do with the targeting set on the hyperspace cloud, but I am not sure.

### Expected behaviour
Game should not crash.

### Steps to reproduce
1. Undertake a dangerous passage mission having weapons to fight
2. Target the enemy ship by clicking on it 
3. Possibly ensure the navigational target is on a hyperspace cloud before targeting the ship (pink marker)
4. Destroy the ship
5. Click on the "Switch to system overview"
6. See the game crashing without any message.

__My pioneer version (and OS):__
Build 20171001 (316a1f7) - Windows 7

Savegame attached

![pioneer-crash when pressing](https://user-images.githubusercontent.com/34732798/35442702-11abc988-02a0-11e8-9be8-6ddf706262d2.jpg)
[Savegame-Targeting crash.pdf](https://github.com/pioneerspacesim/pioneer/files/1667915/Savegame-Targeting.crash.pdf)

**Comment by impaktor** [comment] 2018-01-26 15:25
Pioneer has gone through a lot of changes recently, and your version is quite old. 

You could try compiling master branch, and see how that works. Instructions are [here](https://github.com/pioneerspacesim/pioneer/blob/master/COMPILING.txt)

**Comment by Another-MrZ** [comment] 2018-02-06 13:19
Issue confirmed on newer build: 20180203. Game still crashes without message.

**Comment by impaktor** [comment] 2018-02-06 13:38
I can confirm, clicking sector view, then system overview causes segfault:

```
Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
0x0000555555764d70 in SystemInfoView::UpdateIconSelections (this=this@entry=0x555557d6fd10) at SystemInfoView.cpp:616
616					if (bodyIcon.first == navpath.bodyIndex) {
(gdb) bt
#0  0x0000555555764d70 in SystemInfoView::UpdateIconSelections (this=this@entry=0x555557d6fd10) at SystemInfoView.cpp:616
#1  0x0000555555767140 in SystemInfoView::SystemChanged (this=this@entry=0x555557d6fd10, path=...) at SystemInfoView.cpp:498
#2  0x00005555557686ae in SystemInfoView::Update (this=0x555557d6fd10) at SystemInfoView.cpp:570
#3  0x00005555556c1312 in Pi::MainLoop () at Pi.cpp:1460
#4  0x00005555556c26dd in Pi::Start (startPlanet=<optimized out>) at Pi.cpp:1323
#5  0x00005555555c0f90 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:178
```

**Comment by Another-MrZ** [comment] 2018-02-07 19:51
The autopilot target set on hyperspace cloud is enough to trigger the bug at any point of the game. No need to engage in any fight.

**Comment by richardpl** [comment] 2018-06-19 16:40
This have been fixed too. See #4350, the duplicate of this bug report.

**Closed by richardpl** 2018-06-19 16:40 UTC
Labels:  CONFIRMED, Crash or hang
