### ISSUE TITLE
Orbit Planner: precision issue

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4937] opened 2020-07-22 14:15 UTC
The computed position on a orbit computed with the orbit planner may be different for extreme orbits and extreme time-delta's.

![image](https://user-images.githubusercontent.com/1067920/88187199-8501a800-cc36-11ea-9ce2-83b6240824ee.png)

### Observed behaviour
* different position on orbit for same time

### Expected behaviour
* same position on orbit for same time

### Steps to reproduce
* start at station
* fly out from station
* accelerate a bit into a hyperbolic "orbit"
* press the 10'000'000x and -10'000'000x button in alternating order 

__My pioneer version (and OS):__
git 20200718 linux

**Comment by Gliese852** [comment] 2020-07-22 15:17
@PtrMan can't reproduce. I see in the screenshot that the planner time does not match the game time, maybe this is the problem?

**Comment by PtrMan** [comment] 2020-07-22 16:09
I admit that it's hard to reproduce. I didn't add a safegame, duh.

**Comment by impaktor** [comment] 2020-07-23 06:01
I'll leave this to @Gliese852 to close, who knows this code the best of us by this point, I think.

**Comment by Gliese852** [comment] 2020-09-14 18:42
Closing because it is not reproducible.

**Closed by Gliese852** 2020-09-14 18:42 UTC
