### ISSUE TITLE
Fonts become unreadable when playing through Steam

### ISSUE THREAD

**Issue by v1nsai** [pioneerspacesim/pioneer#3924] opened 2017-02-12 18:01 UTC
![capture](https://cloud.githubusercontent.com/assets/410443/22864619/cdd2f130-f122-11e6-9abd-79ae050d5858.PNG)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/769497/opengl.txt)

### Observed behaviour
When running Pioneer as a non-Steam game, fonts become unreadable.  I've tried creating a simple mod to switch fonts and have tried several but they are always fine without Steam and unreadable when run through Steam.  Trying to run through Steam in order to get more options to reconfigure Xbox or Steam Controller.

### Expected behaviour
Fonts to be readable.

### Steps to reproduce
Add pioneer.exe to Steam through the Add a non-Steam game button, then run it.  Fonts are unreadable.

__My pioneer version (and OS):__
Pioneer build 20161129 (0c423b2)
Windows 10 fully updated

**Comment by nozmajner** [comment] 2017-02-12 18:15
That seems to be the same issue as #2931 visually, which was caused by some MSI overlay that displayed FPS and such.
I had the guess that if you disable the steam overlay, that might fix the issue, but there isn't any overlay, nor any option for it, so that won't work.

**Comment by v1nsai** [comment] 2017-02-12 20:56
Yea!  That's exactly like what I'm seeing.  Sorry for the dupe post, I searched for 'font' but should have also checked for 'text'.  I've been looking through the Steamworks API to see if compiling a few components in with the main branch might fix the problem but it's a bit over my head.......I'll contribute anything useful I can figure out to the other thread.

**Comment by fluffyfreak** [comment] 2017-02-13 10:06
@v1nsai I think if you disable the Steam overlay it should be fine.
I believe that it's because we request a strict forward compatible OpenGL context which forbids older style/purpose OpenGL calls which a lot of overlays rely on.

**Comment by fluffyfreak** [comment] 2017-02-13 10:08
Re-opened issue as I'm wondering if we should put some comments into the readme, wiki or FAQ?

**Comment by v1nsai** [comment] 2017-02-14 01:18
It would definitely be helpful to have something in the wiki.  I did lots of Googling for "Pioneer Space sim Steam" and variations on that and never found anything that said it was the overlay's fault until noz pointed me that way after I posted here.

I would imagine disabling this strict forward compatible OpenGL context would just require unticking a few flags in ./configure before compilation, right?  I've been coding for a few years but never tried game programming of any sort before, this seems like a good excuse to start learning :-D  

I really want to make this work with a controller, I just can't imagine playing a flying game without a stick and since this game still needs mouse capability the Steam controller is really quite perfect for the job.

**Comment by v1nsai** [comment] 2017-02-15 02:33
Well, you can disable the whole Steam overlay in settings, then right-click on the game in the Library screen and select Edit Steam Controller configuration.  This allows playing the game and editing controller configs.  I even tried alt-tabbing out to change controls in game and it played stable for about 15 minutes.  Hopefully this helps someone out.

**Comment by impaktor** [comment] 2017-02-19 12:21
Tried putting it on the wiki, but even if using simple html, seems that it mangles all other text already there. The wiki busted, as no edits are possible. 
Reference:
https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=488

**Comment by fluffyfreak** [comment] 2017-02-28 16:17
This one might also be fixed by the reintroduction of the GLEW library

**Comment by alugarius** [comment] 2017-04-03 16:54
Also happens on Linux

**Comment by richardpl** [comment] 2018-06-26 17:00
Is this still relevant?

**Comment by nozmajner** [comment] 2018-06-26 17:20
Not really. And with the transititon to imgui, it might fix itself.

**Closed by nozmajner** 2018-06-26 17:20 UTC
