### ISSUE TITLE
Crash with translations in Options screen

### ISSUE THREAD

**Issue by gunchleoc** [pioneerspacesim/pioneer#3527] opened 2015-11-10 12:20 UTC
Pioneer crashes due to translation contents in the gd locale - this crash does not happen in the English language version.

Version: pioneer-20151109-linux32, downloaded from Sourceforge
OS: Ubuntu 14.04

To reproduce, set the language to "Gàidhlig" and restart Pioneer.

Click on "Roghainnean" (Options).

Ma language has a lot of `' `  in it, so if you use `' '` to delimit your JSON files, that might be the problem. Is there a way to have an error messages that shows which string, or at least with JSON file has the problem? Unfortunately, Transifex doesn't allow you to search for `' `. I can search for JSON Key names there though.

Console output:

Loading took: 56132.430260 milliseconds
CreateCollisionMesh for : (ac33)
CreateCollisionMesh for : (amphiesma)
CreateCollisionMesh for : (deneb)
CreateCollisionMesh for : (dsminer)
CreateCollisionMesh for : (kanara_civ)
CreateCollisionMesh for : (lunarshuttle)
CreateCollisionMesh for : (malabar)
CreateCollisionMesh for : (molamola)
CreateCollisionMesh for : (natrix)
CreateCollisionMesh for : (nerodia)
CreateCollisionMesh for : (pumpkinseed)
CreateCollisionMesh for : (sinonatrix)
CreateCollisionMesh for : (storeria)
CreateCollisionMesh for : (varada)
CreateCollisionMesh for : (vatakara)
CreateCollisionMesh for : (venturestar)
CreateCollisionMesh for : (wave)
CreateCollisionMesh for : (xylophis)
error: [string "[T] @ui/Settings.lua"]:22: bad argument #1 to 'Label' (string expected, got nil)
stack traceback:
	[C]: in function 'Label'
	[string "[T] @ui/Settings.lua"]:22: in function 'optionCheckBox'
	[string "[T] @ui/Settings.lua"]:123: in function 'template'
	[string "[T] @ui/Settings.lua"]:360: in function 'template'
	[string "[T] @libs/ui/TabView.lua"]:130: in function 'SwitchToNum'
	[string "[T] @libs/ui/TabView.lua"]:96: in function 'AddTab'
	[string "[T] @ui/Settings.lua"]:367: in function 'Settings'
	[string "[T] @ui/MainMenu.lua"]:78: in function <[string "[T] @ui/MainMenu.lua"]:76>

**Comment by impaktor** [comment] 2015-11-10 12:37
Clicking Options in Lang=gd works for me on current master. The problem here is that no English string `ENABLE_AUTOSAVE` was added before the build was shipped. So this crash should happen on latest build _for all_ languages, the way I see it. Or at least for all non-English languages.

**Comment by impaktor** [comment] 2015-11-10 12:39
So this is the "Enable Autosave" #3518 string that i supposed to be in ui-core:

    [string "[T] @ui/Settings.lua"]:123: in function 'template'

This problem should be fixed in next build, since current master runs fine.

**Comment by Tichy** [comment] 2015-11-10 12:39
I can confirm that. It happens to me eventy time there's a new untraslated string in my language of choice.

**Comment by impaktor** [comment] 2015-11-10 12:46
> It happens to me eventy time there's a new untraslated string

Really? But then it is fixed in the release after that one?

**Comment by Tichy** [comment] 2015-11-10 12:52
Yes. When I build the version with the translated string, it works without errors.

**Comment by impaktor** [comment] 2015-11-10 12:58
> I can confirm that. It happens to me eventy time there's a new untraslated string in my language of choice.

Just to be clear: Are you talking about the builds you download from pioneer page, or that you build yourself? In the latter case, it's expected, since it takes a few hours (12?) to insert the English untranslated string in to it.json (or gd.json). However, a build will always sync before, thus it should never crash due to missing strings. There should always be an English version of it in the *.json file.

**Comment by gunchleoc** [comment] 2015-11-10 13:08
In my case, it was the pre-compiled package downloaded from the pioneer page. I chan check again if this has been fixed once a new development build is available.

**Comment by Tichy** [comment] 2015-11-10 13:13
For me, I build it by myself.

**Comment by impaktor** [comment] 2015-11-10 13:28
> For me, I build it by myself.

I _expect_ it to crash if your master is updated after, say #3518 was merged, but before the transifex sync happened.

The new string was added yesterday at 10:21
aad72096e9ac067c9d12d0416d1722c53e9ffd4e

langauge files were synced yesterday at 12:00
245ebccd4407bf251ae4da144b5fdd4555219d2e

Thus, any build made between those to points will crash.

**Comment by Tichy** [comment] 2015-11-10 13:56
Il 2015-11-10 14:28 Karl F ha scritto: 

>> For me, I build it by myself.
> 
> I _expect_ it to crash if your master is updated after, say #3518 [1] was merged, but before the transifex sync happened.

That is the case. So it works as expected. 

I thought that there's some kind of fallback to english strings, when
the localized ones are missing. 

 

Links:
------
[1] https://github.com/pioneerspacesim/pioneer/pull/3518

**Comment by gunchleoc** [comment] 2015-11-10 14:08
Although this is an edge case, it might be good to have a fallback, e.g. when a key is missing from the JSON file (I assume that this is the problem?), load the original English string instead and write some log output.

**Comment by impaktor** [comment] 2015-11-10 14:35
Well, the fall back is that the pioneer build machine should always sync transifex which will insert the English strings in the json file for us before shipping a build. Thus a pioneer release should never lack a string, as seems to be the issue for the original poster. 

Those compiling from source could be considered "professionals" and can "deal with it" (i.e. update a few hours later, or revert). :sunglasses:  (but sure, no crash at all would be better)

> (I assume that this is the problem?

Yes.

So the real issue here is that the build failed to update the language files.

**Comment by gunchleoc** [comment] 2015-11-11 11:08
I can confirm that building from current trunk works.

**Comment by impaktor** [comment] 2015-12-10 13:21
I'll write this off as some random fail in the build machine, due to tummy ache, since the build mahcine has been sick for some time, randomly puking. 

@robn did cure the build mahcine, and the missing string is in the current build (I just checked ru.json), so that should be fine as well. It will be interesting to see if the new Search and Rescue module will have all the strings in place for the _next_ build. 

Closing for now.

**Closed by impaktor** 2015-12-10 13:21 UTC
Labels: Build, Crash or hang, Language
