### ISSUE TITLE
Crash loading old models

### ISSUE THREAD

**Issue by mike-f1** [pioneerspacesim/pioneer#4637] opened 2019-07-08 18:12 UTC
### Observed behaviour

Pioneer crashes during loading, with these lines on console:
```
...[SNIP]...
new ModelCache
Shields::Init
BaseSphere::Init
GenerateIndices: triangles count = 2312, mid indexes = 6528, hi edges = 102
CityOnPlanet::Init
decompressed model file Dome1.sgm (137.79 KB) -> 354.22 KB
LoadSurfaceFromFile: models/buildings/vlastan/Dome1_D.dds: Unsupported image format
LoadSurfaceFromFile: models/buildings/vlastan/Dome1_S.dds: Unsupported image format
LoadSurfaceFromFile: models/buildings/vlastan/Dome1_G.dds: Unsupported image format
LoadSurfaceFromFile: : could not read file
No loader for: Group
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

### Expected behaviour

Pioneer load...

### Steps to reproduce

Download or pull last master, compile and run

### Hints

It may be related to #4626 or to #4628, thus pinging
@Web-eWorks  and @pcercuei 

__My pioneer version (and OS):__
last master (0f3379f23224) on Ubuntu

**Comment by pcercuei** [comment] 2019-07-08 22:03
It's not related to #4628, I reverted it locally and it didn't fix the bug (which I can reproduce).

**Comment by pcercuei** [comment] 2019-07-08 22:27
I bisected the issue, 09a84e669 ("Better profiling, speedup model saving / loading.") is the first bad commit.

**Comment by Web-eWorks** [comment] 2019-07-08 23:49
That's very weird, because it worked perfectly fine on my end during development. I am going to be unable to seriously debug this code for several weeks, but I'd recommend looking in `TextureBuilder.cpp` as – IIRC – that's where `LoadSurfaceFromFile` is defined.

**Comment by mike-f1** [comment] 2019-07-09 16:02
Ok: I just did some investigation.

It seems that if all models are _not_ compiled or all are compiled it works like a charm.
Thus I removed manually some `*sgm` files and... it keep working :worried: 

I'm unable to reproduce the bug. @pcercuei , are you able to reproduce it?

OT(?): I get all icons "darker" (which is probably an unrelated issue, but I would check if there's someone else that get the same):
![DarkIcons](https://user-images.githubusercontent.com/13293916/60904203-ec8ac680-a272-11e9-80dc-99dd6857126a.png)

**Comment by pcercuei** [comment] 2019-07-09 16:06
I removed the installed files, then installed them again, now it works.

**Comment by mike-f1** [comment] 2019-07-09 16:34
> I removed the installed files, then installed them again, now it works.

what a pity :/

Anyway:, the only idea I got is of some issue when loading models compiled with the old algorithm, but doing some investigation will take time I don't have right now.  @Web-eWorks, do you did some test in order to exclude this scenario?

**Comment by vakhoir** [comment] 2019-07-10 19:15
> OT(?): I get all icons "darker" (which is probably an unrelated issue, but I would check if there's someone else that get the same):

Yeah, I was about to ask if anyone had the same problem too.

**Comment by fluffyfreak** [comment] 2019-07-11 12:32
You can probably test this by having a few of the older SGM files in the mods folder.

**Comment by CylonicRaider** [comment] 2019-07-11 19:29
I observe darkened however-that-particular-UI-module-is-called buttons as well. The final on-screen color is `#000000` in the main menu and `#000010` in-game. Perhaps some sort of redundant alpha pre-multiplication? While they look snazzy, I wish they had a distinct on-hover color like they used to.

**Comment by vakhoir** [comment] 2019-07-11 19:41
I figured it out in #4624, it's because of the casting to uint8 in the Shade method introduced in c19aab4e482d4574b7b6af2e738a1574db1dbc99.

**Comment by pcercuei** [comment] 2019-07-11 21:12
Oops. Sorry about that.

**Comment by pcercuei** [comment] 2019-07-12 00:15
Both the screenshots issue and the transparency issue are fixed in #3640.

**Comment by mike-f1** [comment] 2019-07-12 08:59
> Both the screenshots issue and the transparency issue are fixed in #4640.

Nice&quick work :smile: 

Then, back to original title,

> You can probably test this by having a few of the older SGM files in the mods folder.

Right: I simpli don't know when I have enought time to recompile on an old version; compile models; then recompile on newest :sweat_smile:

I leave this open for now.

**Comment by fluffyfreak** [comment] 2019-07-14 14:55
I can confirm this is a bug, SGM6 non-lz4 appear to be broken. Not tracked down the cause yet but I've got a callstack where it's failed in deserialising `GeomTree`.

I'll dig around a bit.

**Comment by fluffyfreak** [comment] 2019-07-14 15:49
Hmm, interesting, in `BinaryConverter::LoadNode` it seems that it doesn't find the loader from `m_loaders` for "Group" despite it being present and the string being correct.

**Comment by fluffyfreak** [comment] 2019-07-14 15:52
Changing https://github.com/pioneerspacesim/pioneer/blob/master/src/scenegraph/BinaryConverter.cpp#L451 to read `auto loadFuncIt = m_loaders.find(ntype.c_str());` seems to fix it but I'm a bit baffled why it happened. I think because the actual `ntype` string is "Group/0" perhaps

**Comment by Web-eWorks** [comment] 2019-07-14 16:39
Hmm. I thought I rewrote string loading/saving functionality to be compatible with the previous iteration. There's probably an off-by-one error in `Serializer::Reader::operator<<(std::string)` compared to the previous behavior (though it works just fine with SGM files written by the Writer counterpart).

**Comment by fluffyfreak** [comment] 2019-07-15 08:46
After wasting some time this morning writing tests for the serialisation I can confirm that it works just fine. So the problem is being introduced elsewhere. Possibly conversion between C-style strings and std::string operations maybe?

**Closed** 2019-07-22 20:46 UTC
Labels:  CONFIRMED
