### ISSUE TITLE
Spacestation.lua attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by SkinSz** [pioneerspacesim/pioneer#5233] opened 2021-07-28 00:10 UTC
**Observed behaviour**
Loaded my savegame. Went to the already docked station and switched to the commodities or equipment tab and seen the error.

**Expected behaviour**
Obviously the GUI should function without issues.

**Steps to reproduce**
Unknown as I don't know what the cause is. Sounds like someone that understands the code needs to do some digging (I can only read a little bit of powershell and that has nothing to do with a real useful scripting language :> )

**Attachments**

![1](https://user-images.githubusercontent.com/69037806/127243147-480594a4-4289-48a3-846a-7a41d2cf973a.png)
![2](https://user-images.githubusercontent.com/69037806/127243151-c62e7d4b-06d7-4f3c-b4d7-e0286f7933c8.png)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6889377/output.txt)

**Comment by Web-eWorks** [comment] 2021-07-28 00:34
Duplicate of both #5149 and your most recent issue #5231. I'll leave this issue open, but it's the same edge-case bug where equipment data isn't properly being initialized with the station object.

**Comment by SkinSz** [comment] 2021-07-28 01:51
Well, I haven't thought of [#5231](https://github.com/pioneerspacesim/pioneer/issues/5231) beeing a big deal as it sorted itself. Further having the game in such an inconsistent state seems to cause crashes entering a new system via a hyperdrive jump.

**Comment by joonicks** [comment] 2021-09-26 21:17
in my playground setup, this bug is triggered even on creating new games, even ending the game and starting a new the error never resets

its further indication it seems that lua is not reset between games

**Comment by joonicks** [comment] 2021-09-27 00:11
this function is a prime suspect (SpaceStation.lua)

```
Event.Register("onShipDocked", function (ship, station)
	if ship ~= Game.player or SpaceStation.adverts[station] then return end
	createStationMarket(station)
end)
```

**Closed** 2021-11-06 20:00 UTC

**Comment by Jose-Reis** [comment] 2022-01-27 23:09
Is this the same error. Got it after landing on a station where there was a slave revolt.
![pioneer-error](https://user-images.githubusercontent.com/5701839/151458377-7097e0f3-98fb-4b7a-8afb-b78caa7f3056.png)

**Comment by Web-eWorks** [comment] 2022-01-28 08:30
If you were playing with the release from July, yes it's probably the same error (and since fixed). If you're playing the most recent development builds then it's most likely #5221.
