### ISSUE TITLE
Loading Save Issue

### ISSUE THREAD

**Issue by jimmyli97** [pioneerspacesim/pioneer#4203] opened 2017-12-18 07:48 UTC
Hi, thanks so much for developing this game I'm really enjoying it!
I'm experiencing an issue where sometimes the game will load incorrectly: e.g. timeskip functions stop working, a ship alert is displayed when there are no ships nearby. It's difficult to reproduce because it only happens every so often (my magic number is saving the game and then reloading it 3 times). However, reloading the save fixes it, so I'm not sure if this is a big deal but I thought I'd report it anyway.

[output.txt](https://github.com/pioneerspacesim/pioneer/files/1567036/output.txt)
Last bug-free: N/a (downloaded today)
Issue has not been reported before
<img width="960" alt="falseshipalert_brokentimeskip" src="https://user-images.githubusercontent.com/1155874/34094958-63ef6712-e39d-11e7-970b-9a8917b20e49.png">

### Observed behaviour
Loading a save will sometimes cause timeskip functions to stop working and a ship weapons alert to appear. 

### Expected behaviour
Loading a save will result in state last saved.

### Steps to reproduce
Save. Load the save. Repeat as necessary until it appears (takes a few tries for me)

Version: ver 20171001 (316a1f7)
Windows 8 (High DPI scaling override: Application)
Very High graphics setting, Planet textures, Speed lines, HUD trails, Autosave enabled

**Comment by The-EG** [comment] 2017-12-30 11:30
I believe this has been fixed by PR #4218 , but a new release hasn't come out yet.

**Comment by impaktor** [comment] 2017-12-30 13:48
Ping @johnbartholomew

**Comment by johnbartholomew** [comment] 2017-12-30 15:00
I think The-EG is probably correct. The spurious ship weapons alert should be fixed by #4218. Time acceleration not working could also be caused by the spurious alert problem since we lock time acceleration out when your ship is under attack.

**Comment by impaktor** [comment] 2017-12-30 16:11
good enough for me, -> closing.

**Closed by impaktor** 2017-12-30 16:11 UTC
Labels: Unexpected behaviour
