### ISSUE TITLE
M and T keystrokes not working

### ISSUE THREAD

**Issue by Blaxcot** [pioneerspacesim/pioneer#4976] opened 2020-10-16 17:35 UTC
I have just started taking dog fights seriously and find that the "M" (missile launcher) and "T" (target) keystrokes do not work. Only way to target and/or launch missiles is to click on them with the mouse, in the middle of a dogfight. They also do not work when I assign them to buttons on my Attack 3 joystick. Anyone else have this problem or know a workaround. Thanks. Blaxcot.

### Steps to reproduce Must use mouse lhc.

__My pioneer version (and OS):__  Pioneer 20200203 Windows

**Comment by Web-eWorks** [comment] 2020-10-16 17:39
I'll have to look at the history, but from what I remember of the relevant code the M and T keys haven't been connected to missile targeting in a very long while. If I can find where it was changed, I'll see if I can resurrect the old behavior!

**Comment by impaktor** [comment] 2020-10-16 17:43
@Blaxcot we (devs) don't do much dog fighting so your input is valuable, e.g. does "E" for ECM work?

@nozmajner is in the process of re-balancing the ships, if you're interested in play testing that, please give us/him a shout.

**Comment by Blaxcot** [comment] 2020-10-16 17:57
Thanks for the swift reply. And I'd like to take this opportunity to thank you for keeping an incredibly fun and exciting project going. I was instantly hooked. Haven't got to the E and ECM features yet, but will keep you updated. Looking forward to what you come up with.

**Comment by The-EG** [comment] 2020-10-16 18:00
The current default bindings in master:
![image](https://user-images.githubusercontent.com/7342077/96291593-46ba2180-0fb6-11eb-9589-5ced857be398.png)

Space does work for firing the cannon, but I can confirm that m and y do not work as advertised. 

I think I see part of the problem: Clicking on the missile icon does fire the missile if you have a combat target. If you have different kinds of missiles (such as 1 guided and 1 unguided) they show up as separate icons and you can choose which to fire by clicking on the different icons.

I don't think clicking on the icons is ideal, unless you have a touch screen, but I also don't see a way to set what missiles are active, which is probably why the 'old' keybinding isn't firing: it doesn't know which missile to fire.

**Comment by impaktor** [comment] 2020-10-16 18:00
@Blaxcot make sure to compile from master, as there's been [a lot of nice changes](https://github.com/pioneerspacesim/pioneer/blob/master/Changelog.txt) since last release.

**Comment by The-EG** [comment] 2020-10-16 18:27
> Maybe default to the most expensive? (or the "top" one)

Looking at the code a bit...it should be calling Ship:FireMissleAt (lua), which looks like it just 'picks' one (whichever comes up first)...so it _should_ work, but it's never getting called because PlayerShipController::FireMissile (c++) is never getting triggered.

**Comment by Web-eWorks** [comment] 2020-10-16 18:47
I think I know why, too. Right now all systems have to manually forward events to their keybindings, which is nuts and currently under replacement. I'll resurrect the input-frame branch tonight and see if I can get it in suitable state to merge.

**Comment by The-EG** [comment] 2020-12-09 12:39
Ping!

This is still broken in master, post input bindings refactor. I thought I also saw some input-frame stuff go in not long after all of the input bindings things too...

**Comment by Web-eWorks** [comment] 2020-12-09 17:56
Now that input frame is merged, this should be relatively easy to fix @The-EG. Unfortunately I might not have time for a while to do anything bigger than tiny bugs, so I might have to delegate this to someone else.

**Comment by The-EG** [comment] 2020-12-10 18:14
Testing this now and M (fire missile) is working. But, as you pointed out in IRC, it looks like the target doesn't have any code to trigger, so that will be more involved.

**Comment by impaktor** [comment] 2020-12-16 15:01
@The-EG how does one select which missile to fire? (shift-m to cycle through? Or clicking it selects, instead of fire, and `m` for fire)

**Comment by The-EG** [comment] 2020-12-16 15:20
> how does one select which missile to fire? (shift-m to cycle through? Or clicking it selects, instead of fire, and `m` for fire)
@impaktor Currently, if you want to choose a missile to fire you will need to use the UI and click on the missile to fire it. Pressing the keybind (m) just 'picks' one.

I do like the idea selecting one from the UI, though.

**Comment by The-EG** [comment] 2020-12-18 15:47
I forgot to copy/paste the IRC here, but to summarize: a good approach could be to have an 'active' missile that could be cycled with a keybind. The user can still click on the different missile types to fire them directly, but pressing 'm' would fire the currently 'active' missile type. The active type would go to the next available type when a type is depleted, etc.

**Comment by nozmajner** [comment] 2020-12-18 16:36
Wouldn't it be better if clicking on the Missile just selected it as active, instead of firing it? Might avoid some misfires that way.

**Closed** 2023-01-19 20:39 UTC
Labels: Input
