### ISSUE TITLE
Segmentation fault upon hyperjump arrival

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5199] opened 2021-05-27 16:22 UTC
### Observed behaviour
at the end of the hyperjump to the next step (Shifu) the game crashes.

### Steps to reproduce
load attached savegame [issue crash upon hyperjump.zip](https://github.com/pioneerspacesim/pioneer/files/6555439/issue.crash.upon.hyperjump.zip)
plan hyperjump to Shifu system
hyperjump (error on arrival)

output
`Started hyperspacing...
Stars picked from galaxy: 183416
Final stars number: 500000
Shifu:
    height fractal: Ellipsoid
    colour fractal: StarM
    seed: 2553857242
Shifu a:
    height fractal: Ellipsoid
    colour fractal: StarBrownDwarf
    seed: 143134285
Shifu a a:
    height fractal: Asteroid3
    colour fractal: Asteroid
    seed: 2148565527
Shifu a b:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 3920381483
Shifu a c:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 1452552246
Shifu a d:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 3799378358
Shifu a e:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 2703843160
Shifu a f:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 2620854534
Shifu a g:
    height fractal: Barren Rock 2
    colour fractal: Rock
    seed: 2401920067
Shifu b:
    height fractal: Ellipsoid
    colour fractal: StarBrownDwarf
    seed: 2004550379
New Sawyer:
    height fractal: HillsCraters2
    colour fractal: Rock
    seed: 919778332
Ramirez Settlement:
    height fractal: HillsNormal
    colour fractal: Rock
    seed: 1382183848
Mays's Grave:
    height fractal: Barren Rock
    colour fractal: Rock
    seed: 3667208111
Shifu b d:
    height fractal: HillsNormal
    colour fractal: Rock
    seed: 1763612033
Shifu b d 1:
    height fractal: Asteroid
    colour fractal: Asteroid
    seed: 1259787947
WARNING: ship varada discarded, because there are no hyperspace routes available for it
DEBUG: Jumps since warranty: 0
Warranty expires: 14:35:20 28 Aug 3230
Segmentation fault
`

__My pioneer version (and OS):__
Mint Cinnamon 20.1
20210513 (0c84df0)

**Comment by Web-eWorks** [comment] 2021-05-27 22:53
CC @Gliese852 - this looks like another one of the plethora of hyperjump issues you're experienced at resolving.

**Comment by Web-eWorks** [comment] 2021-07-22 21:57
I was unable to reproduce this with the current `master` branch. Going to mark as fixed due to the number of changes since 20210513.

**Closed by Web-eWorks** 2021-07-22 21:57 UTC
