### ISSUE TITLE
Mounting guns misaligned

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3311] opened 2015-01-09 21:34 UTC
![screenshot-20150109-001142](https://cloud.githubusercontent.com/assets/1334989/5687500/0e51ee34-982c-11e4-84b6-7cd3f0879cb8.png)
![screenshot-20150109-173815](https://cloud.githubusercontent.com/assets/1334989/5687502/16241ee8-982c-11e4-8629-9a3405c49f46.png)

It happens in most of the ships with "tag gun points".

On ships without "tag gun points", everything works ok until the game is saved. When retrieving the game, there are no projectiles, but the shots were heard.

**Comment by walterar** [comment] 2015-01-09 21:41
I understood that on the ships without "tag points", the default shot line must be the longitudinal axis of the ship?

**Comment by impaktor** [comment] 2015-01-09 23:08
I think this is a double of an issue gernot opened a few years ago. Can't find it now. Perhaps I closed it recently in one of my cleaning sprees.

**Comment by nozmajner** [comment] 2015-01-10 00:05
As far as I know, the default is the ship center for this, if there's no tag on the model.
Although it looks like these shots on these images are aligned properly, but the scale of the projectile is off. 
Both of these ships have their cannon tag towards one side. Amphiesma, Mola Mola, DSminer, Storeria, Nerodia, and a couple of other ships have them in a similar way if I remember correctly.
The sinonatrix on the above pic seems to have a dual blaster, which is problematic in every case because as far as I know, the twin shots are generated relative to the gun tag, with an offset for each side. And it seems that their center lines up nicely with the gun on the model.

**Comment by walterar** [comment] 2015-01-10 14:01
@impaktor  @nozmajner 
There are two different issues here. Both serious.
I just opened 3313 to see, in detail, the other problem.

**Closed** 2015-01-12 17:12 UTC

**Comment by walterar** [comment] 2015-01-12 19:10
@fluffyfreak 
This has not yet been resolved. It is different from #3313. This affects the ships "with" gun_tag. The shots they deviate and is very easy to see.

**Comment by nozmajner** [comment] 2015-01-12 19:20
How they are deviate? 
Neither of these ships have their guns on their longitudinal axis, but towards the side. Those pictures are showing them in their correct position (apart from the twin gun issue of course, but the center of the two shots do line up with the cannon as it should).

**Comment by walterar** [comment] 2015-01-12 19:28
Any player can see that what you say is wrong. You, do not play this game. With guns pointing every which way, it is impossible to hit the target. Try playing the game.

**Comment by nozmajner** [comment] 2015-01-12 19:39
Wow. This is pointless.
http://en.wikipedia.org/wiki/Perspective_(visual)
![screenshot-20150112-203125](https://cloud.githubusercontent.com/assets/4182678/5709517/d794799a-9a9a-11e4-8dea-239e75d37b83.png)
![screenshot-20150112-203136](https://cloud.githubusercontent.com/assets/4182678/5709521/dea4e224-9a9a-11e4-9fce-ccb4768d401b.png)
![screenshot-20150112-203539](https://cloud.githubusercontent.com/assets/4182678/5709524/e27e1e24-9a9a-11e4-87a1-48e807394258.png)
![screenshot-20150112-203550](https://cloud.githubusercontent.com/assets/4182678/5709528/e7a4cf7e-9a9a-11e4-9333-c19f3fb1d8e6.png)
![screenshot-20150112-203559](https://cloud.githubusercontent.com/assets/4182678/5709531/ee224598-9a9a-11e4-91c6-aefa36441319.png)

**Comment by walterar** [comment] 2015-01-12 20:22
You're good to argue with papers, but with the help of wikipedia, you never get to Elite. :)

Nor is it yet resolved the issue with dual guns.

The code that handles gun_tag is broken.

**Comment by nozmajner** [comment] 2015-01-12 20:40
See that faint line in front of the Pumpkinseed? I just put that on the model. There's one for the gun tag orientation (straight ahead) and one from the origin of the ship, straight ahead:
![screenshot-20150112-213537](https://cloud.githubusercontent.com/assets/4182678/5710530/50560576-9aa3-11e4-9fb3-4fd6295b9a05.png)
![screenshot-20150112-213556](https://cloud.githubusercontent.com/assets/4182678/5710532/54ba3a60-9aa3-11e4-89c0-ce15b6960c39.png)
![screenshot-20150112-213603](https://cloud.githubusercontent.com/assets/4182678/5710536/58906718-9aa3-11e4-8935-4b1909b9261b.png)
And if you'd read carefully what I wrote, you would note that I did said that the dual gun stuff is broken, but that has nothing to do with the gun tag alignment.

**Comment by walterar** [comment] 2015-01-12 20:56
Now I understand why people do not report problems. Instead of solving them, invest your time to prove that all is well. Keep it up.

**Comment by fluffyfreak** [comment] 2015-01-12 20:59
@walterar what are you on about? @nozmajner has just shown you that it is doing exactly what you say it isn't.

**Comment by nozmajner** [comment] 2015-01-12 21:02
You know it's a bit strange to have this one sided argument, where I'm the only one arguing. You said something.
I said it seems good to me, but I asked you to elaborate. 
You responded that I'm not playing the game (I could say yes, because I'm too busy contributing to it, but surprise, I do play the game). 
I tried to illustrate that it seems good to me. Two times actually, but I could also give you that model shoots straight in the direction where it should, if you want. 
You never even tried showing what are you talking about, apart that two screenshots which doesn't actually show anything.

**Comment by walterar** [comment] 2015-01-12 21:08
As you wish. I already lost too much time trying to make them understand what I am experiencing in practice with my module combat. I will see how I solve this.

**Comment by laarmen** [comment] 2015-01-12 21:30
@walterar, please try to refrain yourself from being what comes across as condescending. You give out a distinct impression of thinking that somehow our work on Pioneer is your due. I know for a fact that when one expresses oneself in a foreign tongue, especially one having a way to express nuances that is way different than what is used in Latin-languages grammars, it is easy to convey a tone that isn't the one originally intended.

Furtermore, we all come from different countries and cultures, and thus all have different standards regarding what is acceptable in a discussion. In France we *love* arguing, so as long as you bring something to the discussion you can be as abrupt as you want, but I know it isn't the case in other countries. We should try to keep things as civil and cordial as possible, since it is easier to get used to such a tone than the other way around.

Cheers!

**Comment by walterar** [comment] 2015-01-12 21:56
@laarmen 

Thanks for the advice. I'm trying to warn you that it is burning them home. But they do not understand me. Sorry.

**Comment by fluffyfreak** [comment] 2015-01-12 22:05
Correct, we do not understand, that's why nozmajner is trying to find out what the problem is and you are being rude and unhelpful!

You spent a lot of time attacking me when I was spending HOURS of my time trying to fix the issue that you reported and it annoyed me. Please, your bug reports are good for the game but please stop being so rude to the people who are making this game and trying to fix the bugs you're reporting.

**Comment by walterar** [comment] 2015-01-12 22:29
I have also spent many HOURS, DAYS, MONTHS AND YEARS, testing your works. Merged in the master without you tested.

**Comment by nozmajner** [comment] 2015-01-12 22:40
@walterar Please stop. You are being malicious and you do nothing but namecalling. This conversation won't get us anywhere.

**Comment by walterar** [comment] 2015-01-12 22:45
Done. Ship.cpp modified, and put ALL ships with weapons in default position. Problem solved. You will see the difference when you see them fight.

Thanks for everything.

**Comment by fluffyfreak** [comment] 2015-01-13 07:14
@walterar no-one has said the bug doesn't happen, @nozmajner has simply posted that he cannot get the same results as you. In other words we cannot understand **how** you get the bug to happen.

The description you posted doesn't tell us the steps that are needed to repeat the bug, do you understand? If you don't tell us how to repeat the bug then we cannot fix the bug. 

Instead of telling us how to repeat it you've just spent the whole time insulting us and claiming that we ignore the bug. We're not here to ignore the bug, we just can't see the bug.
