### ISSUE TITLE
Disapearing Fuel after save and load

### ISSUE THREAD

**Issue by Olbirion** [pioneerspacesim/pioneer#5534] opened 2023-02-08 21:28 UTC
### Observed behaviour

With the 03/02/23 build, I sometimes lose all the fuel in my cargo after saving and loading a game in space.
Happens randomly around once an hour.

Last time it happened :
- it was with a Coronatrix (30t space, 16t max cargo):
- I started a mission with 23t fuel + 24t equipment + 6t hydrogen in cargo (max cargo of 6t)
- I made a 2t jump
- i checked my ship info and it was as intendeded : 4t hydrogen in cargo

Then save -> quit -> load : now my cargo appears empty and my max cargo is 2t (equipment list still shows 24t of equipments)

### Expected behaviour

Cargo content should not change after save/load.

### Steps to reproduce

Hard to say. When it happens and I have a save just before the jump I can reproduce it again and again.
But it does not happen every time.

See attached saves : 
- Landed 2 - Depart : before take off and jump
- mission 1 : after 2t direct jump to Doligray system & save

__My pioneer version (and OS): last relaese, 03/02/23 on windows 11
[saves.zip](https://github.com/pioneerspacesim/pioneer/files/10689985/saves.zip)

**Comment by RaulMarq** [comment] 2023-02-21 18:56
I can confirm the same thing is happening to me in the latest master build, [50b28e3](https://github.com/pioneerspacesim/pioneer/commit/50b28e3ce4cca7db3b758aabf1bbb537ffd78f6c). I had 12t of hydrogen in my Coronatrix's cargo hold when I made the jump into this system, but I just went to manually refuel a couple of minutes ago and all of a sudden my hydrogen was gone, and I only have 7t of cargo space even though the cargo is supposedly empty.

**Comment by yump** [comment] 2023-03-30 15:22
I hit this too.  Ship has 3t of ghost mass in it.  I don't have a save from just before the corruption, but I can reproduce with OP's "Landed 2 - Depart" save.  It turns out the corruption is observable without a save/load cycle. 

In the dock, the ship information screen shows "Cargo space used: 0t (0t free)", even though there are 6t of Hydrogen on board.  After jumping to Doligray, it shows "0t (-4t free)".

In the lua console, before the jump

```
>Game = require "Game"
>print(Game.player.totalCargo, Game.player.usedCargo)
0 0
```
And after...
```
>print(Game.player.totalCargo, Game.player.usedCargo)
0 4
```

**Closed** 2023-10-08 17:14 UTC
Labels: Unexpected behaviour
