### ISSUE TITLE
Cockpit model occasionally becomes glued to the view at a random angle

### ISSUE THREAD

**Issue by MirceaKitsune** [pioneerspacesim/pioneer#5621] opened 2023-09-05 12:45 UTC
At random times the 1st person cockpit model becomes glued to the view at a bad angle: It will always rotate with the view instead of the ship, meaning middle-mouse-button dragging can no longer be used to look around inside it... further more it's badly rotated so you're stuck looking at the chair or window and can't even see outside any more. Fortunately the issue can be resolved by saving and reloading your save.

![Screenshot_20230905_024853](https://github.com/pioneerspacesim/pioneer/assets/825418/bb77c02e-d66c-4da8-8a1c-9b91aa468381)

I don't yet know what exactly triggers this behavior, only that it happens rarely but does on occasion. I believe someone on Discord suggested it may be related to pausing / unpausing the time.

I observed this behavior both in the newest Pioneer release (20230203) as well as latest Git master. I'm running / compiling it on Linux (Manjaro). AMD graphics card using the default amdgpu driver.

**Comment by Max5377** [comment] 2023-09-13 11:22
Always occurs if you press `Debug Info` button in pause menu, but stops if you then pause and unpause. Also, cockpit rotation doesn't update while in pause menu.

**Comment by Max5377** [comment] 2023-09-16 11:26
This happened, because in this line in `void ShipCockpit::Update(const Player *player, float timeStep)` in `ShipCockpit.cpp`:

`vector3d rot_axis = cur_dir.Cross(m_dir).Normalized();`

If cur_dir == m_dir, `Cross` function would return zero vector, which can't be normalized.
To easily reproduce this behaviour:
1. Load Save;
2. Your game should be paused now, don't rotate camera;
3. Unpause the game;
4. Cockpit becomes glued, which can be fixed only if your reload save or just uncheck/check cockpit option in the pause menu.

The solution is to create new variable `vector_cross` and then check it's length. If the length is zero, don't normalize it, instead 
just assign cur_dir to rot_axis:

```
// For yaw/pitch
vector3d vector_cross = cur_dir.Cross(m_dir);
vector3d rot_axis = cur_dir;
if (vector_cross.LengthSqr() != 0.0)
{
     rot_axis = vector_cross.Normalized();
}
```

**Closed** 2023-10-06 23:28 UTC
Labels: Unexpected behaviour
