### ISSUE TITLE
Bulletin Board - Fast-forward generates similar missions on same destinations

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5187] opened 2021-05-16 11:48 UTC
### Observed behaviour
Fast forwarding has generated the second half of listed missions in the screenshot. 
Some of the missions are same type and destination, still different in payment and number of elements ( i.e. fuel needed or crew mobility).
![issue generated missions](https://user-images.githubusercontent.com/84130826/118395867-36b70d00-b67f-11eb-927b-eebb6c1a173d.png)
### Expected behaviour
It is of course convenient to earn multiple amounts of money going to the same place :) , but the pseudo-redundantly generated missions are probably unwanted behavior.

### Steps to reproduce
fast forward time in bulletin board

__My pioneer version (and OS):__
20210205
Mint Cinnemon 20.1

**Comment by impaktor** [comment] 2021-05-17 11:56
So is this specifically about the red icon missions? There can not be more than one emergency per system?

Not sure I see a bug here. 

@clausimu this works as you intended the Search And Rescue missions? If so, we can close this.

**Comment by Web-eWorks** [comment] 2021-05-17 12:58
I believe the unintended behavior is mostly the high concentration of search and rescue missions, although this might be a starport such that the other mission types don't have good targets to generate nearby. Ultimately this is the correct behavior, adverts are supposed to regenerate over time and there is no particular concern as to how (or how well) it covers the "surrounding space".

**Comment by impaktor** [comment] 2021-05-17 13:24
Right, I'll consider nerfing the spawn rate some, if it's generating too quickly relative to the others

**Comment by impaktor** [comment] 2021-05-17 18:16
OK, I've considered it, and I'm not going to spend any time on this -> closing.

**Closed by impaktor** 2021-05-17 18:16 UTC
Labels: Unexpected behaviour
