### ISSUE TITLE
crash upon saving or hyperspace arrival after assassination

### ISSUE THREAD

**Issue by YinYin-Falcon** [pioneerspacesim/pioneer#2149] opened 2013-03-11 14:44 UTC
Whenever I successfully assassinate someone the game always crashes upon either saving or arriving somewhere from hyperspace. (Somehow cannot make screenshots of the game)
In effect I cannot play as a bounty hunter.

**Comment by laarmen** [comment] 2016-05-25 10:26
I dunno about the original problem, but the stack trace in the screenshot is a duplicate of #3704. Between that and @impaktor comment, I'm closing this.

**Closed by laarmen** 2016-05-25 10:26 UTC
Labels: Crash or hang
