### ISSUE TITLE
Autopilot Crash Bug

### ISSUE THREAD

**Issue by TheNumber5** [pioneerspacesim/pioneer#4071] opened 2017-08-10 13:48 UTC
Recently, i have upgraded to the newest Pioneer version, after 3 hyperspaces, the autopilot crashes the game around 2.40 AU, AND ITS ANNOYING...
I hate the game now... cant do anything but CRASH...
Specs
-CPU:Intel Celeron N2840N
-GPU:Intel HD Graphics 3000 Mobile
-RAM:4 GB
-HDD:500 GB
Settings:
Planet quality, City & Fractals quality:
DOES NOT WORK EVEN ON VERY LOW.
Antisotropic filtering:On
On 800x600
VSinc:Off
Help me...

Observed behaviour
Autopilat crashes the game near any planet

Steps to reproduce
-Start the game
-Start on any planet
-Hyperspace 3 times (you may need more fuel)
-Try to land on a planet with autopilot
-Feel the pain...

__2017,04.17 Version, Windows 8.1 N__

**Comment by nozmajner** [comment] 2017-08-10 14:12
This seems to be similar to #3996, which is already fixed on master. A new release shouldn't be too far out hopefully, but there are some kinks that need ironing out.
Try [this build](https://www.dropbox.com/s/kz34twd1kg5y6o5/pioneer_frommaster.zip?dl=0) from master, and check if it still chrashes.

**Comment by TheNumber5** [comment] 2017-08-13 15:50
Still... nothing. :(

**Comment by el-Bundinio** [comment] 2017-08-18 20:51
Start from earth, jump to Groombridge 34 (0, -2, 1), set autopilot, watch game crash @ 3.07 AU from target unless you're looking at some other screen such as personal info - Economy & Trade only for it to crash as soon as you try to set autopilot.

Looking out back of ship - crash.

Windows, build 10270813, Intel IGP (tested with everything "very low" or "off" except nav tunnels, speed lines, HUD trails, compact radar) starfield 0%

I found this crash in a different ship, tried disabling graphics features that I'm not sure are supported on intel and finally tried again with the standard start ship.

Just tried again with graphics detail maxed out and game crashed @3.08AU this time.

**Comment by el-Bundinio** [comment] 2017-08-18 21:16
Win10, build 20170813, Intel IGP.

start Sol
Fly Groombridge 34 (0,-2,1)
Set autopilot for Salonen or Austinville
Observe crash ~ 3.07AU from target.

Crash can be avoided (temporarily) by looking at any page of 2D graphics such as the refuel page while the autopilot works, but switching to world view to request docking clearance or restart autopilot crashes the game. I tried all graphics setting min / off including HUD e.t.c. and max / on and it makes no difference to the 3.07AU crash.

**Comment by macksting** [comment] 2017-08-25 19:24
Just tested in April build in lubuntu 16.04. Attempted to dock. Ran out of fuel on braking toward Austinville, and there were a few little pauses because my computer's being a butt today, but there was no game crash (nor, for that matter, lithobraking.)
Restarted at Sol, autopiloting to vicinity of Salonen. Successfully docked at Austenville (very low on fuel, of course.)

lubuntu 16.04, build 20170415 (41a0f4c)
Radeon R7 250

Attempting same, per el-Bundinio's procedure, in a recent build. Autopiloting seems to have improved significantly; only down to 20% fuel. However, it means I still haven't replicated the crash. Have attempted both "Dock at Station" (Austinville) and "Fly to Vicinity of Salonen."
Maybe it's an nvidia thing?

**Comment by TheNumber5** [comment] 2017-08-25 19:27
I have intel HD 3000 mobile (dont laugh at me :P)
So maybe its not something related to nvidia...

**Comment by macksting** [comment] 2017-08-25 19:29
Can't speak for everybody else, but I ain't laughing. Thanks for keeping touch! My failure to replicate only complicates matters.

**Comment by jaj22** [comment] 2017-08-25 20:29
I couldn't replicate the crashes, and the description sounds more like a rendering than an autopilot problem. The autopilot doesn't care which page you're looking at.

@TheNumber5 and @el-Bundinio : Which exact GPUs do you have? Best to give the CPU model. I have a few different Intel GPUs to test here.

**Comment by TheNumber5** [comment] 2017-08-25 20:31
@jaj22
Intel HD Graphics 3000 Mobile
DirectX 11, installed visual studio 2017 C++ components a week ago (official microsoft version)

**Comment by fluffyfreak** [comment] 2017-08-26 12:56
@TheNumber5 is this a downloaded version of Pioneer or do you compile it yourself? Because the  DirectX / MSVCP140.DLL shouldn't matter if it's the downloaded build.

How much ram do you have in that machine?

If you look in "My Documents" there should be a "Pioneer" folder with two files called `opengl.txt` and `output.txt`. Could you **reproduce the crash** and upload them or use https://pastebin.com/ to share their contents with us please?

Once you've uploaded the `output.txt` you can also try this:
Also in that folder there will be a `config.ini` file where we store Pioneers settings.
At the top of that file there will be a line saying `AMD_MESA_HACKS=0` you can try changing that to `AMD_MESA_HACKS=1`. There is another setting `EnableGPUJobs=1` that you can try setting to 0 as well to see if that helps.

**Comment by Web-eWorks** [comment] 2020-11-07 16:56
Unfortunately as this issue is three years old and there is no actionable information (savefiles, callstacks, etc.) I'm going to have to close it. If you can replicate this behavior in current `master` build, please open a *new* issue with your `output.txt`, thank you!

**Closed by Web-eWorks** 2020-11-07 16:56 UTC
