### ISSUE TITLE
commandline: ./pioneer -h or ./pioneer -v provides no output on windoze

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#5276] opened 2021-09-23 18:36 UTC
related to #5274 ?

git 2021-09-23
winblowz x64

**Comment by The-EG** [comment] 2021-09-23 20:33
Due to  #4890

**Comment by Web-eWorks** [comment] 2021-09-24 09:04
Unless you are willing to put in the effort to dynamically discover whether stdout is available (and add that function for all platforms to the OS namespace), I'm probably going to close this issue as intended behavior. Throwing an exception every time we try to log a string is too much runtime overhead, so writing to stdout is statically disabled on Windows.

**Comment by joonicks** [comment] 2021-09-24 12:50
also consider this before abandoning lua debug output on windows:

windows players who encounter problems will provide output.txt vastly different from linux players. and adding debug statements that trigger in linux wont be visible in windows.

**Comment by Web-eWorks** [comment] 2021-09-24 21:06
@joonicks *all* debug output from Pioneer is logged to output.txt and the in-game console. In fact, there is some debug output that is only logged to output.txt because it is too verbose to be logged to the console. The only difference between linux and windows when it comes to debug output is that stdout is not an *additional* output sink for debug information on windows.

**Closed by Web-eWorks** 2021-09-24 21:06 UTC

**Comment by joonicks** [comment] 2021-09-24 22:02
From BreakDownService.lua (initial offering bbs dialog):

		print(('DEBUG: %.2f years / %.2f price = %.2f'):format(ad.strength, ad.baseprice, ad.strength/ad.baseprice))

no such output.txt lines can be found in windows

**Comment by Web-eWorks** [comment] 2021-09-24 22:12
Hmm... I distinctly remember re-implementing `print()` to use our logging system, but looking back through the code it may not have been merged. Will open a new issue related to that, thank you for pointing that out.
