### ISSUE TITLE
Can't sell 1MW Pulse Laser mounted on a SINONATRIX

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4702] opened 2019-10-10 15:07 UTC
OS: Independent
Version: 2019-10-09 & 2019-02-03

It's not possible to remove that weapon, there for a different one can't be mounted.

And sorry say this, but that weapon is useless. 20 minutes continuessly fighting a pirate ( mouse controlled ) and just two accounted hits to the enemy. For godsake he had the same bad weaponry :D

**Comment by craigo-** [comment] 2019-10-12 08:51
My initial guess is that you are currently docked at a location that doesn't have a tech level high enough to buy/sell that particular item. The Equipment Market screen only shows your ship's *sellable* equipment. This is not a complete list of all of your ship's equipment; it only shows those items up to a tech level that starport supports. For example, London (Tech Level 3) does not show a starting Sinonatrix's Class 3 Hyperdrive. For a complete list of ship equipment, see the Ship Information screen.

Have a look at [this PR](https://github.com/pioneerspacesim/pioneer/pull/3505) for a bit of background (not sure if the data there is current).

I just fired up a new game at Mars with a Sinonatrix on the following Pioneer versions (on Windows), and was able to sell the Sinonatrix's fitted 1MW Pulse Laser at both Cydonia (Tech Level 9) and London (Tech Level 3):

- Pioneer (commit 4701592) - Release x64
- Pioneer 20190203 (latest release)

Re: your comment about the fitted pulse laser being useless... Well, yes. It kind of is, until you get to the point where you [know](https://www.youtube.com/watch?v=i__2Q-pQRGY) [how](https://www.youtube.com/watch?v=ZsVU4L6WfJU) to use it. I'm not there yet! Which is why I'm more of a space-based APC, ferrying high-risk passengers between systems most of the time. My suggestion: try the new [beam lasers](https://www.youtube.com/watch?v=m7iFiMBcchY).

**Comment by Cyborgscode** [comment] 2019-10-12 10:22
It's not a tech level problem : This station has military level and you still can't sell it:

![Pioneer sellingbug](https://user-images.githubusercontent.com/8317797/66699876-eb8e8880-ecea-11e9-9455-1c1bc5621a8d.jpg)

**Comment by craigo-** [comment] 2019-10-12 11:33
Does the laser show up under Ship Information? Wondering if it has maybe been destroyed..? You did say you experienced prolonged combat... I know when a hyperdrive blows up (because it's not been serviced), it becomes its weight in rubbish...

![image](https://user-images.githubusercontent.com/4467963/66700732-78b7f880-ed50-11e9-8e0e-3b0fd2a730dc.png)

I count 18 tons of listed equipment on that screen, and 35 tons used total... Does that look right to you, e.g. 17 tons of cargo? Any of that rubbish?

If you start a new game on Mars, can you sell the laser?

**Comment by robothauler** [comment] 2019-10-12 11:59
I think this is related to #4675

**Comment by Cyborgscode** [comment] 2019-10-12 13:55
I checked it. 

Seeling the laser is working in a fresh game on mars.
There is no rubbish in cargo.
The Laser is working :)
Cargo is 13t for fuel.

**Comment by impaktor** [comment] 2019-10-12 20:09
So summary thus far: it's unclear how to reproduce the bug?

**Comment by Cyborgscode** [comment] 2019-10-12 21:03
You can use these:

[savefiles.tar.gz](https://github.com/pioneerspacesim/pioneer/files/3721149/savefiles.tar.gz)

In another bugreport i talked about error handling/resiliance against bugs, this is another case. The readin savefile has to be checked, if it's content is correct and consistent.

**Comment by nozmajner** [comment] 2019-10-12 21:24
@craigo- Equipment can't be damaged. Only the hyperdrive does that if you doesn't take care of it.

**Comment by craigo-** [comment] 2019-10-12 22:09
@nozmajner: OK, good to know.

**Comment by vakhoir** [comment] 2020-01-27 20:41
I think I ran into this myself at one point. I won't be able to find the cause today, but it seems like it's a bug in the `Ship:CountEquip(item, slot)` function. It's returning 0 even though the laser is equipped.

**Comment by Web-eWorks** [comment] 2020-12-01 19:20
Closing this as a duplicate of #4803, as it's caused by the same root issue.

**Closed by Web-eWorks** 2020-12-01 19:20 UTC
