### ISSUE TITLE
MacOSX Download

### ISSUE THREAD

**Issue by darren77** [pioneerspacesim/pioneer#3921] opened 2017-02-08 07:22 UTC
Looks like an excellent game, thank you :)

### Observed behaviour
I have build 20160330 31/3/2016 but when selecting and performing a mission no one collects my delivery and payment is not received by the date specified for that mission.  I have tried multiple missions and waited for about 14 days later but no one takes my delivery.

I also noticed that the downloads showing on the website http://pioneerspacesim.net/download show that Linux and Windows were last update on 29/11/16 but Mac OSX is last updated 31/3/2016.

1) Is there plans to update the Mac OSX copy? 
2) Does the updated copy allow for missions to receive payment?

**Comment by impaktor** [comment] 2017-02-08 08:37
HI!

1. Mac builds are made when people (read: players) give us a binary build of our master. We (read: developers) don't have access to any Mac to build it on.

2. Most likely you must be doing something wrong. Is this package delivery? Are you sure you're at the right system? System names are not unique. Do you see the package in your manifest? Once date has passed you should get a "failed" message, possibly next time you dock. (The code that checks if you pass or fail is run when docking, if I remember correctly).

**Comment by fluffyfreak** [comment] 2017-02-08 12:02
@salborrelli if you're still around it'd be great if you can take a look at this. There's been a lot of optimisations and other work done lately but the existing XCode version seems a bit broken.

**Comment by salborrelli** [comment] 2017-02-08 17:17
@fluffyfreak @impaktor Hi guys yes I'm still around and will take care of updating the Mac package as son as I have a bit of time. I know I've not been actively participating to the project for a while, the reason for this is two-fold:

1. a chronic lack of time due to work commitments (I'm sure you know what I mean 😃 
2. an apparent lack of "things to do" on the C++ side, as after looking at the code in a certain depth I realised that most of the important things are basically written in Lua, a language that I have no wish at all to spend time on. I might be wrong of course but again the lack of time does not allow me to expand on this aspect beyond a given extent.

Will get back to you as soon as I have the new version of the install package for Mac ready.

Sal.

**Comment by fluffyfreak** [comment] 2017-02-08 17:41
@salborrelli I tried to fixup the XCode package a bit earlier and noticed a few things could do with fixing so opened #3922

I think the Assimp version needs updating from 3.0.0 to 3.2 as well as it has some API changes and fixes.

**Comment by salborrelli** [comment] 2017-02-16 18:17
@fluffyfreak @impaktor Hi guys, while working on the new version of the install package for Mac I've incurred in a strange compilation problem. As you can see from the attached screenshot, the LineProgram class (.../src/graphics/opengl/LineMaterial.h) refers to a parent constructor that doesn't seem to be defined by the parent Program class  (.../src/graphics/opengl/Program.h). I have also checked the latest version of the file directly on GitHub, just to make sure it was not a revision problem, but the only constructor that seem to be defined by Program is still:

`Program(const std::string &name, const std::string &defines);`

without the third boolean parameter, that is.

What am I missing? Can you please help me figure out the cause of this problem?
![screen shot 2017-02-16 at 19 00 37](https://cloud.githubusercontent.com/assets/1098233/23034404/0433673a-f47c-11e6-8f05-04a86e4f97d0.png)

**Comment by fluffyfreak** [comment] 2017-02-16 19:43
I don't think that LineMaterial/LineProgram is actually used anywhere.

**Comment by fluffyfreak** [comment] 2017-02-16 19:48
No it isn't, i'm doing a PR to remove it right now. @salborrelli you can safely ignore it, it'll be gone from master in a few minutes!

**Comment by salborrelli** [comment] 2017-02-17 17:32
@fluffyfreak thank you Andrew, I can build without problems now.

**Comment by fluffyfreak** [comment] 2017-02-18 15:30
@salborrelli how do you create an installPkg from the XCode build?

Would you mind creating one?
Would you have time to document how to do it?

I realise that somewhere in these issues/forums/PR's you have done this before but I cannot find the instructions :(
I apologise for that!

**Comment by fluffyfreak** [comment] 2017-02-18 15:31
I did find [this information](https://github.com/pioneerspacesim/pioneer/issues/3401#issuecomment-109628926) but it's part of a cmd line build script.

**Comment by salborrelli** [comment] 2017-02-19 11:26
@fluffyfreak No problems at all I had already planned to create the new install package at the first suitable moment (most likely tomorrow). Will share the link for you to download the package as soon as it's ready.

**Comment by salborrelli** [comment] 2017-02-20 11:48
@fluffyfreak @impaktor Here you are the latest install package for MacOS X:

https://drive.google.com/open?id=0B3YT4wkIA2jjY2xUd1pXM3dMYVE

Let me know if everything works fine with it.

**Comment by fluffyfreak** [comment] 2017-02-20 17:50
@darren77 latest OSX build is now uploaded to sourceforge! https://sourceforge.net/projects/pioneerspacesim/files/

Thanks @salborrelli how do you build the installPkg files? Is the XCode project supposed to do that automatically or is it something you have to do?

**Comment by salborrelli** [comment] 2017-02-21 09:06
@fluffyfreak nope I use Xcode for building the App only, and although building the package from Xcode is of course possible, personally I prefer to go with the `productbuild` command line tool instead.

Note that I have no problems in maintaining the Xcode project up to date and generate the MacOS X install package every now and then. And who knows, maybe one day I'll find something interesting to do on the C++ side too, along with the time to do it :)

Do you have a predefined time frequency (e.g. once a month, etc.) for generating the next install package for any given OS? If not you can just send me a message when you need a new package and I'll build it at the first free moment.

**Comment by fluffyfreak** [comment] 2017-02-21 16:36
@salborrelli there's no fixed schedule as such but it would be good to do one each month (_last day or 1st_) since OSX has been so neglected for releases this last year.

I think we could give you upload privileges on sf.net so you wouldn't need to get one of us to do them.
If you're interested?

**Comment by salborrelli** [comment] 2017-02-21 17:54
> I think we could give you upload privileges on sf.net so you wouldn't need to get one of us to do them.
If you're interested?

Sure thing ... I'll build and publish a new release at the beginning of each month, starting from March 1! I'm also thinking of taking this occasion for upgrading the Assimp library to the latest version as you requested in a previous post.

**Comment by impaktor** [comment] 2017-02-22 10:06
Sounds like this is fixed now. Conversation can of course continue if need be.

**Closed by impaktor** 2017-02-22 10:06 UTC

**Comment by fluffyfreak** [comment] 2017-02-28 10:23
@salborrelli do you have a sourceforge.net account and username? If so then I can add you.

**Comment by salborrelli** [comment] 2017-02-28 12:05
@fluffyfreak just created my SourceForge account, my username is (you bet :) salborrelli

**Comment by fluffyfreak** [comment] 2017-02-28 14:19
Ok, I've tried to set it as a developer account, and modified those to have create and update. 
Let me know if you can upload a build next time you do one :)

**Comment by salborrelli** [comment] 2017-03-01 11:36
@fluffyfreak I am ready with a new version of the install package for MacOS X. Unfortunately I cannot upload it to SourceForge because, although I can access the file browser, there is no "upload file" command of sort for me to use at the moment (see screenshot below)
![screen shot 2017-03-01 at 12 34 57](https://cloud.githubusercontent.com/assets/1098233/23458215/8d57d1fa-fe7b-11e6-8109-689e95bbaf68.png)

**Comment by fluffyfreak** [comment] 2017-03-01 11:49
Ok, I've made you a full admin on the page :)

**Comment by salborrelli** [comment] 2017-03-01 16:20
Thank you and I've just completed the upload of the latest install package.

**Comment by fluffyfreak** [comment] 2017-09-07 10:35
@salborrelli I hear that you're job is changing and thus you can no longer maintain/upload MacOS builds for us. Thankyou for all of the builds and time that you've put into the project. I wish you luck in the future and hope that you still enjoy the game! 😄

**Comment by salborrelli** [comment] 2017-09-07 11:51
@fluffyfreak yup I'm in the process of switching to another company where I'll mostly be working on Unix systems, so no Mac programming anymore for the time being. Sure I have a PC at home but I don't like developing on Windows platforms ... it goes against my own ethical principles 😎
