### ISSUE TITLE
Camera position wiggles spasmodically in particular system

### ISSUE THREAD

**Issue by yump** [pioneerspacesim/pioneer#3800] opened 2016-08-26 09:20 UTC
### Observed behaviour

The position of the camera rapidly jerks around when the ship is in the Esswaze (-4, -4, 8) system.  The effect is most visible when landed, or when the external or sidereal views are used with a close zoom.  If other systems are affected, I haven't run into one yet.
### Expected behaviour

The position of the camera does not wiggle when the ship is in the Esswaze (-4, -4, 8) system, or any other system that shares whatever underlying characteristic causes this.
### Steps to reproduce
1. Load [this save file](https://u.pomf.is/rbhhza).
2. Un-pause the game.
3. Press F1.
4. Observe the wiggling.
5. Make a hyperspace jump to some other nearby system, and observe that the wiggling is gone.

The save file is a convenience. I was also able to produce the effect by starting a new game either at Barnard's Star or Earth and traveling directly to Esswaze.

**My pioneer version (and OS):** 20160814-linux64, Fedora 24

**opengl.txt:** [here](http://pastebin.com/pCt1eeY7)

**Comment by nozmajner** [comment] 2016-08-26 10:32
My observation:
That system is quite huge. The starport around the 4th star is 0.29ly (18 339 AU) away from the entry point around the first star. If you jump to the first, there's only a slight wiggle, but if you jump to the 4th, the wiggle is quite much larger. The 3D cockpit doesn't wiggle at all.
When landed, the ship and the whole city wiggles in concert, and that's both visible from internal and external view.
And the orbit map behaves wiggly too.
Nothing's wiggling while paused.
Maybe it's due to the size of the system?

**Comment by yump** [comment] 2016-08-28 00:32
I think you're right about the size of the system.  I just ran into another wiggler, Exphiack (-1,6,-7), and it has a star that's 0.24 ly away from the others.

**Comment by impaktor** [comment] 2016-08-28 07:17
Didn't Barnard's star have some similar issue?
@fluffyfreak ?

**Comment by fluffyfreak** [comment] 2016-09-08 19:15
@impaktor it's interesting and yes it looks like a precision issue somewhere, perhaps in the camera? Hard to say really but I think @johnbartholomew has looked into these things before if he's got any insight?

**Comment by johnbartholomew** [comment] 2016-09-08 19:27
Sorry, I don't have any insight. I agree it's a precision issue but I don't know where in the code the culprit is.

I will note that Google calculator says 0.29 ly is 2.74e15 metres. Double precision floating point only gives around 15 decimal digits of precision. Basically any calculations done on System-relative coordinates are going to break down this far away from the system origin, where even changing the least significant bit represents on the order of a metre of distance.

**Comment by fluffyfreak** [comment] 2016-11-08 14:59
> <FluffyFreak> JohnJ what do you mean by "_The bug is that relative positions aren't supposed to use root coords in cases with shared frames_"?
> <JohnJ> FluffyFreak: Check out Frame::GetPositionRelTo
> <JohnJ> Currently it's just subtracting root-relative coords
> <JohnJ> The commented-out code may not actually work though
> <JohnJ> I'm not sure if I ever tested it

**Comment by jaj22** [comment] 2016-11-19 02:03
Ok, this should fix several issues:
[https://github.com/pioneerspacesim/pioneer/compare/master...jaj22:jitter-fix]

1. The changes in Frames.cpp enable the use of relative positions in cases where the two frames share a near parent. The "relative to child" case is standard for rendering, because the player's ship and the camera are children of the same parent. The other two cases are less important, but apply when two nearby objects are in different reference frames. I tested those by modding the projectiles.

2. The change in Camera.cpp fixes an old bug where interpolated frame coordinates were not used for rendering, causing heavy rendering jitter and frame transition glitches. The easiest way to demonstrate this is to move in and out of one of the far stations' reference frames at Barnard's Star.

3. The change in WorldView.cpp is a workaround for an issue where the player's ship label is placed exactly between the four centre pixels in external view, causing it to jitter.

Note that some jittering is not fixed, by design. Objects that are very far from their frame's centre will still jitter. The external view will also jitter in the same circumstances, because the camera frame and player ship are both children of the same frame. Many HUD elements also jitter badly: I haven't looked into fixing these, as the HUD is being reworked anyway.

**Comment by impaktor** [comment] 2016-11-19 07:50
@jaj22 that's great! You're just one button click away from turning it into a propper pull request. Care to press that green "New pull request" button you should see near the top of your github/pioneer page?

**Comment by impaktor** [comment] 2016-11-22 18:47
closed by #3872.

**Closed by impaktor** 2016-11-22 18:47 UTC
Labels:  CONFIRMED, Unexpected behaviour
