### ISSUE TITLE
Number of buildings in city depends on previously loaded game

### ISSUE THREAD

**Issue by cwyss** [pioneerspacesim/pioneer#4802] opened 2020-02-22 18:29 UTC
### Observed behaviour
The number of buildings around a surface space-port changes depending on games started earlier in the same running instance of pioneer.

### Expected behaviour
Number of building does not change if other games have been started earlier.

### Steps to reproduce

1. Start pioneer and select "Start on Mars"
2. F1-switch to external view, zoom out and observe the number of buildings around Cydonia. (With a setting of `CityDetailLevel=Low` I count 21 buildings)
3. Quit and restart pioneer
4. Select "Start at New Hope" and end this game again (Esc + "End Game"); do *not* quit pioneer.
5. In main menu, now select "Start on Mars" 
6. Switch to external view and again observe number of buildings around Cydonia. I see more than 100 buildings now!

This issue is not limited to Cydonia. I originally observed it at Mariasuriru where I get
- zero buildings when I directly load my savegame after launching pioneer
- around 20 buildings when I first "Start on Mars" and then load the savegame
- more than 100 buildings when I first "Start at New Hope"

Here is the savegame (docked at Mariasuriru): [_quicksave.gz](https://github.com/pioneerspacesim/pioneer/files/4239750/_quicksave.gz)

__pioneer version__
current upstream/master, 20200203 release, and 39ef0e8a2 (dec 1 2019) all have this issue

**Comment by fluffyfreak** [comment] 2020-02-24 21:36
Oh, interesting and wierd bug!

**Comment by joonicks** [comment] 2021-09-23 19:33
this problem persist; however its an indication of a bigger problem: game data isnt reset completely between games

for these drastic changes in building numbers, the galaxy data "population" needs to drastically change.

**Comment by joonicks** [comment] 2021-09-23 19:55
void PopulateStarSystemGenerator::PopulateStage1()
line 1449: 	sbody->m_population += workforce;

PopulateStage1() is called from Apply()
can it be run multiple times....?

**Comment by Web-eWorks** [comment] 2021-09-23 23:53
@joonicks the entire galaxy object and all associated system objects are torn down between games *as far as I remember*. I'd maybe check CityOnPlanet for any static variables that might be persisting across games. Another good way to test would be to use the lua console to check the population variable for the space station.

**Comment by joonicks** [comment] 2021-09-24 00:02
yep, using lua console would be cool. if it worked.

**Comment by Web-eWorks** [comment] 2021-09-24 09:06
LuaConsole works correctly. Console.AddLine is replaced with `print()` - it's logged to `output.txt` and the in-game console.

**Comment by joonicks** [comment] 2021-09-24 12:43
... something something windows

**Comment by joonicks** [comment] 2021-09-24 13:47
verified fixed by #4913

**Comment by zonkmachine** [comment] 2023-06-13 19:11
> verified fixed by #4913

Confirmed. I can't reproduce this on https://github.com/pioneerspacesim/pioneer/commit/0041e9d9218925b2fc85b437738aeb779149208a (or master for that matter).

**Closed** 2023-06-14 15:54 UTC
