### ISSUE TITLE
Opening audio window breaks game

### ISSUE THREAD

**Issue by ProgramRAM** [pioneerspacesim/pioneer#5137] opened 2021-02-04 08:43 UTC
### Observed behavior
Opening the audio tab in the game settings causes the game to severely lag and become borderline unresponsive requiring a force quit to remedy. 

### Expected behavior
Opening the audio tab does not affect performance

### Steps to reproduce
From the main menu or in game simply open the audio tab in settings

__20210203 142693b __Windows 10 Pro 10.0.19042 Build 19042

**Comment by The-EG** [comment] 2021-02-04 11:58
Same as your other issue, I can't reproduce this.

Can you trigger that behavior and then attach output.txt (found in My Documents\Pioneer) to this issue?

**Comment by ProgramRAM** [comment] 2021-02-04 12:03
[output.txt](https://github.com/pioneerspacesim/pioneer/files/5925564/output.txt)
There we go, I booted into an autosave made sure the issue worked and managed to safely exit without having to force quit, the issue did happen again

**Comment by The-EG** [comment] 2021-02-04 12:12
Hm, ok, nothing out of sorts there.

That's an odd one. Nothing really comes to mind, that tab shouldn't be doing anything too different than the other tabs. Out of curiosity, do the other tabs on the settings window work fine?

**Comment by ProgramRAM** [comment] 2021-02-04 20:52
Yes all other tabs work perfectly fine its just the audio one that does this, It happens without fail all the time

**Comment by Web-eWorks** [comment] 2021-02-05 06:33
Nothing that's specifically tied to that particular settings page stands out as a smoking gun. If you could, I'd appreciate a bit more system information:
- What CPU do you have (vendor, model, any overclock?)
- What type of drive is your user folder on? Hard-disk, SSD? What speed is the disk?
- How much RAM do you have?
- When the program freezes, what does the Task manager report it's using in CPU, Memory, Disk?

This is a difficult one to debug, as I've never seen a user with anything even close to this particular issue before. My gut is saying that it might be a disk issue (possibly related to anti-virus) as just having the window open doesn't even touch the Windows sound subsystem and just reads some config variables.

**Comment by ProgramRAM** [comment] 2021-02-05 18:26
Sure heres the info

- i7-9700KF (No overclock)
- NVME SSD
- 32GB 3200Mhz
- 0.1 CPU , 350MB Memory, 0.1MB Disk


I do have an Antivirus running but I don't see any log of it taking action on Pioneer I also went ahead and disabled it and tried again same issue.

**Comment by Web-eWorks** [comment] 2021-07-05 22:47
Closing this one as system-specific; I've not seen any reproductions of the issue across multiple platforms and users.

**Closed by Web-eWorks** 2021-07-05 22:47 UTC
