### ISSUE TITLE
If multisampling is more than 2x I have a black screen.

### ISSUE THREAD

**Issue by SomenameIchose** [pioneerspacesim/pioneer#5719] opened 2024-01-20 10:57 UTC
If I turn on multisampling more than 2x I have a black screen. At the next launch of the game I can hear only main theme and see the mouse cursor that's all.
[output.txt](https://github.com/pioneerspacesim/pioneer/files/13997625/output.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/13997626/opengl.txt)
 #
![12312](https://github.com/pioneerspacesim/pioneer/assets/154741968/69eda329-79f0-4a68-8af1-d4295de4f276)
I tried build 20230203 and auto-commit: translation updates 20240118 both of them have the same problem.

**Comment by Web-eWorks** [comment] 2024-01-20 12:17
Duplicate of #5297 - OpenGL reports a `FRAMEBUFFER_COMPLETE` render target with higher levels of multisampling, but attempting to render to it will fail with an incomplete framebuffer error.

This appears to be a graphics-driver-specific issue (not helped by the fact that you're running extremely old Nvidia drivers); the only workaround at this time is to disable MSAA or use the multisampling level your driver supports.

**Closed by Web-eWorks** 2024-01-20 12:17 UTC
Labels: Rendering

**Comment by SomenameIchose** [comment] 2024-01-20 12:21
> Duplicate of #5297 - OpenGL reports a `FRAMEBUFFER_COMPLETE` render target with higher levels of multisampling, but attempting to render to it will fail with an incomplete framebuffer error.
> 
> This appears to be a graphics-driver-specific issue (not helped by the fact that you're running extremely old Nvidia drivers); the only workaround at this time is to disable MSAA or use the multisampling level your driver supports.

Thank you!
