### ISSUE TITLE
Search&rescue bug - with save game

### ISSUE THREAD

**Issue by sfence** [pioneerspacesim/pioneer#3627] opened 2016-02-24 15:16 UTC
My Pioneer is builded from git: d3eb57e

I have tried fuel and crew rescue missions, but both fails because of transfer problem.
For fuel rescue, game console wrote me that hydrogen miss for transfer. But that time I have 3t of hydrogen in cargo space, ship needed 1t.
And for crew transport on ship. passager transfer failed, because of no aviable space for crew on target ship. Secundary problem was ship location. System orbit view (F6) show the target ship on orbit of sun, instead of planet, where ship was. But, after selecting ship as a target, autopilot works fine. For a situation, it can be helpfull, I have uploaded two saves from crew transport on address: http://147.229.208.36/pioneer/
May be, it will help us to solve the bug. Good luck and thank us for work on this game.

**Comment by clausimu** [comment] 2016-02-24 15:35
Thank you for reporting the bug! I have so far been unable to reproduce it on my system. I will take a look at the save games and hopefully they will allow me to track down the problem. If you can, could you upload a save game where you had an issue transferring fuel as well? Seeing the problem in action is going to be very valuable!

**Comment by sfence** [comment] 2016-02-24 17:01
I'am sorry. I have tried to reproduce fuel problem but without success. But I get to different types of errors. On the same address, files with prafix LANDFUEL and FUEL. First one, LANDFUEL, I am not able to land, to finish transfer. Probably because of terrain profile. Second, FUEL, it looks like game not recognized, I am in transfer area to allow transfer.

**Comment by sfence** [comment] 2016-02-24 17:32
May be, it can be needed information. I am running pioneer under Linux.

**Comment by walterar** [comment] 2016-02-24 22:35
@clausimu This fixes the problem of missing fuel.
```
local cargoPresent = function (ship, item)
-- Check if this cargo item is present on the ship.
   if item.l10n_key == 'HYDROGEN' then
     item = Equipment.cargo.hydrogen
   end
   if ship:CountEquip(item) > 0 then
     return true
   else
     return false
   end
end
```
The reason, Laarmen maybe best explained ;)

@sfence You can send the savegames in zip format?

**Comment by sfence** [comment] 2016-02-24 23:24
@walterar Now you should be able to download a zip archive of all saves from the same address.

**Comment by clausimu** [comment] 2016-02-25 00:29
@walterar - really?? I must be totally on the wrong track then... As far as I understand I am already passing "Equipment.cargo.hydrogen" to the cargoPresent function as "item". If I weren't so, how else would "item.l10n_key" return 'HYDROGEN'? As it is, the (new) first three lines in that function would seem redundant to me...? 

I bow to your wisdom and experience, but I hope you or another expert like @impaktor or @laarmen can help me understand. Failing this function and equipment handling would certainly explain a lot of bugs (although it doesn't explain why only some people experience the bug).

**Comment by walterar** [comment] 2016-02-25 02:36
@clausimu I tested it fully. If we get a saved game that problem you can check.
The Pioneer engine has many things that work well and some do not.
Some things do not survive a saved game; this is a old known bug, but no one fix yet.
In many planets and especially asteroids, is not possible to land; this is something that perhaps nobody ever fix.
Is likely to survive to this if you make a "by-pass", not stopping to wait for someone fix it.

**Comment by walterar** [comment] 2016-02-25 13:56
@clausimu   You can verify what I said with FUEL_save saved game.

Without the patch in cargoPresent, "Comms.ImportantMessage (missingtxt)" shown

With the patch works properly.

**Comment by sfence** [comment] 2016-02-25 15:22
Again on http://147.229.208.36/pioneer/ . NOLAND and PRELAND saves, 

There is a fuel rescue situation with the target ship below terain level.

And DANCING_MOON save... it is a different situation, but same moon... if I do time acceleration it looks from distance between etc 200-500km from moon like mount is steping again and again to bad location and back. May be, only graphic bug.

I think, it is enough material. That I will wait to new version in git to test it again.


Od land_dance.zip archive...

**Comment by sfence** [comment] 2016-02-27 08:46
It looks, like there is bad distance in ly calculation for search&rescue missions from other systems. Do you want the save with it? Bad distance is show when you negotiating about mission accept/refuse on some station.

**Comment by sfence** [comment] 2016-02-27 19:15
i have added HYDROGEN_FAIL save to server. There is a situation with hydrogen trasfer failed, because of hydrogen missing aboard, what is not true.

**Comment by impaktor** [comment] 2016-02-27 19:25
@clausimu  I don't know why walterar's fix would be a fix, unless things are not deserialized correctly, in which case that should go in the deserializer function; or at least that's my quick guess. Don't take my word for it.

I'd advice to sprinkle the code with `asserts()` or if-print statements (maybe prefix your strings with something, to separate them from all other debug printouts), maybe give a copy of that lua-file to players, like @sfence, to test. This of course means they need to tell us/you whatever line the fail happened on. Running pioneer from the terminal helps, as print-statements are then shown.

Sorry, but I don't have time to help for the comming 2-3 months.

**Comment by sfence** [comment] 2016-02-28 10:46
With new build, it looks like landing on moons and ateroids work for the time being. But hydrogen fail transfer ofen interapt refuel mission. If you will be working on fixing hydrogen transfer problem, I think, ships without fuel in other systems or on remote planets/asteroids from travel destination should need more then 1t of hydrogen.

**Comment by clausimu** [comment] 2016-02-28 13:46
@sfence, @walterar, @impaktor - please don't take my relative silence as lack of interest. Work is very stressful at the moment. I'm trying to understand why the fix by @walterar works and will have to step through the script one by one again.
@sfence - I will also consider your other suggestions (deliver more fuel to targets far away from next station, etc.). Just give me a little bit of time. :)

**Comment by fluffyfreak** [comment] 2016-02-28 17:04
No rush @clausimu we all know what real life is like :)

**Comment by impaktor** [comment] 2016-02-28 17:29
> No rush @clausimu we all know what real life is like :)

Something like this:
![skriet](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/220px-The_Scream.jpg)

**Comment by sfence** [comment] 2016-02-29 13:21
Yeah. No rush.

For crew transport to target ship..... with actual build... a few minutes old... branch master
http://147.229.208.36/pioneer/NO_MORE_CREW

**Comment by Emmanuel-F** [comment] 2016-03-27 22:13
Hi, I think I've found a bug in data/modules/SearchRescue/SearchRescue.lua, ligne 580 :
crew_num = crew_num - flavour.deliver_crew
It should be 
crew_num = crew_num - deliver_crew
as the parameter containing the actual number of crew to deliver is deliver_crew. flavour.deliver_crew seems to just be a default parameter, equal to 0.
In my case, a rescue mission where I have to deliver 2 members of crew to ship is impossible to complete because the target ship already have its maximum number of crew (8).

**Comment by Emmanuel-F** [comment] 2016-03-27 23:41
+ in the function deliverCrew (line 1425), the default value for mission.deliver_crew_check is missing and the variable takes the value PARTIAL (no idea why, garbage in memory ?) when a crew member is delivered, thus aborting the mission. Trying to reset the interaction doesn't work as this status is registered in the variable 'mission'.
So this variable should be set to a default at the beginning of deliverCrew, or at least be written in all cases.
I think the same applies to all other mission functions.
Also, closeMission (line 1646) is never called if status is PARTIAL.

And latest point, at line 1625, the check is == :
```
if mission.pickup_comm_check[commodity] == "PARTIAL" then
    done = false
end
```
unlike all other snippets where the check is ~=. That's strange and maybe another bug, but i didn't investigate more in this direction.

**Comment by Hexdump74** [comment] 2016-03-28 17:28
@clausimu I think I found why you don't get the correct hydrogen objet : in the function `createTargetShipParameters`, the `deliver_comm_orig` is set using a COPY of `ad.deliver_comm`, through the use of `CopyTable()`. But then, the cargo content is compared to `deliver_comm_orig` using `Ship:CountEquip()`, which compares the objects by comparing directly the tables (that is, the ADRESSES of the tables). As the object were copied, the adresses aren't the same anymore and the match always returns false.

Here is some code you can insert to observe it :
```
-- Print contents of `tbl`, with indentation.
-- `indent` sets the initial level of indentation.
function tprint (tbl, indent)
  if not indent then indent = 0 end
  for k, v in pairs(tbl) do
    formatting = string.rep("  ", indent) .. k .. ": "
    if type(v) == "table" then
      print(formatting)
      if indent > 5 then 
      	print("table")
      else
      	tprint(v, indent+1)
      end
    elseif type(v) == 'boolean' then
      print(formatting .. tostring(v))      
    else
      print(formatting .. v)
    end
  end
end
```

And in the `deliverCommodity` function : 
```
print("--- Dumping ship content ---")
tprint(Game.player.equipSet.slots)
print("--- End dump ---")
print("--- What is needed ---")
print(commodity)
tprint(commodity)
print("--- End needed ---")
print("--- Extracting ---")
for sname,slot in pairs(Game.player.equipSet.slots) do
	print("Slot: "..sname)
	for iname,item in pairs(slot) do
		if type(item) == "table" then
			print(item)
			tprint(item)
		end
	end
end
print("--- End extraction ---")
```

**Comment by impaktor** [comment] 2016-03-28 17:35
Really excellent work there @Hexdump74!

**Comment by laarmen** [comment] 2016-04-03 18:51
Indeed. However, looking at copyTable(), it seems it makes a shallow copy of the table, which itself contains the proper commodity object.

**Comment by laarmen** [comment] 2016-04-04 08:36
FWIW, I've been working since yesterday on a way to examine the private contents of the loaded modules. There will be some caveats because robn did a damn good job sandboxing everything, and you guys are way too clean in your programming, which means for me it's like trying to get into a room without a door but with a 2-inches wide ventilation shaft. The shaft being optional.

**Comment by Wuzzy2** [comment] 2016-06-26 18:57
This bug is not an illusion, I have suffered it, too.

Almost same situation: I was required to deliver 1t hydrogen to a stranded ship on a planet, I brought 10t hydrogen, found the ship, landed and the game told me the transfer did not work because of “missing hydrogen”. :-(

Here's a save file of just after I've landed. Study the messages carefully:

[SearchRescueFail.zip](https://github.com/pioneerspacesim/pioneer/files/333746/SearchRescueFail.zip)

Pioneer version: 20160614

I think this bug should be high priority because a core feature of the game is broken.

**Comment by laarmen** [comment] 2016-06-26 19:35
Well, about the "priority", two things : for one, the S&R feature is not a
"core" feature, just a really good thing to have. And, also, we are all
volunteers, so we work pretty much on whatever has our interest.

The particular issue with this bug is that it probably occurs during the
serialization, thus providing us with save files will not really help us
figure it out. I'll still check it out whenever I have time, but I wouldn't
hold my breath on that ;-)

**Comment by fluffyfreak** [comment] 2016-06-26 19:36
@Wuzzy2 acutally there's a PR #3659 that might make it work but it's not been merged or tested, so if you'd like to test it that would be good

**Comment by fluffyfreak** [comment] 2016-06-26 19:37
we still don't know why it happens which is more worrying for me

**Comment by roman-yagodin** [comment] 2016-07-02 19:50
Same thing for me on my first search & rescue mission - mission info says the target ship needs 1t of hydroden fuel, I'm having 1t of hydrogen fuel in cargohold, but transfer failed due to missing fuel.

**Comment by walterar** [comment] 2016-07-06 14:03
This bug continue without solution until it merges #3659 or until someone finds a better solution. It may be years.

**Comment by fluffyfreak** [comment] 2016-07-13 19:59
@walterar merged #3755 which was a fixed up version of #3659 after I investigated and could not figure out what the cause of the bug was.

**Comment by walterar** [comment] 2016-07-14 12:09
@fluffyfreak  It is an emergency solution to the problem. There is much work to do in that module, but worth it. Hopefully clausimu back soon.

**Comment by roman-yagodin** [comment] 2016-07-16 20:22
Does the provided fix work only with new missions? I still cannot deliver fuel in 20160710, mission taken in older game version.

**Comment by walterar** [comment] 2016-07-17 00:50
@roman-yagodin It is very likely that your saved game is definitely broken, unfortunately. You should have no problems with new missions.

**Comment by clausimu** [comment] 2016-07-25 17:03
@roman-yagodin - if you still have it, can you upload/send a save game that does not work? The fix did rescue the saved game posted by sfence originally. If yours is not working I would like to understand why.

**Comment by roman-yagodin** [comment] 2016-07-26 06:48
I've tested it again with 20160724 and it seems to be fixed. 

Here's the saves: https://github.com/roman-yagodin/bug-reports/tree/master/pioneerspacesim/pioneer/3627

**Comment by clausimu** [comment] 2016-07-26 13:16
Thank you, @roman-yagodin, for letting me know. I know the fix is only a patch that does not solve the underlying problem of why serialization sometimes has slip ups. But that has to be fixed by someone much smarter than me. I believe this can be closed now.

**Closed** 2016-07-26 15:34 UTC
