### ISSUE TITLE
Layout: misaligned box in personal -> eco & trade-context

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4701] opened 2019-10-10 15:02 UTC
Version: 2019-10-09
OS: Fedora 29

the upper edge of the content box is to near the top window border:

![Pioneer-missalignedbox](https://user-images.githubusercontent.com/8317797/66580939-7d798280-eb7f-11e9-9915-3ce497f77f97.jpg)

same for MISSIONS & ROOSTER pages.

Ship Info & Personal Info.. pages are correct.

**Comment by impaktor** [comment] 2019-10-10 17:12
Which resolution are you playing at? (should be visible in settings/options menu)

**Comment by Cyborgscode** [comment] 2019-10-10 17:15
1920x1080

**Comment by Cyborgscode** [comment] 2019-10-10 17:15
ups..

**Comment by Gliese852** [comment] 2020-01-11 20:35
It seems that the problem is with those pages that did not go to Pigui.
Lobby, Commodity Market, Equipment Market, Ship Info, Personal Info - Pigui - OK.
Bulletin Board, Ship Market, Ship Repairs, Police, Cargo Hold, Mission Info, Crew Roster - Not Pigui - Not OK.
So that everything resolves by itself when these pages go into pigui

**Comment by Web-eWorks** [comment] 2020-01-13 23:06
Gonna close this one as WONTFIX due to its nature as a byproduct of stripping out the newUI screens - as you said, it'll go away as soon as they're gone, so we don't really need to track this issue.

**Closed by Web-eWorks** 2020-01-13 23:06 UTC
