### ISSUE TITLE
Ground-based stations not placed on flat land

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#7] opened 2011-04-11 08:23 UTC
Original subject: Bentley Starport (Canqu [-2,-4]) is in wrong position.

Bentley Starport (Canqu [-2,-4]) is in wrong position. There is no possible to land in bay 2 due to collision with the planet surface. Alpha 9.01.

Logged by Mysibrat on SpaceSimCentral

**Comment by nozmajner** [comment] 2015-11-05 19:12
I guess it's already know that this happens again/still, but I thought I'll report it anyway (this issue was what other similar issues referenced.)
On Io, at Dante's base this happens again, the small pads of the station are buried under ground.
Then I tried reducing the detail level, hoping that then the terrain will be better. It did, but I was still unable to land, because the ship rough landed some 60m above the pad:
![screenshot-20151105-194459](https://cloud.githubusercontent.com/assets/4182678/10978686/89a7b510-83f8-11e5-8d99-f556ad2e6295.png)
Restoring to very high detail level did show that there supposed to be terrain on that spot:
![screenshot-20151105-195140](https://cloud.githubusercontent.com/assets/4182678/10978706/a6b9e68c-83f8-11e5-8c36-890ebe5c5ec2.png)
So I guess the collision doesn't updated with the terrain.

**Comment by Vektorweg** [comment] 2016-12-01 15:37
Had this bug today in Reedville, Gliese 623 .
![2016-12-01 1](https://cloud.githubusercontent.com/assets/2967485/20800021/4c362c2c-b7e4-11e6-84c7-8787af59a7c2.png)

This issue doesn't seem that closed in the 20161129 build.

**Comment by Talkless** [comment] 2017-09-08 18:49
I discovered same problem, after I switched fractal level from Medium to Low, Thebe Gas Refinery gone underground:
![thebe-gas-refinery-underground](https://user-images.githubusercontent.com/292191/30226639-4c7e3372-94c6-11e7-9bcc-141b290e34e5.png)

**Comment by impaktor** [comment] 2017-09-08 18:52
@fluffyfreak should this be reopened, or split (is it even possible in github?) to a new issue?

**Comment by jaj22** [comment] 2017-09-08 20:51
Checked out Thebe Gas Refinery. Looks fine on Low and Medium fractal detail here, 1.3km underground on Very Low. Possibly within the range of "working as intended".

**Comment by Vektorweg** [comment] 2017-09-09 00:39
it still breaks the game for some players. it can only be considered "working as intended", when very low fractal detail is dropped. but even then, there is still no guarantee, that this issue is solved for every ground station.

**Comment by jaj22** [comment] 2017-09-09 06:05
It doesn't break anything functional, just aesthetic. You can still fly to those stations. That terrain on Thebe also looks way more interesting from the inside than the outside. I stared at it for a while.

Thebe uses TerrainHeightAsteroid, which is literally four lines of code and so pretty easy to fix, although I'm never sure what the intention was with those height fractals. In this case you could simply remove the m_fracmult multiplier from TerrainHeightAsteroid.cpp, as it's a very cheap terrain function by Pioneer's standards.

**Comment by Talkless** [comment] 2017-09-09 08:46
> You can still fly to those stations. 

Well, you can't dock and finish mission.

**Closed** 2017-09-09 11:16 UTC
Labels:  CONFIRMED, Unexpected behaviour

**Comment by fluffyfreak** [comment] 2017-09-09 11:19
No this needs a new Issue if it needs tracking at all, I should just work out how to patch the problem for now
