### ISSUE TITLE
Reloading save in same system duplicates data

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4273] opened 2018-01-11 08:12 UTC
[Double-spawn bug on loading saved game](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=538&p=5407#p5407)

> Not sure if you're aware, but I noticed after a few times saving a game and re-loading while in the same system that game performance was dropping. I've discovered that the game acts as though you've entered the system for the first time when you load a saved game, thus spawns new ships, doubling the amount of traffic in the system. So if you stay in one system for a few saves, things get very busy indeed.

Just wanted to call attention to this, ping @johnbartholomew

**Comment by richardpl** [comment] 2018-06-18 17:54
I can not reproduce this, anybody can?

**Comment by impaktor** [comment] 2018-06-18 18:07
There's also some weirdness with crew contracs duplicating (and other adverts on BBS?) after load, I think, but that has its own issue.

**Comment by pcercuei** [comment] 2020-12-03 23:07
Adverts on the BBS definitely duplicate after a load:

![Capture d’écran de 2020-12-03 23-05-37](https://user-images.githubusercontent.com/403272/101099186-8e2b5a00-35c4-11eb-8923-4942124f1529.png)

**Comment by zonkmachine** [comment] 2024-08-11 01:29
Looks like the same as https://github.com/pioneerspacesim/pioneer/issues/5305 which was closed in https://github.com/pioneerspacesim/pioneer/pull/5456

**Closed** 2024-08-11 04:21 UTC
