### ISSUE TITLE
Crew for hire: empty

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#3456] opened 2015-09-18 14:40 UTC
Intended, or?
I dont think I would post on a BBS if I had nothing to offer,
Crew for hire: empty offer on Gates BBS right after starting a new game on earth.

**Comment by impaktor** [comment] 2015-09-18 14:47
> Crew for hire: empty offer on Gates BBS right after starting a new game on earth.

Well, it's random, so not sure if that will help reproduce it, but you could have a look at the code (data/modules/Crew) to see if you can think of why that could happen

**Comment by joonicks** [comment] 2015-09-18 14:52
Imho, it shouldnt post unless there is atleast one crew to hire, so, I see it as a bug/flaw

**Comment by demolitions** [comment] 2015-09-25 09:38
I have looked into this, been able to reproduce, and want to contribute a fix, it is a very simple matter (currently the number of crew generated can be 0), but I wanted both the devs and your advice:
Is it better to:
1) have always at least one crew to hire at every station
2) not post the advert if no crew to hire is generated

In the meanwhile, I'm going to look out how to correctly make a contribution via GIT.

**Comment by impaktor** [comment] 2015-09-25 10:04
@demolitions Hi! I definitely vote for number 2. And we love to have you on board as a contributor.

**Comment by joonicks** [comment] 2015-09-25 12:30
maybe like this, generate 2 random numbers from -5 to 15 (example numbers), average them: to make extremes more unlikely, and if the result is below 1, dont post on the bbs, otherwise post the number of crew.

maybe it could take the population of the system into account?

**Comment by impaktor** [comment] 2015-09-25 12:43
The correct and "full nerd" way to do it is how it is done in second hand module, although it is quite overkill: [SecondHand.lua#L161](https://github.com/pioneerspacesim/pioneer/blob/master/data/modules/SecondHand/SecondHand.lua#L161)

But a simple scheme could be done as well. Yes, take population / station size is preferable. Without having looked at the code recently, I suspect it does the right thing, meaning, I see many crew contracts in London, but none in Bernard's Star, or other small stations.

My suggestion would be to just fix the bug and leave the code as is. If the existing code is replaced I want to see graph of how probability would depend on station size, like in #3220, and how it improves/changes the result of the current code.

**Comment by demolitions** [comment] 2015-09-25 13:02
Actually, I didn't plan to replace the current code, it already takes the system population in account, its only flaw is that it can generate 0 crew to add (ceil(0, random)), and the BBS post is added before the crew generation, this occasionally results in an empty post.
The only thing I thought worth doing was simply moving the AddAdvert call **after** the generation, and only executing it if enough crew is generated (at least 1).

**Comment by impaktor** [comment] 2015-09-25 13:07
@demolitions sounds good to me. 
We can always discuss further once you have the pull request open. If you want to play more on that file, we have: #2636, and #2408

**Comment by demolitions** [comment] 2015-09-25 19:57
Not adding the BBS post if there aren't enough generated crew introduces another bug, since the onCreateBB event is called once per station, and never again, a station that will not add the "Crew for hire" post in its first BB creation will never have a "Crew for hire" post.
I'm looking into creating it but controlling the enabled flag.

This issue is actually a nice way to get to know Pioneer's LUA code base.

**Comment by nozmajner** [comment] 2015-09-25 20:34
How about adding an entry in the advert that say there's nobody to hire? Like if it was some kind of crew hiring office, and but currently there aren't anybody looking for work?

**Comment by demolitions** [comment] 2015-09-25 20:40
@nozmajner That's exactly what I had in mind.

**Comment by impaktor** [comment] 2015-09-26 10:24
Fixed by #3465

**Closed by impaktor** 2015-09-26 10:24 UTC
