### ISSUE TITLE
Crash while orbiting Mars

### ISSUE THREAD

**Issue by CmdrBugbear** [pioneerspacesim/pioneer#4885] opened 2020-05-30 13:04 UTC
#4453 
# Observed behaviour
Newly compiled on Ubuntu, built from commit 1efa5cf17fcbd8b593fd7f5cfdb8541ea909e707.
New game.
Launched from station, established stable orbit at approx 10km altitude.
Time acceleration was at 10x
Game crashed with following output to the terminal:

Fatal: [string "[T] @modules/TradeShips.lua"]:625: attempt to index field 'dest_path' (a nil value)
stack traceback:
	[string "[T] @modules/TradeShips.lua"]:625: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>Fatal: Frame instance deletion outside 'DeleteFrame' [0]
terminate called after throwing an instance of 'fmt::v6::system_error'
  what():  cannot write to file: Bad file descriptor
Aborted (core dumped)

### Steps to reproduce
I haven't been able to reproduce this error in the subsequent few hours of play.

(Realistically, unless there is actionable information here, I'm happy for this bug to be closed unresolved.)

__My pioneer version (and OS):__
Pioneer built from git commit 1efa5cf17fcbd8b593fd7f5cfdb8541ea909e707

**Comment by Gliese852** [comment] 2020-05-30 13:51
It seems some AI trade ship tried to hyperjump into NOTHING.

**Comment by Web-eWorks** [comment] 2020-09-02 21:11
Without a savefile to reproduce the issue I can't realistically fix the root cause of this particular bug. Closing this as unresolved, thank you for being so understanding!

**Closed by Web-eWorks** 2020-09-02 21:11 UTC
