### ISSUE TITLE
Laser weapons do not damage ships

### ISSUE THREAD

**Issue by veksever** [pioneerspacesim/pioneer#5741] opened 2024-02-04 11:28 UTC
### Observed behaviour

Laser weapons do not damage ships. It only works at a very close distance (a few meters).

https://github.com/pioneerspacesim/pioneer/assets/99830004/eba5125e-de96-4c11-83ed-fe592e1fc2dd

### Expected behaviour

The laser should damage ships

### Steps to reproduce

1. Buy laser weapons
2. Call the ship through debugging tools
3. Shoot

__My pioneer version (and OS):__

ver 20240203 (e7f3122) on: Windows

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/pioneerspacesim/pioneer/files/14156517/output.txt)

**Comment by nozmajner** [comment] 2024-02-04 17:45
This might be a duplicate of #5695

**Closed** 2024-02-17 04:04 UTC
