### ISSUE TITLE
Hyperjump exit point is sometimes too close to White Dwarf

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#4479] opened 2018-10-20 13:16 UTC
### Observed behaviour
The hyperjump exit point is sometimes too close to a White Dwarf.
There is no chance of escape. The ship gets destroyed within seconds.

### Expected behaviour
Have a chance to survive.

### Steps to reproduce
Jump to a White Dwarf e.g. Van Maanen's Star (0, -2, 0)

__My pioneer version (and OS):__
current master

**Comment by WKFO** [comment] 2018-10-21 18:06
Van Maanen's Star has a surface gravity of 207186.972g. (for reference, Sun only has about 25-30g)
Exiting somewhere close to that star is rather unsettling.

**Comment by fluffyfreak** [comment] 2018-10-23 20:42
Erm, what stars did you jump from when testing, because I've had a variety of things happen.

Sometimes I miss the star and get flung out.
Sometimes I smash into it.

There's some randomness involved in exiting but it also depends on where you came from a bit.

**Comment by fluffyfreak** [comment] 2018-10-23 20:44
Also the calculation does take into account the mass of the target star when determining what your "orbital" velocity will need to be... though as you've noticed (_by dying_) it isn't always that reliable a calculation 😀

**Comment by WKFO** [comment] 2018-10-23 20:59
I never really looked at the code, but I know that the orbital speed formula requires the mass of the star. That's how physics (should) work.

I've jumped to Van Maanen's Star system from Sol and Epsilon Eridani a few times, and that's it.

I've also jumped between lots of other star systems, but the worst case was the orbital velocity was a little too high and I got suborbital trajectories. (At least that's what the orbit display told me.)

So Van Maanen's Star is the only one that required me to panic immediately.

**Comment by impaktor** [comment] 2018-10-24 13:39
One could spitt out an ordered list of the surface gravity of all stars pioneer has parsed, in some region, when starting the game, assuming star gravity is exposed to LuaAPI, if not it aught to be.

...then fly to the one with strongest gravity.

**Comment by fluffyfreak** [comment] 2018-10-24 19:45
@impaktor it works ok for Sagittarius A* ... which should have plenty of gravity. I think it's the exit angle calculation which is suspect and that could fail even with relatively low mass stars.

**Comment by fluffyfreak** [comment] 2018-10-24 19:50
If you look at the line starting here: https://github.com/pioneerspacesim/pioneer/blob/master/src/Game.cpp#L523

You'll see that I'm not 100% certain of my calculations in this area 😁

**Comment by quickdudley** [comment] 2018-10-27 02:55
This might have also caused me to crash into Barnard's Star; but that might also have been caused by putting too much trust in the autopilot.

**Comment by robothauler** [comment] 2019-01-01 13:36
I think this is solved since #4495. The only thing is that I'm approx. 400000AU away if I jump to Sagitarius A*. But I think this is a separate issue ;-)

**Comment by impaktor** [comment] 2019-01-01 19:48
Well, if you arrive > 100 AU from the targeted body, it sounds like it still needs fixing to me.

**Comment by mike-f1** [comment] 2019-08-08 11:55
The conditions in #4495 limits the internal radius.

For Sagitarius A* (big black hole) the first condition is the one used (also because of #4288...) and thus 400000AU for an orbit with a speed of 100Km/sec isn't so much.

You should look at:

https://github.com/pioneerspacesim/pioneer/blob/c469f576bbeca9ce3316e62223f8a6bb4c2ff512/data/systems/custom/02_black_hole.lua#L12-L14

compared to Sol:

https://github.com/pioneerspacesim/pioneer/blob/c469f576bbeca9ce3316e62223f8a6bb4c2ff512/data/systems/00_sol.lua#L10-L13

Thus, an orbit of 400000AU may sound irrealistic only if you don't look at these numbers: indeed orbits radiuses are proportional to masses).

I'm with @robothauler: it's time to close this...

Disclaimer: Mine are comments based on code, not theory...

**Comment by robothauler** [comment] 2019-08-08 18:25
Please wait. We can add a maximum distance. Maybe there is no solution for Sagitarius A* to reach Planet Terminus. But better than 400000AU away from the target.

**Comment by mike-f1** [comment] 2019-08-08 21:50
Adding a maximum distance, will constrain speed to be more of some value.

In particular, if this "hard" limit is triggered, you get exit speeds of more than 100Km/sec and this is what @cwyss would avoid (his first post).

But another side effect is that you raise exit speed in every system with enough mass to apply for more than 100AU.

**Closed** 2019-11-19 18:09 UTC
