### ISSUE TITLE
Segmentation Fault when requesting launch

### ISSUE THREAD

**Issue by beltsonata** [pioneerspacesim/pioneer#4741] opened 2019-11-18 21:44 UTC
Hi,
I've not been having much luck with stability so far but I managed to reproduce this one and get a stack trace. 

**Issue**

The game crashes with a segfault.

**Steps to reproduce**

1. Load up the the save game file attached to this ticket, called '8.zip'. 
2. Unpause time and make a launch request. 
3. The game crashes immediately with a segmentation fault. 

**Pioneer Version**

I built Pioneer from source. According output.txt, version is 20191117 (4dd3918b9). I'm running Xubuntu 18.04.1 on an old Dell Latitude E-6420. Specs:

8Gb RAM
Intel Core i5-2540M @ 4x 3.3GHz
NVS 4200M / nvidia proprietary driver 390.116
Resolution: 1600x900 (I run Pioneer fullscreen)

The stacktrace is from gdb. After hitting 'r' all I did was perform the steps above to reproduce the crash, then when the segfault occurred I got the backtrace.

Let me know if you need any other files or any other information.

[stacktrace.txt](https://github.com/pioneerspacesim/pioneer/files/3860787/stacktrace.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/3860789/output.txt)
[8.zip](https://github.com/pioneerspacesim/pioneer/files/3860797/8.zip)
EDIT: added [opengl.txt](https://github.com/pioneerspacesim/pioneer/files/3860849/opengl.txt)

**Comment by Web-eWorks** [comment] 2019-11-18 22:32
Oh, I was wondering how fast we'd find the first bug related to the FrameID changes. Thanks for tracking this one down!

The cause of the segfault is fairly simple - `DeleteCameraFrame()` doesn't handle being passed invalid frames or frames without parents. However, this behavior is being caused by a deeper problem - we're double-deleting the camera frame in the `SaveGame()` routine.

I'll get this one cleaned up and ready to go in a day or two.

@fluffyfreak in retrospect, maybe I should have dug into that FrameID PR further... I'm thinking we need to update the contribution guidelines wrt. enforceable PR size.

**Comment by impaktor** [comment] 2019-11-19 17:49
Is this related to the PR we merged from @mike-f1?

**Comment by fluffyfreak** [comment] 2019-11-19 18:11
Yeah, I'll take a look shortly unless @Web-eWorks beats me too it

**Comment by mike-f1** [comment] 2019-11-20 17:51
While waiting for a fix, I would suggest to disable autosave from option screen or, if already caught in this bug, to manually open "config.ini" in `~/.pioneer` in your home dir and set "EnableAutosave=0" before starting the game.

**Comment by vakhoir** [comment] 2019-11-21 18:35
Doesn't help. I don't think it's related to saving the game. In my case it crashes on launch, I don't even see anything past the main menu.

**Comment by Web-eWorks** [comment] 2019-11-21 18:56
@vakhoir ...Let me stash my changes and I'll get this fixed.

**Comment by impaktor** [comment] 2019-11-26 08:27
Fix merged

**Closed by impaktor** 2019-11-26 08:27 UTC
Labels:  CONFIRMED, C++ code, Crash or hang
