### ISSUE TITLE
Logitech Joystick doesn't work at all with Pioneer v2019-02-03 for Linux

### ISSUE THREAD

**Issue by gerrygk** [pioneerspacesim/pioneer#4564] opened 2019-03-26 12:01 UTC
Hi everyone,

my Logitech Extreme 3D Pro Joystick doesn't work with the newest Pioneer (v2019-02-03 64-bit) for Linux (used OS: Mint 19.1 x64 + Cinnamon). No axes or buttons are being detected when trying to set them up. The joystick itself is working properly, as determined by checking it with the jstest-gtk tool.

Btw, it works good with the same 64-bit software version for Windows 7 x64.

Any ideas of what could be the cause?
Thx in advance & greetings

**Comment by impaktor** [comment] 2019-03-26 12:37
But it used to work on Pioneer's linux version?

**Comment by gerrygk** [comment] 2019-03-26 14:43
I unfortunately don't have any experience with older pioneer versions on Linux OS's. Could try such a version in the next time...

As far as I remember, the joystick always used to work on all Pioneer versions for Win7 x64 that I tested (at least the last few official ones...).

**Comment by Web-eWorks** [comment] 2019-03-26 16:10
If the joystick is not being detected, it might be an issue with SDL, as that's what Pioneer uses for all of the low-level joystick handling. What version of SDL does your system have installed?

**Comment by gerrygk** [comment] 2019-03-26 17:16
I tried v20180203 now with Linux, setting up the joystick works just as I remembered.

How do I check the SDL version?

**Comment by impaktor** [comment] 2019-03-26 17:22
> How do I check the SDL version?

(For GNU/Linux) Check in yout package manager

**Comment by gerrygk** [comment] 2019-03-26 17:30
Using synaptic package mgr I get a whole bunch of libsdl entries

**Comment by gerrygk** [comment] 2019-03-26 17:35
Could you give me some more detailed information?

**Comment by gerrygk** [comment] 2019-03-26 18:29
After some research I now checked by using "dpkg -l | grep sdl".

The result is:

ii  libsdl-image1.2:amd64                      1.2.12-8                             amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-mixer1.2:amd64                      1.2.12-14                            amd64        Mixer library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-net1.2:amd64                        1.2.8-5                              amd64        Network library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2debian:amd64                      1.2.15+dfsg2-0.1                     amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                        2.0.8+dfsg1-1ubuntu1.18.04.3         amd64        Simple DirectMedia Layer
ii  libsdl2-image-2.0-0:amd64                  2.0.3+dfsg1-1                        amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-2.0-0:amd64                  2.0.2+dfsg1-2                        amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-net-2.0-0:amd64                    2.0.1+dfsg1-3                        amd64        Network library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-2.0-0:amd64                    2.0.14+dfsg1-2                       amd64        TrueType Font library for Simple DirectMedia Layer 2, libraries

**Comment by Web-eWorks** [comment] 2019-03-26 19:56
Hmm. I'm not aware of any regressions in SDL 2.0.8 that would be causing this issue. Could you take a look in your pioneer logfile for lines containing `SDL_JoystickOpen` and post the relevant lines if there are any?

It's also possible that your joystick isn't becoming visible to the program until after Pioneer has enumerated joysticks and set them up. I'm not sure why this would happen, and you would be seeing the same issue on the previous version if that were the case.

**Comment by gerrygk** [comment] 2019-03-27 10:45
Here's an extract from output.txt:

System Name: Linux
Host Name: 
Release(Kernel) Version: 4.15.0-46-generic
Kernel Build Timestamp: #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019
Machine Arch: x86_64
Domain Name: (none)



--------------------
SDL Version (build) 2.0.9
SDL Version (dynamic) 2.0.9
SDL Versions match
SDL_image Version (build): 2.0.4
SDL_image Version (dynamic): 2.0.4
SDL_image Versions match
Assimp Version: 4.1.0
FreeType Version: 2.9.1
GLEW dynamic version: 2.1.0
--------------------

Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding 'disabled,Key107,Key105' in config file for BindAxisPitch
invalid axis binding 'Joy030000006d04000015c2000000000000/Axis0/DZ0.15/E1,Key117,Key111' in config file for BindAxisRoll
invalid axis binding 'Joy030000006d04000015c2000000000000/Axis2/DZ0.15/E1,Key106,Key108' in config file for BindAxisYaw

**Comment by gerrygk** [comment] 2019-03-27 10:51
As one can see, with no SDL_JoystickOpen Lines, but JS axis binding doesn't work.

Also, I can't open the .pioneer/config.ini file with any editor.

Some further error reports in output.txt are:

import [libs/autoload.lua]: libs/autoload.lua did not return anything
import [ui/GalacticView.lua]: ui/GalacticView.lua did not return anything
import [ui/InfoView.lua]: ui/InfoView.lua did not return anything
import [ui/StationView.lua]: ui/StationView.lua did not return anything
nanosvg: /app/share/pioneer/data/icons/icons.svg 1024x1024
import [pigui/game.lua]: pigui/game.lua did not return anything
nanosvg: /app/share/pioneer/data/icons/logo.svg 512x512
import [pigui/init.lua]: pigui/init.lua did not return anything
import [pigui/mainmenu.lua]: pigui/mainmenu.lua did not return anything
import [modules/AIWarning/AIWarning.lua]: modules/AIWarning/AIWarning.lua did not return anything
import [modules/Advice/Advice.lua]: modules/Advice/Advice.lua did not return anything
import [modules/Assassination/Assassination.lua]: modules/Assassination/Assassination.lua did not return anything
import [modules/AutoSave/AutoSave.lua]: modules/AutoSave/AutoSave.lua did not return anything
import [modules/BreakdownServicing/BreakdownServicing.lua]: modules/BreakdownServicing/BreakdownServicing.lua did not return anything
import [modules/BulkShips.lua]: modules/BulkShips.lua did not return anything
import [modules/CargoRun/CargoRun.lua]: modules/CargoRun/CargoRun.lua did not return anything
import [modules/Combat/Combat.lua]: modules/Combat/Combat.lua did not return anything
import [modules/CrewContracts/CrewContracts.lua]: modules/CrewContracts/CrewContracts.lua did not return anything
import [modules/CrimeTracking/CrimeTracking.lua]: modules/CrimeTracking/CrimeTracking.lua did not return anything
import [modules/DeliverPackage/DeliverPackage.lua]: modules/DeliverPackage/DeliverPackage.lua did not return anything
import [modules/DonateToCranks/DonateToCranks.lua]: modules/DonateToCranks/DonateToCranks.lua did not return anything
import [modules/EasterEgg/Message.lua]: modules/EasterEgg/Message.lua did not return anything
import [modules/FuelClub/FuelClub.lua]: modules/FuelClub/FuelClub.lua did not return anything
import [modules/GoodsTrader/GoodsTrader.lua]: modules/GoodsTrader/GoodsTrader.lua did not return anything
import [modules/Mining.lua]: modules/Mining.lua did not return anything
import [modules/MusicPlayer.lua]: modules/MusicPlayer.lua did not return anything
import [modules/NewsEventCommodity/NewsEventCommodity.lua]: modules/NewsEventCommodity/NewsEventCommodity.lua did not return anything
import [modules/Pirates.lua]: modules/Pirates.lua did not return anything
import [modules/PolicePatrol/PolicePatrol.lua]: modules/PolicePatrol/PolicePatrol.lua did not return anything
import [modules/SearchRescue/SearchRescue.lua]: modules/SearchRescue/SearchRescue.lua did not return anything
import [modules/SecondHand/SecondHand.lua]: modules/SecondHand/SecondHand.lua did not return anything
import [modules/StationRefuelling/StationRefuelling.lua]: modules/StationRefuelling/StationRefuelling.lua did not return anything
import [modules/StatsTracking/StatsTracking.lua]: modules/StatsTracking/StatsTracking.lua did not return anything
import [modules/System/Explore.lua]: modules/System/Explore.lua did not return anything
import [modules/System/OutOfFuel.lua]: modules/System/OutOfFuel.lua did not return anything
import [modules/Taxi/Taxi.lua]: modules/Taxi/Taxi.lua did not return anything
import [modules/TradeShips.lua]: modules/TradeShips.lua did not return anything

**Comment by Web-eWorks** [comment] 2019-04-02 00:44
Hmm. I don't know what the issue is here.

@gerrygk those `invalid axis` errors appear to be coming from the older version of Pioneer; the code logging those errors isn't used for input bindings any more. Otherwise, there doesn't appear to be anything salient in the log.

**Comment by gerrygk** [comment] 2019-04-04 09:22
Ok. Must be from tested PSS v 20180203, sorry.

**Comment by gerrygk** [comment] 2019-04-04 09:24
Yes, I remember that all the files of the new version are being stored somewhere in .var in my home dir.

**Comment by gerrygk** [comment] 2019-04-04 09:47
Just checked .var/app/net.pioneerspacesim.Pioneer/.pioneer/output.txt.

Invalid axis bindings reports are the same...

**Comment by gerrygk** [comment] 2019-04-04 09:48
invalid axis binding 'disabled,Key107,Key105' in config file for BindAxisPitch
invalid axis binding 'Joy030000006d04000015c2000000000000/Axis0/DZ0.15/E1,Key117,Key111' in config file for BindAxisRoll
invalid axis binding 'Joy030000006d04000015c2000000000000/Axis2/DZ0.15/E1,Key106,Key108' in config file for BindAxisYaw

**Comment by Web-eWorks** [comment] 2019-04-04 17:30
@gerrygk those errors are thrown by the legacy input system trying to read the config entries for the new input system's bindings.

The legacy system is no longer used except in a very small handful of cases where it's simpler to rewrite the entire screen than convert it to the new input system. The code responsible for binding joysticks all uses the new input system code, so you can safely disregard those errors.

I don't have the time right now, but when I do, I'll sit down and implement some better logging and error checking for input detection.

**Comment by impaktor** [comment] 2019-04-16 12:07
So we have error messages that are for a system that's not in use?

**Comment by gerrygk** [comment] 2019-05-05 13:46
Sorry for the delayed answer.
All the error messages above seem to be generated from the newest PSS version (2019-02-03).

**Comment by Web-eWorks** [comment] 2019-06-02 16:20
@gerrygk now that #4607 is merged, can you compile latest master and retest? I've added better logging for joystick initialization which should help debug whether it's a system-level issue or something related to our input binding code.

**Comment by gerrygk** [comment] 2019-06-11 08:54
Until now, I never compiled PSS source under Linux. This also may take a while because currently I'm rather busy.
Don't forget that the joy worked formidable with the old PSS version of 2018. Maybe since then there's a change in the input binding code, that would be a first indication on the source of error.

**Comment by Cyborgscode** [comment] 2019-10-16 12:57
any updates here on the joystick front?

**Comment by gerrygk** [comment] 2019-10-16 13:33
Unfortunately not. I didn't yet have the time to take care of the compilation. Seems to be more complicated than doing it under Windows... Maybe someone else can do that. I'm the worst among all programmers.

**Comment by Web-eWorks** [comment] 2019-11-18 22:43
I have not seen any other reports of nonfunctional joysticks. Given the lack of activity, I'm closing this issue; if you can confirm the bug (with logs from the newest version!) then we can reopen it.

**Closed by Web-eWorks** 2019-11-18 22:43 UTC
Labels: Input, More information required, Unexpected behaviour

**Comment by gerrygk** [comment] 2020-02-11 19:40
Problem solved with own build and new version 2020-02-03

**Comment by marcorighi** [comment] 2022-08-29 21:35
Hi there,
I have a similar problem.

The joystick is a Logitech Extreme 3D' but `jstest-gtk` recognize it as 6 axis and 12 buttons.

Inside `jstest-gtk` the joystick works perfectly.

I downloaded Pioneers from AUR.

`
lsb_release -va

LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.3.7
Codename:	Ruah`

`
pioneer --version
ver 20210203 (142693b) on: Linux

System Name: Linux
Host Name: mm
Release(Kernel) Version: 5.15.60-1-MANJARO
Kernel Build Timestamp: #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022
Machine Arch: x86_64
Domain Name: (none)

--------------------
SDL Version (build) 2.0.10
SDL Version (dynamic) 2.0.22
WARNING: SDL Versions differ
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.6.1
WARNING: SDL_image Versions differ
Assimp Version: 5.2.0
FreeType Version: 2.10.1
GLEW dynamic version: 2.0.0
--------------------

Initialized OpenGL 3.1, with extensions, renderer
Initializing joystick subsystem.
Found joystick 'Logitech Extreme 3D' (GUID: 030000006d04000015c2000010010000)
- 4 axes, 12 buttons, 1 hats
- axis 0: deadzone 0.00, curve: 1.00, half-axis mode: 0
- axis 1: deadzone 0.00, curve: 1.00, half-axis mode: 0
- axis 2: deadzone 0.00, curve: 1.00, half-axis mode: 0
- axis 3: deadzone 0.00, curve: 1.00, half-axis mode: 0
font orbiteer:
- Orbiteer-Bold.ttf 1.000000
- DejaVuSans.ttf 1.200000
- wqy-microhei.ttc 1.000000
font pionillium:
- PionilliumText22L-Medium.ttf 1.000000
- DejaVuSans.ttf 0.928571
- wqy-microhei.ttc 1.000000
Warning: Commodity rubbish has invalid producing economy ALL
Loaded economy info: 3 economies, 31 commodities (10 consumable)

started 3 worker threads in 0.21ms
Engine startup took 931.79ms
LoadStep::Start()
ShipType::Init()
Lua::Init()
Loading [08%]: Lua::InitModules() started
nanosvg: /usr/share/pioneer/data/icons/icons.svg 384x384
nanosvg: /usr/share/pioneer/data/icons/icons.svg 512x512
nanosvg: /usr/share/pioneer/data/icons/icons.svg 1024x1024
nanosvg: /usr/share/pioneer/data/icons/logo.svg 512x512
Ship Def found: missile_unguided
Ship Def found: missile_guided
Ship Def found: ac33
Ship Def found: missile_naval
Ship Def found: natrix
Ship Def found: vatakara
Ship Def found: varada
Ship Def found: kanara_civ
Ship Def found: dsminer
Ship Def found: deneb
Ship Def found: wave
Ship Def found: venturestar
Ship Def found: nerodia
Ship Def found: xylophis
Ship Def found: storeria
Ship Def found: skipjack
Ship Def found: sinonatrix_police
Ship Def found: sinonatrix
Ship Def found: pumpkinseed_police
Ship Def found: pumpkinseed
Ship Def found: molaramsayi
Ship Def found: kanara
Ship Def found: bowfin
Ship Def found: missile_smart
Ship Def found: amphiesma
Ship Def found: malabar
Ship Def found: molamola
Ship Def found: lodos
Ship Def found: bluenose
Ship Def found: lunarshuttle
30
Loading [08%]: Lua::InitModules() took 242.76ms
Loading [15%]: Gui::Init() started
Loading [15%]: Gui::Init() took 2.37ms
Loading [23%]: GalaxyGenerator::Init() started
Creating new galaxy generator 'legacy' version 1
Warning: 'mass' is 0.000000 for body 'Themisto'
Warning: 'mass' is 0.000000 for body 'Lucksmall'
Number of factions added: 103
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 101, slave hits: 0, master hits: 2
Loading [23%]: GalaxyGenerator::Init() took 18.26ms
Loading [31%]: FaceParts::Init() started
Face Generation source images loaded.
Loading [31%]: FaceParts::Init() took 681.47ms
Loading [38%]: new ModelCache started
Loading [38%]: new ModelCache took 0.00ms
Loading [46%]: Shields::Init started
Loading [46%]: Shields::Init took 1.40ms
Loading [54%]: BaseSphere::Init started
GenerateIndices: triangles count = 648, mid indexes = 1728, hi edges = 54
Loading [54%]: BaseSphere::Init took 49.78ms
Loading [62%]: CityOnPlanet::Init started
Got 20 buildings of tag city_building
- Dome1: 39.626175
- Dome2: 48.596382
- Library: 64.693522
- Mall: 26.159388
- Tower1: 33.094160
- Tower2: 34.924003
- kbuilding01: 29.664692
- kbuilding02: 46.268344
- kbuilding03: 41.542333
- newbuilding1: 36.202756
- newbuilding10: 16.297418
- newbuilding11: 34.961034
- newbuilding2: 22.822782
- newbuilding3: 22.649894
- newbuilding4: 25.978193
- newbuilding5: 22.908506
- newbuilding6: 29.817877
- newbuilding7: 22.674426
- newbuilding8: 23.154979
- newbuilding9: 36.528138
End of buildings.
Loading [62%]: CityOnPlanet::Init took 163.59ms
Loading [69%]: SpaceStation::Init started
ground_station has:
 14 entrances,
 14 pads,
 0 exits
new_ground has:
 6 entrances,
 6 pads,
 0 exits
orbital_station_2-10k has:
 5 entrances,
 64 pads,
 5 exits
orbital_station_2-2k has:
 4 entrances,
 18 pads,
 4 exits
orbital_station_2-5k has:
 5 entrances,
 64 pads,
 5 exits
orbital_station_2-5k10k has:
 5 entrances,
 64 pads,
 5 exits
Loading [69%]: SpaceStation::Init took 500.21ms
Loading [77%]: NavLights::Init started
Loading [77%]: NavLights::Init took 0.07ms
Loading [85%]: Sfx::Init started
Loading [85%]: Sfx::Init took 16.94ms
Loading [92%]: Sound::Init started
Loading [92%]: Sound::Init took 397.29ms
Loading [100%]: PostLoad started
Loading [100%]: PostLoad took 0.02ms
Pioneer loading took 2123.12ms
Stars picked from galaxy: 0
Final stars number: 500000
Pi shutting down.
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 101, slave hits: 0, master hits: 1

`
