### ISSUE TITLE
wave forward gun fires backwards

### ISSUE THREAD

**Issue by NotEnoughPotions** [pioneerspacesim/pioneer#5928] opened 2024-10-05 23:59 UTC
For some reason when flying the wave, the forward and rear gun fires backwards.

**Comment by zonkmachine** [comment] 2024-10-06 00:25
Duplicate of https://github.com/pioneerspacesim/pioneer/issues/5776 ?

**Comment by NotEnoughPotions** [comment] 2024-10-06 00:46
huh so it is, ill close this, sorry

**Comment by NotEnoughPotions** [comment] 2024-10-06 00:47
duplicate

**Closed** 2024-10-06 00:47 UTC
