### ISSUE TITLE
Pioneer app not opening

### ISSUE THREAD

**Issue by RayReaper** [pioneerspacesim/pioneer#5579] opened 2023-04-12 15:49 UTC
I was running the app for the first time (via the itch.io app) and it failed to open. I checked the details of the error and it said (the directories it is in)/pioneer/release/pioneer: error while loading shared libraries: libassimp.so.5: cannot open shared object file: No such file or directory

Is this an error on my side downloading it? Is there something I need to download to open the app, or could it be because I am using Linux even though I downloaded the version for Linux?

Thanks

**Comment by impaktor** [comment] 2023-04-12 16:25
Please see: #5148

And please download pioneer from our official site, or grab the most recent build from github actions, e.g. [this](https://github.com/pioneerspacesim/pioneer/actions/runs/4628684926)

**Comment by impaktor** [comment] 2023-04-14 06:40
I assume this is duplicate of above -> closing

**Closed by impaktor** 2023-04-14 06:40 UTC
